Automattic/newspack-blocks

package.json, src/setup/blocks.json, webpack.config.js
WIP. 
Inspired by https://github.com/Automattic/jetpack/pull/11802. The idea is to encapsulate complexity in `@automattic/calypso-build` and provide a nice enough interface to consumers.
=> Blocks: Make webpack.config.extensions.js extend calypso-build's

babel.config.js, package.json
Verify that blocks still build fine.
---
I'll clean up babel plugin deps in a follow-up PR. That will require some work on the Calypso side (https://github.com/Automattic/wp-calypso/pull/32144) (and a new release of `calypso-build`) first.
I also plan to file a separate PR to simplify the webpack config. Thought it might be fine to keep things small and separate.
=> Simplify babel.config.js

babel.config.js, package-lock.json, package.json
Introducing the `calypso-build` binary, and allowing us to drop the babel config. Seems to build alright! :tada:
=> Bump calypso-build version to 1.0.0-rc.3

package-lock.json, package.json
Just published latest version.
[Changelog](https://github.com/Automattic/wp-calypso/blob/master/packages/calypso-build/CHANGELOG.md)
> # 2.0.0
> 
> - Breaking change: Remove babel plugins incompatible with TypeScript. If your bundle continues to
>   compile without error, no changes are necessary. These babel plugins were removed:
> 
>   - [`@babel/plugin-proposal-export-default-from`](https://babeljs.io/docs/en/babel-plugin-proposal-export-default-from):
>     Code relying on this plugin will need to be modified for compatibility before it can be bundled
>     with `calypso-build`. For example:
> 
>     ```js
>     // Code relying on @babel/plugin-proposal-export-default-from
>     export someExportedName from 'some-module';
> 
>     // becomes
>     export { default as someExportedName …
```
=> Upgrade calypso-build to v2

package.json
This simply renames the build script from `build` to `build:webpack` to match https://github.com/Automattic/newspack-plugin for consistency's sake.
To test:
1. Check out this branch.
2. `npm ci && npm clean`
3. `npm run build:webpack`
Verify no errors and that `dist` directory has been created and populated.
=> Consistent Build Script Name

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR is a bit of a mixed bag of changes, but they collectively tighten up the layout of the article blocks a bit: 
* Reduces the space between the columns when you've set the article block to display as grid.
* Gets the author avatar, name and published date on one line when there's room for it (the display when there isn't room for all three still needs work; the date sits below the avatar if it's there, which looks strange). 
* Adjusts the vertical space between articles, and with the post meta. 
* Removes an extra `<p>` tag from around `the_excerpt()`, and reworks the post meta markup a bit to allow for the current layout.
1. Set up a couple article blocks - one with multiple items displayed in one column, and second with the grid.
2. Check it over.
3. Apply the PR; confirm a few …
=> Tighten up layout of the article blocks

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR updates the section header to use an `h2` tag, so it will inherit the theme's heading styles.
It also conditionally switches the tag used on the article titles, from `<h3>` when there is a section header, and `<h2>` when there is not. 
I also added a `.use-header-font` class to the post meta, so the font doesn't have to be explicitly set in the theme. 
Related to discussion here: https://github.com/Automattic/newspack-theme/pull/49#pullrequestreview-246552526
1. Apply the PR.
2. Set up an article block without a section header; publish and check the markup.
3. Add a section header.
4. Confirm that the markup of the section header uses an `<h2>`, and that the article title goes from `<h2>` to `<h3>`.
5. Try a couple different font scale values, and make sure the font size of the …
=> Update 'section' header markup to make it use a h2 tag

src/blocks/homepage-articles/view.php
This PR adds `ignore_sticky_posts` to the query that generates the posts that display on the front end.
This makes sure the posts shown in the editor match the front end, and also make sure the number of posts shown matches what's set in the editor. 
I can see there being a case for the sticky posts behaving like sticky posts in these blocks, but I think overall it will cause more confusion/problems than it will be useful. 
Fixes #27.
1. Mark a post as 'sticky'; preferably one deeper in the post archives.
2. Set up a homepage block with the same category as the sticky post (or all posts). Set a specific number of posts to display.
3. Save and publish.
4. On the front end, note that the sticky post displays first, and the total posts showing is +1 more than you selected.
5. Apply the PR. …
=> Add `ignore_sticky_posts` to the output of the homepage blocks

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php
This PR adds a 'More' link option to the block. When a block uses a specific category, the 'More' link leads to that Category's archive page. When a block uses 'All' categories, the link will go to the blog posts page. 
Known issues:
* In the editor, the 'More' link just links to `#`, rather than the correct link it uses on the front-end. The primary reason is complexity -- I got blocked trying to find a way to pull the current query's category's URL. I'm happy to circle back to this in a separate ticket, but it seems like it can be moved forward without. 
* The link has no styles included in the block; it uses the generic class `.button`, so it inherits the editor's button styles; on the front-end it successfully picks up the Newspack theme's styles for `.button`. My plan is to update …
=> Adding 'more' link option to the Newspack blocks

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR updates the `.article-*` classes used in the block to the more standard `.entry-*` classes used for posts in many themes (thanks to them being used in default themes and _s). 
The hope is that this will help the blocks inherit the theme's styles with minimal interference, though right now it may cause some visual breakage (for example, the theme will have to pass its .entry-meta styles to the editor for them to look right; this isn't standard at the moment -- post meta doesn't appear in the editor yet -- but I expect it will be down the road. 
1. Visually review the block.
2. Apply the PR.
3. Make sure it looks _mostly_ the same. As noted, some adjustments will be needed in the theme, so the post meta will not use the correct font in the editor, but the other fonts used (post …
=> Update classes to match "standard" theme classes

src/blocks/homepage-articles/edit.js
This PR removes live links from the block in the editor. As noted in https://github.com/Automattic/newspack-blocks/issues/52 it's easy to accidentally click a link in the editor and be unexpectedly taken to another page. 
Closes #52
1. Add an instance of `Newspack Homepage Articles`, with `Show Author` checked.
2. Click on the title and author name, and verify no navigation occurs.
3. Test both with and without a block heading. This subtly alters the rendering of post titles.
4. Preview or publish the post, and verify that all links work as expected in the view.
=> Remove Live Links In Editor

src/blocks/homepage-articles/sass/_variables.scss, src/blocks/homepage-articles/view.scss
This PR updates the homepage block's font sizing to switch it from pixels to ems, so it inherits the general font sizing from the theme using it.
It also updates the font size variables to match sizing used in the theme; they're not used in the homepage article blocks, but I left them in place in case we need them for another block. If it turns out we don't, and we stick with using ems, they can be removed. 
1. Set up the homepage block using the different sizes, or copy-paste this example into the code view of the block editor: https://cloudup.com/cKNYeV2Gil3
2. Apply the PR and run `npm run build`.
3. Confirm that the font sizing hasn't really changed.
=> Update font sizing to use ems

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/query-controls/index.js, src/blocks/homepage-articles/view.php
https://github.com/Automattic/newspack-blocks/issues/41 suggests filtering by Author. This PR adds an Author select to `QueryControls` which can be used to filter a block's results by author. The first item in the select is "Any Author," which does not filter by author at all.
1. Create a good set of test posts by creating multiple authors and assigning them to variety of posts.
2. Add a few instances of Newspack Homepage Block to a page or post.
3. Change the `Author` dropdown and verify that the filtering works.
=> Add Author Select

src/blocks/homepage-articles/view.php
This PR is an attempt to ensure that multiple articles blocks on the same page will not show the same post more than once. Some questions and caveats:
- This PR only affects the view (preview/published content). In the editor there will still be duplicate posts. This will be addressed in a separate PR.
- Currently this logic will be applied to every instance of `Newspack Homepage Articles` block. Would we need the flexibility to exempt certain blocks from the logic? 
- Blocks will be processed in the order they appear on the page, with higher prioritized stories going to the first ones. It is possible that an unusual layout could be produced where the topmost block is not the visually dominant one, which could lead to unexpected distribution of posts.
This is a partial resolution of …
=> Avoid Post Duplication (View Only)

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/query-controls/index.js, src/blocks/homepage-articles/view.php
Adds a Select to the top of the **Display Settings** Panel for selecting a specific post. If a selection is made, only this post will be shown, and any category, author, or limit settings will be ignored. In the sidebar, the category/author/limit will actually be hidden if a post selection has been made to avoid confusion. 
Big caveat! A select control is definitely not the right UI for this because of the potentially huge number of posts. A select is used in the customizer for setting the homepage Page so I opted to go this way at first, but it will need to be replaced. The Select will only display the 20 most recent posts, so the current version is not yet as flexible as it needs to be. I propose we consider this PR as-is so that the basic functionality is addressed, then consider …
=> Specify Single Post

src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.scss
This PR is a adaptation of #57, and adds an optional border style to the homepage blocks.
When the articles are in one column and there's more than one, the borders appear under each post but the last one:
When they're set to display as a grid, the borders are displayed in-between vertically, switching to horizontal when viewed on smaller screens:
2. In the editor, set up an article block with multiple articles, displayed in one column; add the 'Border' styles.
3. In the editor, set up an article block with multiple articles, displayed in a grid; add the 'Border' style.
4. Test the visuals on both the front-end and in the editor.
=> Add 'border' styles to the blocks

src/blocks/homepage-articles/edit.js
This PR ups the number of posts available in the 'Display Single Post' option in the block from 20 to 50. I'm finding 20 is not quite enough to find the posts I'm trying to find; this should still be low enough to not slow things down.
2. Add the block; confirm that there is now more than 20 posts appearing in the 'single post' dropdown.
=> Increase posts list limit from 20 to 50.

newspack-blocks.php
* Introduce utility method to check if the current request is for AMP.
* If so, do not enqueue blocks JavaScript files in the frontend.
Closes #77  .
1. Follow the steps outlined in the issue, but in the end no validation errors should be reported.+
=> Introduce utility method to check for AMP requests and do not enqueue JS if so

src/block-styles/core/columns/editor.scss, src/block-styles/core/columns/index.js, src/block-styles/core/columns/view.scss, src/shared/sass/_variables.scss
This PR adds a 'border' style to the column block.
It also removes an unneeded style from the re-ordering styles (`flex-wrap: nowrap`).
This PR does need a couple adjustments to the theme, as far as when the columns break -- the theme overrides the Gutenberg default for some reason, so you get some odd column spacing as you shrink the browser window down. I've added a fix for this in https://github.com/Automattic/newspack-theme/pull/314; that PR will need to be applied to the theme to get the same results as some of the screenshots below.
I realize this is a pretty odd approach -- I couldn't find a good way to use `border-right` and maintain the even column spacing, and I wanted to mess with the main styles of the block (like left and right margins) as little as possible. I'm open to …
=> Add a 'border' style for the columns block

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php
This PR adds a link to the featured image when shown in the Homepage Article block.
Closes #71.
1. Apply PR and run `npm run build:webpack`
2. Add a article block; make sure at least one of the articles has a featured image.
3. Confirm in the editor that the image is wrapped in a link, pointing to `#`.
4. Confirm on the front-end that the image is wrapped in a link, pointing to the full article.
=> Adds links to the featured images in the homepage article block.

src/shared/sass/_variables.scss
This PR updates the block styles breakpoint for tablet-sized screens to match Gutenberg's, so we don't have odd moments at different screen sizes. 
A related fix is included in the theme in https://github.com/Automattic/newspack-theme/pull/334.
2. Add a homepage article block and set it to display as a grid.
3. Confirm that the columns change to display as one column at screen sizes smaller than 782px, rather than 768px.
=> Update breakpoint for block styles to match Gutenberg's

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php
Since it mostly duplicates the button block, but with less functionality and more complexity, we've opted to kill the in-block 'more' button. The recommended alternative is using the button link; if we find we need something 'smarter' (like automatically generating a link with an offset) we can approach that separately.
Closes #94.
1. Apply the PR and run `npm run build:webpack`; confirm there are no errors.
2. Confirm that the 'more' button option is no longer there.
3. Double-check it's no longer referenced in the code.
=> Remove 'more' button option from the article block.

src/blocks/homepage-articles/view.scss
This PR makes some improvements to the article block breakpoints, when using it on smaller screens. It looks like:
```
Desktop:     1 col     2 col     3 col     4 col     5 col     6 col
Tablet:      1 col     2 col     3 col     2 col     2 col*    3 col
Mobile:      1 col     1 col     1 col     1 col     1 col     1 col
* The five column block splits into two rows of two, and one row of one, if it's an uneven number. 
```
2. Copy-paste [this test content](https://cloudup.com/cRUjc4KWHpk) into the code editor; it adds six blocks, one of each column width.
3. Confirm the correct column counts are showing for the desktop size screen.
4. Scale down the browser window to less than 768px but more than 600px -- to emulate a tablet-sized screen. …
=> Article Block: Improve breakpoints for smaller screens

class-newspack-blocks-api.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR adds the option to show the image caption for the featured image in the Homepage Article Block.
It uses a very standard tag -- `figcaption` -- that right now is styled too specifically in the theme, so it's not being applied. I'm hoping to clean that up in a separate PR for the theme; ~~I may need to circle back and make adjustments for the font-scaling in the block after that, but for the time being, there are no styles for the caption in the block (so it looks a bit blah).~~ 
Edited to add: I did make some size and spacing adjustments for the block in 63bbae8, but tried to keep them in line with the level of styles added to the block so far.
I updated the markup used for the featured image to a `<figure>` tag, which is more standard with what's used for the image block.
I set …
=> Adds optional image caption to the homepage article blocks.

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.scss
This PR adds two new font size options to the block, and adjusts the sizes throughout, to make them more consistently stepped, and have a more logical number of options (10 instead of 8).
Closes #113 .
2. Copy-paste [this test content](https://cloudup.com/cyAELLSyDMb) into a post - it includes 10 blocks in ascending sizes.
3. Confirm that the blocks are visually different from one another, and seem like reasonable sizes, both on small screens and large screens.
=> Article Blocks: Add additional font sizes

src/blocks/homepage-articles/view.scss
This PR increases the vertical space between the articles on mobile.
It also re-adds the bottom border on the last item; in isolation it makes sense, but when the blocks are stacked with other content, keeping the bottom border actually makes more sense. 
**Before:**
**After:**
Closes #112
2. Add [this test content](https://cloudup.com/csBihgHGv1B) to a post to add the article block with or without borders, or build your own.
3. Shrink the browser window down to mobile size (note: there's an issue with the borders moving to the bottom before the columns are stacked; I'll tackle that in a seperate PR.
4. Confirm that the last item in the first block has a border.
5. Confirm that the vertical spacing is enough to visually separate the …
=> Article Block: Increase spacing between articles on mobile

src/blocks/donate/view.scss
This PR removes the default blue border from the 'Other' donation field.
It also adds a darker border when the field is in focus, and makes the 'Donation amount' text darker.
**Before:**
**After**
Closes #111 
1. Add a donation block; note its appearance; click the 'Other' link to view the text input.
2. Apply the PR and run `npm run build:webpack`
3. Confirm that the blue border is no longer on the text input; focus on the input to confirm that it uses a darker grey.
=> Standardize border styles in 'other' value input

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR adds a text colour picker to the Article Blocks; the purpose is to change the text to white or another light colour when the block is placed on something with a dark background, but it should allow you to change the text to any colour.
Note: For style packs that use the primary colour for the text in the header (Default, 3 and 4), if the primary colour in the theme is customized, it will override the block's setting in the editor.
It's more appropriate to fix this in the theme, so I'll tackle that in a separate PR. 
Closes #97.
2. Add an article block to a page, and switch it to a pre-defined colour from one of the first four spots (the primary and secondary colour); confirm it's applied.
3. Add a second block to the page, and pick a …
=> Article Blocks: Add text colour picker

src/blocks/homepage-articles/view.php
The 'Show Featured Image caption' option in the homepage block has mismatched default settings, so it always displays as 'on' on the front end, and can't be turned off there (it will preview as off in the editor)
This PR sets them both to 'off'.
1. Add an article block to a page; make sure at least one of the articles has a featured image with a caption.
2. View on front-end; note that the caption is visible.
3. Apply the PR and run `npm run build:webpack`.
4. Confirm that the caption is now hidden on the front end.
5. Turn the captions by turning on 'Show Featured Image Caption' in the editor.
6. Confirm that the captions correctly display when enabled.
=> Article block: Making sure showCaption is set to false by default everywhere.

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php
This PR adds a class to the article block when the captions are set to show; it can then be used to help iron out any styles that may need to be changed in this case (there are some visual issues with Style 3's title overlap when captions are enabled). 
Note: this is probably best to test after #125 is merged.
2. Add an article block to a post or page; turn on 'Show Featured Image Captions'
3. Make sure the class `show-caption` appears on the main article container in the editor.
4. Save and publish.
5. Make sure the class `show-caption` also appears on the front end.
6. Turn off 'Show Featured Image Captions' in the editor.
7. Confirm that the class `show-caption` no longer appears in the editor or front-end.
=> Article Block: Add class when captions are enabled

src/blocks/homepage-articles/view.scss
This PR makes sure the captions that can be shown in the Articles Block will inherit the custom text colours that you set.
1. Add an article block to a page; make sure at least one post has a featured image, and that featured image has a caption.
2. In the block settings, enable 'Show Featured Image Caption'
3. In the block settings, pick a custom colour.
4. Note that the caption is not using the colour, in the editor or on the front-end:
5. Apply the PR and run `npm run build:webpack`
6. Confirm that the caption text colour now matches your custom colour selection, in the editor and on the front-end:
=> Article Block: Make sure captions inherit custom text colour

src/blocks/homepage-articles/edit.js
This PR makes the `per_page` API param for the tags API call valid. Currently it always returns a 400 error, and no tags populate in the field:
This should solve the direct issue. However, virtually every site has >100 tags, so this isn't an ideal solution. I think an autocompleting remote search (e.g. https://select2.org/data-sources/ajax) is the best solution for the author/category/tag/etc. search in the block.
1. Attempt to filter an article block by a tag. Observe no tags are in the list.
2. Apply this PR.
3. Attempt to filter an article block by a tag. Observe it works correctly.
=> Fix article block tag API param

newspack-blocks.php, src/blocks/homepage-articles/view.scss
This PR reduces the size of the smallest type scale option for the block (based on feedback), and refines the differences between different sizes a bit.
Closes #130.
1. Copy-paste [this test content](https://cloudup.com/comkHU8FNUj) into a post or page; it has a copy of the article block in each size. 
2. Note its appearance.
4. Confirm that the smallest size is now smaller (14px); also confirm that the difference between each of the different sizes seems fairly consistent, and they're noticeably different from each other. 
(And just let me know if anything is "off"!). 
(I messed something up with the version bump PR, causing the commit to show up here -- master should already have it set to '6').
=> Reduce size of smallest type scale options

src/blocks/homepage-articles/view.scss
This PR reduces the vertical spacing between individual articles, as part of work to tighten up the layouts you can build with it.
Closes #131.
**Before:**
**After:**
1. Copy-paste [this test content](https://cloudup.com/ccsEbt1y09P) into the editor.
2. View in the editor and on the front end; note the vertical spacing.
4. Confirm that the vertical spacing is reduced, but the articles still appear "separate"
=> Reduce vertical spacing between articles

src/block-styles/core/group/editor.scss, src/block-styles/core/group/index.js, src/setup/block-styles.js
This PR replaces #138, and adds align left and align right options to the block settings.
The appearance of these blocks will be improved in #465. 
2. In the editor, add a Group block, and align it left:
3. Add  a second group block and align it right.
4. Confirm the block displays as expected in both the editor and on the front-end.
=> Add left/rightblock alignment option to the group block

class-newspack-blocks-api.php, newspack-blocks.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR adds three fixed image sizes to the blocks plugin -- Landscape (800 x 600), Portrait (600 x 800) and Square (800 x 800). It's not a perfect solution to our image size issue (and I've outlined why below), but hopefully it's a good starting point towards a solid, useful fix. 
Some known issues:
* If the original image is smaller than the custom image size, it won't be cropped.
* The image sizes I've picked -- 800 x 600, 600 x 800 and 800 x 800 -- are a bit to small to fill the content space (1200); especially if we're talking about images for retina screens, where we'd ideally be starting with images twice as large as they need to be (so a minimum of 2400px).
These two images kind of push and pull each other: we need to make the image sizes smaller to work with small archive images …
=> Article Block: Add image size options

class-newspack-blocks-api.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR adds a toggle for displaying categories on posts. I've used the theme's `cat-links` class for the category, so they should be more-or-less already styled just like other category links on the site. When possible, the block will pull the primary category from WPSEO instead of using whichever category it first sees.
If this looks good, I'll make a follow-up PR on the theme repo to add some handling on a couple of the alternate styles to make sure things look good. In general, they look pretty good out-of-the-box.
1. Activate WPSEO if it isn't already active. On a post that will be featured in the block, select 2+ categories. A dropdown should appear to let you select a primary category. Select a primary category different than the default:
2. On your home page, insert an articles …
=> Add toggle for displaying categories

src/block-styles/core/columns/view.scss
This is a partial fix for an issue with the columns and the border styles.
Right now, the even width columns display the borders correctly at the tablet breakpoint, but the (fixed) custom width columns do not. All but the last set of columns have custom widths; the sets with two columns are okay, but the one with three is messed up:
This PR switches it so that the borders display correctly when you have custom column widths (but breaks the 'default' widths):
I'm not sure if there's a great way around this - perhaps if we extend the column block further to add a class if it uses custom block widths? I'd be very interested in getting some feedback on possible approaches.
In the meantime, if you want even-width columns, you can manually set them to even widths (50%, 50%, or 33.33%, 33.33%. …
=> Improves column plus borders behaviour

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php
Right now, the `.has-text-color` class is always applied to the article block, which is causing some colour issues with the 'section header'.
This PR fixes the class issue and visual issues on the front-end; an incoming theme PR, paired with this PR, will fix the remaining preview issues in the editor.
Closes #137.
1. Add a couple article blocks to the editor, and give each of them a 'section header'.
2. Leave one block as-is, select a colour from the colour palette for the second one, and a custom colour for the third. 
3. Note the appearance of each block on the front end. With style packs default, 3 and 4, the text should match the primary colour; for 1 and 2, it should be grey. In the block using default colours, though, it will always look black:
**Default:**
**Style 1**
**Style 2** …
=> Article Block: Fix issue where has-text-color class was always being applied

src/blocks/homepage-articles/editor.scss, src/blocks/homepage-articles/view.scss
This PR is part of a two-part process to update the newly added 'category styles.
On the block level, this PR updates the styles, making sure they mostly match on the front-end and in the editor, and that they're visible when you use the image-as-background option, and don't get in the way when you use the 'show image caption' option.
There will be a second PR on the theme side, to adjust some more style pack-specific issues. I'd recommend testing this with one of the style packs with limited styles on the `.cat-links`, like Style 2 or 4.
2. Add 5 article blocks; in all three, turn on 'Show Category'.
3. The blocks will need the following settings, at least one post in each will need an image:
a) One block with the default, images hidden: …
=> Article Blocks: Adjust category styles a bit

src/blocks/donate/editor.scss, src/blocks/donate/view.scss, src/setup/newspack-logo.js
* Update the `$primary_color` variable
* Adjust the Newspack logo
1. Check out the branch and execute `npm run build:webpack`
2. Test the blocks and see if any of the old blue is still appearing
=> Update the Primary Color to use Newspack new blue: `#36f`

src/block-styles/core/columns/editor.scss
There appears to have been a change in the core column block styles, so the editor preview of our 'reordering' block style was overlapping a bit.
This PR fixes that by making the selector a bit more specific.
1. Make sure you're running the latest version of the Gutenberg plugin.
2. Add a columns block to a page, and change the style to the 'Move first column to second' style.
3. Note the appearance in the editor -- the first and second columns should be kind of overlapping:
4. Apply the PR and run `npm run build:webpack`
5. Confirm that the issue is resolved.
=> Columns Style: Fix editor preview of column reordering

src/blocks/homepage-articles/edit.js
Use the same icon as the Cover Block since it has a fairly similar behaviour
1. Apply the PR and `run npm run build:webpack`.
2. Add a newspack block; make sure at least some of the articles in it have featured images.
3. In the toolbar look for the icon "Show media behind". Does it make sense?
=> Update the icon of the background image style

src/blocks/homepage-articles/index.js
This makes it easy for users to switch to Newspack Homepage Articles if they were already using the core block for showing latest posts. It transforms all configuration attributes that are shared between the two blocks.
It also provides a transformation for the opposite direction. Due to Newspack having much more options for configuration, the way back is not lossless. Things like specific styling, filtering categories/authors/tags will be lost on the way because it's just not supported on the other side.
Shared options: number of posts to show, layouts (list/grid), number of grid columns, showing a date, and showing an excerpt.
1. Start a new page and insert "Latest Posts" block from the core.
2. Configure the block in different ways and always try to transform it into Newspack Homepage …
=> Add transforms to and from core/latest-posts

src/block-styles/core/columns/view.scss
_This is an experiment_
This will allow our theme to lighten its CSS since most of the magic is now handled here.
I added a flex `nowrap` starting from mobile devices (600px) to make sure we overwrite Core. It also changes the behaviour of child elements by adding the same right/left margin to all of them.
I also tweaked the border style behaviour on smaller screens.
See: https://github.com/Automattic/newspack-theme/pull/493
1. Check out this branch and recompile the blocks
2. You will also need to [update the theme](https://github.com/Automattic/newspack-theme/pull/493)
3. Add different sizes of columns, does it work as expected?
=> Rework Columns Block with a more opinionated styles in our plugin

newspack-blocks.php, package-lock.json, package.json, src/blocks/carousel/create-swiper.js, src/blocks/carousel/edit.js, src/blocks/carousel/editor.js, src/blocks/carousel/editor.scss, src/blocks/carousel/index.js, src/blocks/carousel/view.js, src/blocks/carousel/view.php, src/blocks/carousel/view.scss, src/blocks/homepage-articles/query-controls/index.js
Adds a Carousel block that uses `amp-carousel` to display posts.  `amp-carousel` cannot currently be used in the editor because it does not support DOM mutation after page load, which occurs whenever the array of posts to be displayed changes. Eventually Bento AMP will resolve this, but until this is available we will use the Swiper library to make the block functional in the editor. Currently, there is only a placeholder in the editor.
Closes https://github.com/Automattic/newspack-blocks/issues/48.
1. Check out the branch and execute `npm run build:webpack`
2. Add Articles Carousel block to a post.
=> Carousel Block

src/blocks/homepage-articles/view.scss
In reviewing sites, I noticed the varying avatar sizes looks a bit odd on smaller screens.
It changes based on the type scale, but when you get down to a certain point, the fonts are all pretty small -- it makes more sense to get the avatars consistent, too.
1. Set up a page with multiple blocks of different sizes, or [copy paste my test content.](https://cloudup.com/cyohq3mASrd)
2. View on the front end; scale down the browser window to a smaller size, and note the variation in avatars -- it's subtle, but they're all slightly different sizes:
3. Apply the PR and run `npm run build:webpack`.
4. Confirm that the avatars are now all the same size on screens tablet-sized and smaller:
Their sizes will still vary on screens larger than that.
=> Make avatar sizes more consistent on small screens

src/blocks/homepage-articles/view.scss
This PR tightens up the vertical spacing within the articles in the article block, as an attempt to make them become more visually distinct from each other without increasing space between each article (though we can do that, too, if needed).
1. Add some article blocks to a page with different settings (with/without images, font sizes).
2. View the articles on large and small screen sizes; note the vertical spacing between photos, titles, content and post meta.
4. View the articles again; confirm that the spacing is reduced, and things look better (as opposed to worse - no one wants that!).
=> Article Block: Reduce vertical spacing within articles

src/blocks/homepage-articles/view.scss
In an attempt to create some predictable behaviour, I changed the article block to include a border under the last item. Unfortunately, this leads to a lot of doubled borders, especially on smaller screens, or at the very bottom of the page.
I think it ultimately makes more sense to remove the bottom border from the last item; the only time it seems to make sense to keep it is if you only have the block set to show one article; if it doesn't show on the last article in that case, it won't show at all.
1. Set up three article blocks: one with one article, one with several articles displayed as a list.
2. Apply the 'borders' style to all three.
3. Confirm that the last article in each block does not have a bottom border, unless it is the block only displaying one article. 
Note: I noticed …
=> Article Blocks: Remove bottom border of last item

src/block-styles/core/columns/view.scss
This PR increases the vertical space between columns when they're stacked on small screens. 
Before: 
After:
1. Add a column block to a page, and add some content; apply the border style to make testing easier.
2. View on the front end and shrink the browser window down to mobile size; note the spacing between the columns.
4. Confirm that the spacing is now increased.
=> Increase vertical spacing for columns block when stacked

class-newspack-blocks-api.php, newspack-blocks.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php
This PR adds an image sizing option to not crop the featured images in the Article Block.
It sets the 'crop' image size to 1200px wide by any height; if the original image is smaller than this it won't be changed at all, but unlike the images for the other settings, it's totally fine if images with these settings aren't cropped.
2. To affect existing images, Install and run the Regenerate Thumbnails plugin. 
3. Create a new post; use this test image as the featured image: https://cloudup.com/crTPisEKtkg
4. Set up an article block to pull this post; view how it looks with the default (Landscape) image shape:
5. Edit the block; switch the image cropping to "no crop" (last option):
6. Confirm that the full image is now displayed:
=> Article Block: Add option to not crop the images

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php
This PR adds the class `.show-category` to the `wp-block-newspack-blocks-homepage-articles` container when you've selected the 'Show Category' option for the block.
This can then be used to adjust styles in themes (for our purposes, it'll be super helpful for styling 'Style 3').
2. Add an article block; turn on 'Show category' in the settings.
3. On the front-end and in the editor, confirm that there's a `.show-category' class added to the block.
=> Article Block: Add 'show-category' class when category is displayed

block-list.json, package.json, webpack.config.js
An alternate approach to block exclusion. `block-list.json` provides a list of blocks to be built in production builds. In non-production builds all available blocks are built, but in production only the ones explicitly named in the `production` array will be. Optional `--block-list=filename.json` parameter allows overwriting the default list. Releases packaged using the `release:archive` script are now production builds. 
Replaces https://github.com/Automattic/newspack-blocks/pull/177.
1. Run `npm run build:webpack`, verify all current blocks are built and available (Donate, Articles Carousel, Newspack Homepage Articles).
2. Run `NODE_ENV=production npm run build:webpack`, verify the same. 
3. Edit `block-list.json`, and remove `carousel` from the `production` array. 
4. Run `npm run …
=> Block List

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR replaces the `type-scale#` classes with `ts-#`, to help reduce the generated CSS size.
1. Start with a handful of article blocks set to different type sizes.
2. Apply the PR and run `npm run build:webpack`
3. Confirm that the different type scales are still in place.
=> Simplify type scale class to reduce CSS.

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/editor.scss, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR adds a new class -- `wpnbha` -- as a short form to use for the block styles. It'll help reduce the CSS volume. In my testing, the generated view.css for this block went from 17kb to 12kb.
2. On a page with several article blocks, make sure that the styles are still applied as expected on the front-end, and in the editor.
=> Add short version of block CSS class to reduce amount of styles.

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR replaces the `image-scale#` class with `is-#`, to reduce CSS characters.
1. Add a couple article blocks to a page; make sure the articles have images.
2. Float all of the images right or left, and give them different image scales.
4. Make sure the image scale sizes are still respected in the editor and on the front-end.
=> Swap out 'image-scale' class with 'is-'.

src/blocks/donate/edit.js, src/blocks/donate/view.php, src/blocks/donate/view.scss
This PR adds a second, shorter main class used by the donate block, so it can then be used to make the CSS lighter.
1. Add a donation block to a post or page.
2. Apply the PR and run `npm run build:webpack`
3. Confirm that the donation block still looks the same on the front-end and in the editor.
=> Donation Block: Simplify main donate block selector

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php
This PR is kind of a combination of #197 and #198 -- it adds a 'min-height' control to the article block when you have the image set to display behind the article. But rather than just adding a minimum height, it also adds 20% of that value as a top padding. 
This is to help make sure the blocks don't lose all top spacing on smaller screens -- I was finding when you added a moderate min-height to an article with an excerpt, as it scaled down for smaller screens, it would often be 'shorter' than the article's new height, making it seem like it wasn't applied at all. 
The padding won't add anything when the min-height is taller than the article would normally be, but adds a bit of top padding when the min-height is shorter than the content. 
See #153 .
1. Apply the PR and run `npm run …
=> Article Block Height: Add range control for minimum height + top padding (option D)

src/block-styles/core/columns/view.scss
This PR tightens up the vertical spacing on columns when stacked on mobile; their originally spacing worked well for the article blocks, but looked a bit odd with anything else. 
Closes #201 .
1. Set up a page with a couple columns blocks; add paragraphs to each, and set one to use the border style, and one to use the default style (you can also copy-paste [this](https://cloudup.com/c17cyvkzAOC) into the code editor).
2. View on the front-end; make the browser window very narrow and note the spacing -- it seems to work with the border style, but a bit spacy without the borders:
4. Confirm that the spacing is now tightened up:
=> Reduce vertical spacing between columns when stacked on mobile.

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/editor.scss, src/blocks/homepage-articles/view.scss
This PR tightens up the top and bottom spacing for the excerpt in the article block.
This will help create more distinction between separate articles. 
1. Add an article block to a page. Note the spacing around the excerpt in the editor:
2. Note the spacing on the front-end (tighter on the top, but spacier between the bottom and author):
4. View the block in the editor; confirm it's tightened up:
5. View on the front end:
=> Article Block: Tighten up vertical spacing around article excerpt

class-newspack-blocks-api.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/editor.scss, src/blocks/homepage-articles/view.php
This PR adds support for the Co-Author Plus plugin to the Article block.
I also removed the link to the author archives from what we're making available to the API, since we don't actually use it in the editor anymore. 
Closes #200.
2. If you haven't already, install and activate the [Co-Authors Plus](https://wordpress.org/plugins/co-authors-plus/) plugin.
3. Create one 'Guest Author'.
4. On one article, add a second author; on a second article, add two. Make sure one is the Guest author and the other is a standard WordPress user. This gives us a good mix of different author types and numbers.
5. On a page, add the article block, and adjust the settings to make sure the above two posts are displayed, plus one with one regular author.
6. View …
=> Article Block: Add Co-Author Plus plugin support

src/blocks/homepage-articles/edit.js
This PR adds 'help' text to the Article Block's minimum height control:
See #199 
1. Apply PR and run `npm run build:webpack`
2. Add an article block to the editor; set it up to show the featured image behind the text.
3. Confirm you see the 'help' text, like in the screenshot above.
4. Confirm it makes sense (or suggest improvements! It's kind of a weird thing to try to describe, especially when many people seeing it will have no idea what `vh` is).
=> Article Block: Add 'help' text to the minimum height control

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR is kind of a proof of concept for a suggested alternative to #215.
It makes sure that, when images are floated left or right, they will display at 33% of the screen width on mobile (rather than the 50% or 75% you can pick in the settings). 
This is an attempt in making sure the images and associated article content don't get too wildly different in size.
1.[ Copy paste this test content into a page](https://cloudup.com/cbRSWTxIOmB) -- it includes four article blocks, each with a different 'image scale' setting, a text size of 2, and no author/date displayed. They're also nested in a column block, so it's a little closer to a normal case where you'd have image/text side by side.
2. View on front-end; make sure each article has an image (if not, add one to that post).
3. Shrink down …
=> Make sure images have a max-width on small screens

package.json
I've noticed this repo is missing a start script — a way to rebuild sources on file update. Calypso build has the watch param so I've used it here. 
Previously, I was using `npm run build:webpack -- --watch` which is kinda inconvenient.  This way it would be just `npm start`, like it's common in many other projects.
1. `npm start`
1. Build succeeds
1. Edit JS/CSS file
1. It should rebuild automatically
=> Build: add start task to watch and rebuild source

languages/newspack-blocks.pot, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/index.js
This PR renames the `title` and `descriptions` of the Homepage Articles block. 
it's a simpler approach compared with https://github.com/Automattic/newspack-blocks/pull/227.
1. Apply this brown changes
3. Tests with blocks already created before these changes.
4. Confirm that everything is working as expected.
5. Create a new `Homepage posts` block.
6. Check that `article` has been replaced by `post`: inserter, block preview, etc.
=> homepage-articles: rename title and descriptions

src/blocks/homepage-articles/index.js
Instead of using the "Dashboard" Material icon, like Jetpack Tiled Gallery, I suggest we use a different one: "Library Books" as it feels more generic.
__Before:__
__After:__
1. Try to add an Homepage Articles block. And a Jetpack Tiled Gallery. Icons should look fairly similar (one is outline the other isn't...)
2. Switch to this branch
3. Do the same. Does it look better?
=> Update block icon to avoid clash with Jetpack Tiled Gallery

class-newspack-blocks.php, package-lock.json, package.json, src/blocks/donate/editor.scss, src/blocks/donate/view.scss, src/shared/sass/_legacy_colors.scss
This PR updates `calypso-build` to the latest version, 5.1.0. 
The update removes a few Sass Muriel color variables that the Donate block uses. I didn't want to introduce any style changes in this PR so I created a temporary Sass file with these variables (https://github.com/Automattic/newspack-blocks/compare/update/calypso-build-5.1.0?expand=1#diff-d7cc79577ac5a9dd72abcdbc89faa614). In a future PR we should replace the Muriel color values and remove this file, cc: @thomasguillot. 
The approach to dependency extraction changes in this update to use https://developer.wordpress.org/block-editor/packages/packages-dependency-extraction-webpack-plugin/. 
1. `npm ci`. Verify `calypso-build` updates to version 5.1.0.
2. `npm run start`. Verify all blocks build with no errors.
3. Test normal …
=> Update Calypso Build to 5.1.0

src/blocks/homepage-articles/view.php
Add filter for Homepage Posts block registration in order to allow other plugins to override it or change as needed.
1. Install the plugin
2. Build its assets
3. Use plugin and confirm Homepage Posts block work as expected (both in editor and on frontend)
Filter call is added but not implemented directly in this plugin so there should not be any change in functionality. 
The diff on GitHub doesn't look very clean but all that was done it that arguments were wrapped in a filter call.
=> Make block name and args filterable before registration

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/editor.scss
* For the Featured Image Scale, replace the RangeControl with a combination of ButtonGroup and Button.
* Changed the label to "Featured Image Size"
* Instead of using numbers (1 - 4), I switched to sizes (S - XL) with aria-label
My reasoning is I feel like "1 - 4" is very abstract when it comes to image sizes whereas "S - XL" might be more appropriate here. What do you think?
_Note: Ditching the Dashicon here makes me happy._
__Before:__
__After:__
2. Add a Homepage Articles block to a page
3. Display the Featured Image on the right or left (make sure your posts have a Featured Image!)
4. In the sidebar you should see a "Featured Image Size" setting (vs "Featured Image Scale" previously). Play with it.
5. Does it make more sense than "1 - 4" to you?
=> Use a ButtonGroup and Button for the Featured Image Scale instead of RangeControl

class-newspack-blocks.php, src/blocks/homepage-articles/view.php
Second PR taken from https://github.com/Automattic/newspack-blocks/pull/226 to extract pieces of functionality. This one extracts the preparation of the args to be used by `WP_Query`. Currently there is only one use of this function but in 226 it is needed in multiple places.
Differences between this PR and 226:
- `build_articles_query` is a static class method of `Newspack_Blocks` rather than a global function. 
- `$posts_to_show` needs to be available because it's used in the loop: https://github.com/Automattic/newspack-blocks/compare/try/extract-query-building?expand=1#diff-0bc1373b8d23b0320f8a67d468c37a1eR16
There should be no changes to the functionality of the block. Build and verify no regressions.
=> Extract Query Builder

class-newspack-blocks.php
Doesn't add a default alignment.
We could also remove the `align` attribute business altogether, given the block doesn't support that attribute currently.
Closes #26.
1. Load the block in the frontend and make sure the wrapping div does not have the class `aligncenter`.
=> Don't set default alignment.

class-newspack-blocks.php, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/templates/articles-list.php, src/blocks/homepage-articles/templates/articles-loop.php, src/blocks/homepage-articles/view.php
This PR extracts the templates from https://github.com/Automattic/newspack-blocks/pull/226, and copies over a the template include function (`newspack_blocks_template_inc` in 226, `Newspack_Blocks::template_inc` here). On a great tip from @claudiulodro the templates are wrapped in  `call_user_func(function( $data ) { template_contents }, $data)` so variables used within are scoped and don't need to be prefixed. I did not carry over the `READ MORE` button markup from 226, but I did leave the wrapper `<div>` and new placement of the heading to help us see if either of these changes will cause visual regressions.
This is the last of three PRs that deal with significant code refactoring related to the Read More button.
Output should be visually and functionally identical to `master` branch.
=> Extract To Templates

newspack-blocks.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
Adds API endpoint from #226 (incl. `block.json`).
Navigate to `/wp-json/newspack-blocks/v1` on your test site and make sure you get a valid response.
=> Add REST endpoint from #226

.phpcs.xml.dist
Bump the minimum test version of PHP for PHPCS  to 7.0. 
Add some post-5.3 code and verify that  PHPCS doesn't warn.  For example:
```
$newspack_blocks_test_array = [];
$newspack_blocks_test_operation = $newspack_blocks_test_array ?? true;
```
=> Bump PHPCS Test Version

src/blocks/homepage-articles/templates/article.php
This PR replaces the `wp_kses_post()` sanitation on avatars with a custom `wp_kses()` one, to make sure we're not accidentally stripping out things needed for Jetpack lazy loading images to work correctly (like `data-*` attributes, or the `noscript` tag). 
Closes #249.
1. Add the article block to a page, and make sure avatars are enabled on it.
2. Turn on Jetpack's lazy loading images, and turn off AMP.
3. View on front-end and note the double-images:
4. Apply the PR and run `npm run build`.
5. Confirm that the avatars are no longer duplicated:
6. Try turning on AMP, and confirm there are no issues.
7. Toggle Co-Authors Plus (either activate the plugin if it's deactivated, or deactivate it if it's activated), and make sure there are no issues.
=> Article Blocks: Update sanitization for author avatar

src/blocks/homepage-articles/view.js
Replaces apiFetch with XMLHttpRequest. (I wasn't sure how serious we take IE11 support).
This fixes a bug with apiFetch on wp.com, where it always sends an `X-wp-nonce` header that wp.com rejects. See https://github.com/Automattic/jetpack/pull/12823/commits/c8029269a4ee6bc126fd072d1e00043f7871d6cd
I open to other fixes. Jetpack seems to have just gone with `fetch`, fine with that, too. I'd just like it to work on wp.com :) 
1. Set up a block with more button and make sure it still loads new posts.
=> Replace apiFetch

src/blocks/homepage-articles/view.php
Hide/show the Load More button based on  value of the  `Show "More" Button` toggle.
Closes https://github.com/Automattic/newspack-blocks/issues/266.
1. On `master`, add a `Homepage Posts` block, keep `Show "More" Button` toggled off.
2. Publish and  view. Observe the `Load more articles`  button is visible.
3. Switch to this branch and try again. Observe the button is hidden.
4. Toggle the option on and Update post.
5. Observe the button is now visible.
=> Show/hide Load more button based on block attribute.

src/blocks/homepage-articles/view.php
This PR fixes an issue where the author name wasn't linked to the correct location when the Co-Authors Plus plugin is deactivated. 
Closes https://github.com/Automattic/newspack-theme/issues/623.
1. Add an article block to the homepage; make sure at least one author that displays has a two word display name, or their display name and username/slug are different.
2. Deactivate the Co-Authors Plus plugin, if active.
3. Click on one of the author links; note the URL it tries to go to is their nice name, rather than their slug:
4. Apply the PR and run `npm run build`.
5. Confirm that the link now works:
6. Turn back on the Co-Authors Plus plugin and confirm the link still works.
=> Article Block: Fix issue with author link not working

src/blocks/homepage-articles/templates/article.php
The link around the author avatar is getting stripped out; this issue was introduced in #261.
1. Add an article block to a page.
2. Hover over the author avatar; notice that the image no longer has a link.
3. Apply the PR.
4. Confirm that the image now has a link, and it points to the author's archive page.
=> Fix issue with author avatar link getting stripped out

src/blocks/homepage-articles/index.js
This PR adds a filter to the transform function from `core/latest-posts` block, in order to be able to change the block name.
These changes don't affect the current behaviour of the block, so just be sure that it still works as expected. Anyway, if you want to test it, you can define the transformation name adding a filter with this name:
```es6
function setBlockTransformationName( name ) {
return name !== 'newspack-blocks/homepage-articles'
? name
: 'the-new-name-for-the-transformed-block`;
}
addFilter(
'blocks.transforms_from_name',
'set-transformed-block-name',
setBlockTransformationName,
);
```
=> nha: add `blocks.transforms_from_name` filter

class-newspack-blocks-api.php
Only adds custom rest fields for requests with the edit context.
Avoids adding those fields to public requests and only surfaces that information to authenticated users.
Fixes failing wp.com unit tests in D36572-code.
1. Make sure adding a Homepage Posts block still works and it displays all the usual information.
2. Check the `/wp/v2/posts` endpoint unauthenticated to not include these fields.
=> Add rest fields only to edit context

src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
Adds support  for an  `exclude_ids` parameter. As with the normal rendering logic, this avoids using `post__not_in` logic and instead queries for more posts than were requested and sorts out which to return in PHP logic. This is related to  https://github.com/Automattic/newspack-blocks/pull/263, which tacks on an array of all visible posts so they will be excluded.
This one is a little tough to test without https://github.com/Automattic/newspack-blocks/pull/263. Here's one approach:
1. Branch switch to `update/load-more-with-post-ids`.
2. Add several `Homepage Posts`blocks, and switch on `Show "More" Button`.
3. Publish and view the post.
4. With web inspector open to Network->XHR tab (Chrome), click the `Load More Posts` button.
5. You should see requests that look something like this: …
=> Exclude  IDs In Load More Posts Endpoint

src/blocks/homepage-articles/edit.js
As reported in https://github.com/Automattic/newspack-blocks/issues/277, if a Post contains an instance of a block which displays the  current Post, editing the Post title causes the block to break. Normally `post.title` is an object, but after an edit to the current post it comes back as a simple string. The change in this PR accounts for this situation.
Closes https://github.com/Automattic/newspack-blocks/issues/277.
1. Create a post, save and publish.
2. Add Homepage Posts block. Observe the top Post shown is the  current one.
3. Edit the title of the current Post  and save. 
4. Observe the block reflects the title change and doesn't crash.
=> Handle Post Title As String

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
As reported in https://github.com/Automattic/newspack-blocks/issues/279 there has been a regression around the full-width alignment option due to the introduction of an additional `div` related to the Load More button. This PR resolves this by moving the classes and style up to the top-most div and fixing a styling issue created by the new hierarchy.
Closes https://github.com/Automattic/newspack-blocks/issues/279.
1. Switch to a theme that supports Full Width (e.g. Newspack Theme)
2. Create a post or page and add the Homepage Posts block. If you are using  the Newspack Theme switch to the `One Column` or  `One  Column (Wide)`  template.
3. Set the block to Full Width alignment.
4. Publish and view on the front end. 
5. Verify that the block is full width.
=> Fix Full Width Alignment

src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php
This PR implements several improvements to the `More…` button:
* Adds the needed CSS classes in order to try to show the button visually equivalent in both sides (Frontend and Editor canvas)
* Set the same button-text in both sides
* Default text: `Load more articles`. It's debatable and easily changeable.
* Be able to set a custom text for the button.
Closes #275 
Check styles on both sides.
**BEFORE**
**Editor Canvas (Twenty Twenty)**
**Frontend (Twenty Twenty)**
**AFTER**
**Editor Canvas (Twenty Nineteen)**
**Frontend (Twenty Twenty)**
Same as **before**
**Editor Canvas (Twenty Nineteen)**
**Frontend (Twenty Nineteen)**
**Editor Canvas (Maywood)**
**Frontend (Twenty Maywood)**
* Confirm that an additional field appears when it enables the `Show "More" Button` 
* Editing the `Button …
=> NHA: `More…` button improvements

src/blocks/homepage-articles/view.scss
Many themes output both a 'published' and 'updated' time for posts, and hide the latter.
The NHA block does this too, but it has relied on the theme hiding the updated time. Because of this, it's visible with themes that don't (like Twenty Twenty). This PR adds styles to hide it to the block.
Closes #283.
1. Switch to a theme that doesn't hide the `.updated` class (like Twenty Twenty).
2. Add a Homepage Block to a page.
3. Pick a post displayed by the block that was published earlier than today, and edit it. Save and publish.
4. View the block on the front end; you should see two dates, like in the first post below:
5. Apply the PR and run `npm run build`.
6. Confirm that the second date no longer displays, and only the one representing when the post was originally published is shown:
=> NHA: Add styles to hide `.updated` class

src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.js
Add `exclude_ids` query param with currently rendered posts IDs to the "More" request URL. This should be used to address the post duplication issue (paYJgx-jW-p2#comment-418, paYJgx-jW-p2#comment-433).
1. Add `Homepage Posts` block & make sure there are any posts to render
2. Go to preview and open network tab in browser's devtools (filter by XHR)
3. Click the "Load more articles" button and check if `exclude_ids` param has been set to the request URL with correct posts' IDs.
=> Add rendered posts' IDs as "Load More" query param

class-newspack-blocks.php, newspack-blocks.php, src/blocks/homepage-articles/templates/article.php
Closes #281. More info in my comment there.
This PR makes 3 small changes to fix image handling issues I noticed:
- https://github.com/Automattic/newspack-blocks/commit/2e8b905ec15c3ded35f7c82b5a8f1f4ac80c606f just saves a bunch of work looping through every possible thumbnail size on posts that don't have images.
- https://github.com/Automattic/newspack-blocks/commit/38b67ba46892184c1250c4ba282a62821388b61c fixes an issue where if an image doesn't match any Newspack thumbnails there is weird behavior around the class names output on the image. `large` seems like a reasonable fallback size.
- https://github.com/Automattic/newspack-blocks/commit/1e69dba87732600f3b84780645faf14a35e19868 moves things around so the image sizes will get registered in the FSE plugin.
There are definitely easier …
=> Fix some issues with image handling

class-newspack-blocks-api.php, src/blocks/homepage-articles/edit.js, src/components/query-controls.js
This PR cleans up a few React errors and warnings that have been in the codebase for awhile. These include missing `key` attributes and the use of deprecated `@wordpress/editor`. The console won't be completely clean as there are a number of other warnings and errors that aren't related to the block. 
1. Checkout `master`, build the block `npm start`. 
2. Add a few blocks to a Page or Post and interact with them.
3. In the developer console observe numerous instances of:
```
Warning: Each child in a list should have a unique "key" prop
```
and
```
wp.editor.RichText.isEmpty is deprecated. Please use wp.blockEditor.RichText.isEmpty instead.
```
4. Check out `fix/react-errors`, rebuild, and reload the page in the editor.
5. Observe these errors are gone. As noted above there may be other …
=> Resolve React Errors

src/block-styles/core/columns/editor.scss, src/block-styles/core/columns/view.scss
**Note:** there will be a complementary theme PR to make sure this update doesn't break the border styles in style packs 3 and 5. This one should not be merged until that one is also ready to merge.
Edited to add: this is the related theme PR: https://github.com/Automattic/newspack-theme/pull/632
When you create a column block, give it the border styles, and nest a second column block inside of it, that second block incorrectly inherits those styles. This PR fixes that.
Closes #228.
1. On a page, add a column block and apply the border styles. Inside one of the cells, nest a second column block.
2. For testing regressions, also add a second column block with the border styles, but that's not nested.
3. Use any style pack but 3 and 5 (since they have different border styles, which this PR …
=> Columns styles: Make sure nested columns don't inherit border styles

newspack-blocks.php, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.scss
This adds **post subtitle** (Automattic/newspack-theme#635) handling for Homepage Articles block. 
Post subtitle can now appear in the block:
And this can be toggled in the block settings:
=> Handle Post Subtitle

src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
- Following up [this comment](https://github.com/Automattic/newspack-blocks/pull/263#discussion_r357091226), improved block's selector scope by adding a unique selector for the block (parent) element. This is needed to be sure the global selectors we use don't accidentally catch other elements on the page.
- Added some margin to button element to improve default visuals a bit.
Before (`Twenty Twenty`):
After:
Apart from the `top-margin` added to the `Load More Posts` button, there should not be any other noticeable changes.
=> Load More Script Improvements

src/blocks/homepage-articles/edit.js
In addition to the deduplication work, https://github.com/Automattic/newspack-blocks/pull/289 removes a few unused imports and variables that have been out of use for some time. To simplify 289 a bit I've  moved all the clean-up to  this PR.
Try the block, make sure everything works as before, with no breakage.
=> Clean Up For 289

amp/homepage-articles/view.js, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
Adds AMP compatibility for the Homepage Posts bock Load More button. 
1. Begin by verifying the block behaves exactly as it does on `master` in non-AMP requests.
2. Install AMP plugin, use Transitional mode.
3. View page with Homepage Posts block on it, switch to AMP request, verify identical behavior.
4. Test in pages with multiple Homepage Posts blocks. There should be no duplicate posts displayed after clicking Load More buttons.
5. Test in a variety of browsers.
=> Load More Button: AMP Compatibility

package-lock.json, src/blocks/carousel/create-swiper.js
On Linux machines, the import statement may no work if the correct case is not used. This was happening with the Swiper dependency. This change ensures the correct case is used.
=> Fix case-sensitive import

src/blocks/homepage-articles/view.scss
This PR fixes some issue with the grid option for the article blocks, and how they work with the border styles.
Closes #284.
1. Copy-paste [this test content](https://cloudup.com/cbeiotXfh3p) into the editor. It include 10 copies of the article block: two with two columns, with and without borders; two with three columns, with and without borders, all the way up to six columns.
2. View the five column, bordered block on the front-end and note the odd spacing:
3. Shrink the browser window down to tablet-sized, and note the border placement on the blocks with borders -- even though there are still articles sitting side by side, the borders have now moved to the bottom of each article: 
4. Apply the PR and run `npm run build`.
5. Confirm that the five column block is now consistently spaced, …
=> Homepage Blocks: Fix grid display with and without borders

src/blocks/homepage-articles/edit.js
Right now, if you set the Homepage Posts block to display as grid, you have an option to pick the number of columns you want to show. The maximum number of columns is six, or, if you have fewer posts than that (either based on the number of posts you've chosen to show, or the number of posts your query is returning), the maximum number of columns will be that. 
By default, the number of posts loaded is 3, so that's also your maximum number of columns.
This has been reported as confusing, and it also 'breaks' the ability to type in a column count value, since it gets "corrected" when you move focus away from the column field, and reset to the maximum.
This PR removes the restriction, so the maximum is always 6. Down the road, we should also improve the appearance of the columns when your …
=> Homepage Posts: Remove dynamic columns limit

src/components/autocomplete-tokenfield.js, src/components/autocomplete-tokenfield.scss, src/components/query-controls.js
This PR improves two aspects of the Specific Posts UI:
- The feature toggle was labelled "Choose specific stories," not "Posts."
- Feedback indicated the post selection autocomplete interface was not immediately apparent, and help text would be useful. 
Closes https://github.com/Automattic/newspack-blocks/issues/310.
1. Verify the field is labelled `Choose Specific Posts`
2. Toggle the field on and verify helper text below the input.
3. Verify Authors/Categories/Tags inputs no longer have help text beneath them.
=> Homepage Posts: Improve Specific Posts UI

src/blocks/donate/edit.js, src/blocks/donate/index.js, src/blocks/donate/view.php
Normally the Donate block derives tiering and pricing data from the Newspack Plugin's Reader Revenue Wizard. In some circumstances publishers need to control these settings on a per-block basis. This PR adds a "Configure Manually" toggle to the Donate block's Inspector Controls. When switched on, the tiering and pricing of the block can be set manually. 
Closes https://github.com/Automattic/newspack-blocks/issues/308
1. In Newspack Plugin be sure the Reader Revenue Wizard is fully configured (even in Manual mode the block gets the currency symbol and submission URL from the Wizard).
2. Add a Donate block to a page or post, then in the sidebar switch on "Configure Manually."
3. WIth Tiered Mode off verify there is one price field shown in the sidebar, and changing it updates the block. The …
=> Donate Block: Manual Mode

.stylelintrc, package-lock.json, package.json, src/block-styles/core/columns/editor.scss, src/block-styles/core/columns/view.scss, src/block-styles/core/group/editor.scss, src/blocks/carousel/editor.scss, src/blocks/homepage-articles/view.scss, src/shared/sass/_mixins.scss, src/shared/sass/_variables.scss
#327 fixes linting errors for SCSS files. This PR: 
- configures `prettier` to operate without conflicts with `stylelint`
- formats the SCSS files so they adhere to our prettier configuration
Note that this is a draft, as it should be merged after #327 is merged.
1. run `npm run lint:scss` - there should be no errors
2. run `npm run format:scss` - there should be no diff (code is already formatted in this PR)
=> Code style (SCSS): prettier and stylelint configuration

.circleci/config.yml
Adds a CircleCI config. The builds will be available here: https://circleci.com/gh/Automattic/workflows/newspack-blocks
For now, it will just run linting, but in the future also tests and maybe automated releases.
=> CI: add CircleCI config

newspack-blocks.php
This PR bumps the version number of the blocks plugin to `1.0.0-alpha.22`.
1. Apply the PR.
2. Make sure the version number has been updated :)
=> Bump version number

src/blocks/homepage-articles/view.js
IE11 and other browsers don't implement `NodeList.forEach()`, so looping over `querySelectorAll()`'s return value causes errors there.
This PR attempts to fix it by using `Array.prototype.forEach` directly, as suggested in https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Example
Fixes #332.
Fixes #315.
=> Make querySelectorAll loop IE11 compatible

src/blocks/donate/edit.js, src/blocks/donate/view.php
Closes #86 
When multiple Donate blocks were present on the same page the `label` elements for the 2nd+ Donate block controlled the `radio` inputs in the first block since they all had the same ID. I've added a UID to the labels/inputs to prevent this issue.
1. Add multiple Donate blocks to a page (test with tiered and untiered Donate blocks since they each have separate rendering).
2. In the editor, you should be able to toggle the frequencies of the 2nd+ Donate block without affecting the topmost Donate block.
3. On the frontend, you should be able to toggle the frequencies of the 2nd+ Donate block without affecting the topmost Donate block.
=> Prevent label collisions when multiple Donate blocks are on the same page

.circleci/config.yml, package-lock.json, package.json
Fix after #333 - `fsevents` is a MacOS only package, so it won't run on Linux machines. 
Also:
1. changes `npm install` to `npm ci` for efficiency:
> It can be significantly faster than a regular npm install by skipping certain user-oriented features.
https://docs.npmjs.com/cli/ci
2. run in workflow, so that linting job is reported separately (and it will be possible to report testing and then release in that manner):
Note that the linting [will fail](https://app.circleci.com/jobs/github/Automattic/newspack-blocks/40) due to linting errors, but these will be fixed in a separate PR
=> CI: fix build on CircleCI

newspack-blocks.php
This PR bumps the version for the release. We should also be bumping the `NEWSPACK_BLOCKS__VERSION` constant too.
=> Bump version for release

src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/view.js
Fixes IE11 incompatibility with `URL` api.
UI will now always add all IDs of displayed posts, the endpoint will always remove it from its next url.
See https://github.com/Automattic/newspack-blocks/pull/338#issuecomment-576428130
1. Create a block instance with more button.
2. In the front-end, click the more button a few times, make sure the request URL looks sane and posts load as expected.
3. Make sure IE 11 works as expected.
=> HA: Dumb down handling of exclude_ids

src/blocks/homepage-articles/view.scss
This PR tightens up the padding a bit on the Homepage Posts, when using the 'image behind' option. I noticed when recreating one of the layouts on a staging site that, when this block is nested in a column block, it can get really squishy on tablet-ish sized screens. 
This PR doesn't fully resolve the issue -- there's just not enough space. I think it would make sense to look at adding a 'little-to-no gutter' style for the Columns block as well, after #325 lands. 
Closes #320 (not sure where I got the number used in the branch name!)
1. Copy-paste [this test content](https://cloudup.com/c3uK2-EEtdI) into the editor.
2. Make sure most of the posts displayed have a featured image, and a couple also have a caption for that featured image.
3. View on the front end at desktop, tablet-ish and …
=> Homepage Posts: Reduce padding for 'image behind' style

src/blocks/donate/edit.js, src/blocks/donate/index.js, src/blocks/donate/view.php
This PR adds a Campaign field to the Donate block. The field doesn't really do much on its own; it just renders a hidden `campaign` input on the Donate block's form. Other integrations (like NRH) can use this information when processing a submission from the Donate block to sync with Salesforce, and in the future this will be used as part of Newspack to connect with CRMs.
1. Add a Campaign to a Donate block:
2. On the frontend, verify a hidden `campaign` input is rendered as part of the form:
=> Add Campaign field to Donate block

src/blocks/carousel/edit.js, src/blocks/carousel/editor.scss, src/blocks/donate/edit.js, src/blocks/donate/editor.scss, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/editor.scss, src/shared/sass/_placeholder.scss
By adding a new shared SASS file we can control where we want to display the Placeholder content via a `component-placeholder__align-center` class.
This is particularly useful for the combo Placeholder + Spinner which looks odd when left-aligned (since G. 7.2.0)
See #329.
1. Load a post/page with the Home Articles, Carousel and Donation block.
2. Check the loading state. Spinner should be left aligned.
3. Switch to this branch.
4. Refresh your post/page.
5. Spinner should be centred.
=> Add a Placeholder align option and align center when loading

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/editor.scss
Removes background color from Load More button container in the editor.
Closes https://github.com/Automattic/newspack-blocks/issues/367 .
1. Switch to `master`.
2. Add Group block to a post.
3. Set Group block background color.
4. Add Homepage Posts block to the Group block.
5. Toggle Load More button on.
6. Observe background color behind the button.
7. Branch switch to `fix/load-more-button-bg-in-group-block`.
8. Refresh editor page.
9. Observe background is removed.
=> Remove Background Color Behind Load More Button in Editor

amp/homepage-articles/view.js
The AMP implementation of the Load More button wraps dynamically loaded articles in an `amp-layout` element. This works fine for list view, but in grid view the additional layer of hierarchy breaks the flexbox layout. This PR resolves the problem by removing the wrapper and inserting the `article` tags directly into the container.
Closes https://github.com/Automattic/newspack-blocks/issues/366 .
1. Install/Activate the AMP plugin, switch to Transitional mode.
2. With this branch checked out, add a Homepage Posts block to a post or page.
3. Click the Grid View icon.
4. Preview the post/page. 
5. In non-AMP, click Load More, observe the results.
6. Switch to AMP, click Load More, verify the results look the same.
7. Try the same with a variety of other block settings, verify the results are …
=> Fix AMP Load More Grid View

composer.json, package.json
`xwd-dev-lib` lints files in a tmp directory - with changed files only - which makes [`import/no-unresolved`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md) rule fail at times, as not all files are present. 
This PR relieves `xwp-dev-lib` of linting JS files and makes it so that JS is linted with [`lint-staged`](https://github.com/okonet/lint-staged) tool.
Git hooks need to be updated after these changes: `./vendor/bin/cghooks update`
1. Update git hooks - `./vendor/bin/cghooks update`
2. Change a JS file so that it's broken (would not pass linting)
3. Try to commit the change. See that it fails and error message from Eslint is output.
=> Linting: use lint-staged for JS pre-commit linting

src/blocks/homepage-articles/store.js
Fix up store return - it is causing lint errors when trying to deploy FSE on dotcom.
Too many things are interwined, but regardless, the fix is to just return the thing in the case statement instead of defining a new variable and then return.
For reference, here's the lint rule being triggered on commit: 
https://eslint.org/docs/rules/no-case-declarations
=> Remove lexical declaration inside case

src/blocks/homepage-articles/editor.scss
Ensure that when using the blog posts block, the spacing between the category and the post title in the editor is equal to the spacing on the frontend.
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
Closes #393.
1. Go to http://calypso.localhost:3000/pages/YOUR-TEST-SITE
1. Create new page
1. Add blog posts blog and select Show Category in Post Meta Settings
1. Save page and compare editor view and frontend view
=> Blog Posts Block: Synch editor view and frontend view

src/blocks/carousel/view.scss, src/blocks/homepage-articles/editor.scss
Tiny PR to clean the focus and select styles on the different buttons
1. Add a carousel block to a page/post
2. Notice the dotted navigation and left/right arrows when focused/selected
4. Refresh your page/post with the carousel and notice the differences
=> feat: update default carousel style for focused elements

src/blocks/homepage-articles/view.js
Several recent issues have noted that posts displayed by clicking Load More do not adhere to the same query parameters as defined in the block. This is due to a double-encoding problem. The 'next' URL is encoded by PHP [here](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/view.php#L129), then again by Javascript [here](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/view.js#L58). This meant that parameters with special characters would be end up double-encoded. Any of the array parameters, like `categories[]` would end up mangled and therefore would be ignored by the endpoint rendering the Load More response. The Javascript encoding is present only in the non-AMP version, so this issue did not affect AMP pages. …
=> Fix Double-Encoded Load More URLs

src/blocks/homepage-articles/view.scss
✔️Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
✔️Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
✔️Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
This fixes what I'm pretty sure the code attempts to do, but gets overrided with on WordPress.com themes, in regards to displaying the date.
Closes #405
1. Activate a free WordPress.com theme
2. Add the block and select showing the date
3. Get the `updated` class to be applied
4. Verify the date …
=> Blog Posts Block: Prevent Date Being Hidden

newspack-blocks-patterns.php
This tiny PR makes sure that the Subscribe patterns are always being displayed and not just when Mailchimp is active. Because... how would you active Mailchimp if it's not available 🙄
1. On a site with Mailchimp not active, in a page, open the Newspack Patterns, do you see the Subscribe patterns? (you shouldn't)
2. Switch to this branch.
3. Try again (this time you should see the patterns)
=> Display subscribe pattern when Mailchimp is inactive

package.json
Remove redundant build
`npm run build` was ran two times during the release, this was not needed.
=> CI: tweak build script

src/patterns/index.js, src/patterns/style.scss, src/shared/js/newspack-icon.js
Gutenberg 7.7 introduces a pattern library that lives in the pinned sidebar. The icon is very similar to the one we use for the Newspack Patterns.
This PR replaces the Material icon with our logo.
1. Make sure you have Gutenberg 7.7+ installed.
2. Edit a page/post
3. Notice the 2 similar looking icons in the top right hand corner of the editor
4. Switch to this branch and refresh the page/post.
5. Is it any better? Is is less confusing?
=> Update the pattern's icon with Newspack logo

src/blocks/homepage-articles/editor.js, src/blocks/homepage-articles/store.js
The query store maintains the block registration name in a hardcoded constant (https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/store.js#L18). This creates a problem for the Full-Site Editing plugin, which registers the block under a different name (`a8c/blog-posts`) . This branch allows the block name to be passed as a parameter when the store is registered.
There should be no visible changes in this branch. Verify that editor deduplication continues to work as before.
=> Pass Block Name To Query Store

src/blocks/homepage-articles/view.php
It looks like changes in #372 -- to make sure authors archive links worked when using the Co-Authors Plus plugin -- is not loved by WP.com. This PR reworks that approach a bit, so we're adding passing `$author->user_nicename` to `get_author_posts_url()` when the plugin is enabled, and only passing `$author->ID` otherwise.
Note: A WP.com sandbox will be needed to test this fully.
Closes #401.
1. Follow the steps outlined in #372 to confirm that this functionality still works as expected on self-hosted sites.
2. On a WP.com sandbox, add the Blog Posts block, and try clicking on the Author link. Note that it's using the user nice name, not the actual URL.
3. In the sandbox's plugins directory, copy-paste the same changes into the full-site-editing-plugin/blog-posts-block/newspack-homepage-art …
=> Homepage Posts: fix broken author URL on WP.com

src/patterns/index.js, src/patterns/style.scss
This PR tweaks the Newspack Patterns Sidebar so it looks similar to the Gutenberg Patterns Sidebar with 1-column items instead of 2.
Also 2 columns were returning visual issues on Safari 10.
2. Go to a page.
3. Open the Newspack Patterns. Open the Gutenberg Patterns. Do they kind of look similar?
=> Fix pattern sidebar to match Gutenberg patterns sidebar

src/blocks/carousel/editor.scss, src/blocks/carousel/view.scss
Since AMP 1.5.1 (or 1.5, I didn't check...) AMP removed a few css properties from AMP Carousel, including the left/right position of the prev/next buttons.
This PR adds some of these properties back. I also used em instead of px for placement to match the `.entry-wrapper` paddings.
I also restyled the bullet navigation to match the style in #382 
1. Downgrade AMP to 1.4.4
2. Add a Carousel block to a page
3. Notice the prev/next arrows -- there is a 16px gap
4. Upgrade AMP to latest version (currently 1.5.1)
5. Notice the gap -- it should be gone (error!)
6. Switch to this PR
7. Notice the gap -- it should be back (and has increased, from 16px to 1.5em)
=> Update carousel style since AMP 1.5.1

src/patterns/style.scss
This PR removes the pattern's background color introduced with Gutenberg 7.9
1. Make sure you have the latest version of Gutenberg
2. In a page/post try to add a new Pattern -- notice the grey background behind the list of patterns
4. Refresh -- grey background should be gone
=> Fix patterns sidebar background color since Gutenberg 7.9

src/blocks/carousel/create-swiper.js
See https://github.com/nolimits4web/swiper/issues/2745#issuecomment-412607428
Switching to this way of importing the stylesheet makes it independent from the folder structure this component is in. It's currently what's preventing this block from being added to Dotcom's FSE.
See https://github.com/Automattic/wp-calypso/pull/41423.
1. Build the blocks
2. Make sure styles are still loaded for the block.
=> Carousel: Use absolute path for style import

src/blocks/carousel/view.php
* Makes the block name filterable, similar to Homepage Articles.
This allows third party consumers to replace the name in different contexts.
See #248.
1. Create a post with the Carousel block.
2. Preview the post and make sure the block still shows up.
=> Carousel: Make block name filterable

src/blocks/carousel/edit.js
Adds the Editor-provided default class explicitly so styles still work when third party consumers replace the block name with their own.
1. Insert the block in the Editor and make sure the slider styles still work.
=> Carousel: Add default class

src/blocks/carousel/view.php
#239 # All Submissions:
It applies a filter to the carousel block in order to be able to pass custom arguments to it.
It shouldn't change the current behavior of the carousel block. Simply confirm that it's still working as expected after applying these changes. If you'd like to go forward, add a function to the hook and test it runs:
```php
function block_arguments( $name, $args ) {
// $name contains the block name
// $args -> the block arguments :smart:
};
add_filter( 'newspack_blocks_block_args',  'block_arguments', 10, 2 );
```
=> improvement: make the carousel block args filterable

class-newspack-blocks-api.php, src/blocks/carousel/edit.js
Not sure how smart it is to unilaterally open the posts endpoint up to meta queries. I suppose we could pass a custom parameter and "hard-code" the post thumbnail meta query based on that?
Regardless, with this change the carousel in the Editor will now contain the same posts as it does in the front-end. Currently it just displays X number of most recent posts and hopes they have featured images assigned to them.
1. Add the Carousel block in the editor and play with the post count attribute.
2. Make sure the carousel contains as many posts with thumbnails as you selected in the attribute
3. Double-check that posts on the Editor side are the same as in the front-end
=> Carousel: Only query posts with thumbnails

package-lock.json, package.json, src/patterns/index.js, src/patterns/style.scss
Gutenberg 8.0 breaks the Newspack Patterns thumbnails because the class used was removed. So.. instead of relying on Gutenberg styles to display the patterns – since it's constantly evolving – this PR adds its own set of styles for the pattern thumbnails.
1. Enable Gutenberg < 8.0, check the patterns
2. Update to Gutenberg 8.0, check the patterns -- the styles should be missing
3. Switch to this branch and check the patterns -- we now have our own styles
=> Fix patterns preview thumbnails

src/block-styles/core/columns/editor.scss
This PR removes the `.wp-block` class from the selectors for the Columns block styles in the editor. At some point, this container was removed from from the block markup, but! It does exist on the block itself. So when the block is nested in another -- like the group block, like you'd see with the Newspack block patterns -- the preview displays as expected.
Closes #434.
1. Add a column block to the editor with 2-3 columns.
2. In each column, add a paragraph block that labels the order - for example, Column 1, Column 2:
3. Select the 'first column to second' block style.
4. Note the preview isn't updated:
5. Apply the PR and run `npm run build`
6. Refresh the editor and confirm that the block style is now previewing correctly:
=> Columns styles: Update editor selector for reordering columns

class-newspack-blocks-api.php, package-lock.json, package.json, src/blocks/carousel/edit.js, src/blocks/carousel/view.js, src/blocks/carousel/view.php, src/blocks/carousel/view.scss
Originally the Carousel block took an experimental approach using an AMP component in AMP and non-AMP contexts, effectively treating AMP as a general-use components library. This is an unsupported use case, and although it has worked so far, there could be unexpected side effects. The block is being adapted for use on WordPress.com, which multiplies these risks. This PR reworks the front end rendering so that `amp-component` is used in AMP requests and [Swiper](https://swiperjs.com/) is used in non-AMP. 
Closes https://github.com/Automattic/newspack-blocks/issues/449
Closes https://github.com/Automattic/newspack-blocks/issues/442
_Note: If Newspack Pop-ups is active, deactivate it. Pop-ups also enqueues AMP scripts in non-AMP requests so it confuses testing and verification of this …
=> Use Swiper In Non-AMP Contexts

class-newspack-blocks-api.php, src/blocks/carousel/edit.js, src/blocks/homepage-articles/edit.js, src/shared/js/utils.js
The byline and avatar display logic in Homepage Posts has changed since Carousel was first introduced. This brings the two in sync, extracting the handling of both to a shared utilities file.
Closes https://github.com/Automattic/newspack-blocks/issues/445
1. Add Carousel block to the editor, verify author, avatar and date display.
2. Publish the post and verify the display is the same. 
3. Add one or more Homepage Posts blocks, verify the byline/date/avatar display is unchanged.
=> fix: byline, avatar and date in carousel block

src/blocks/carousel/view.php
Removes post updated time element to accomodate themes that doon't fully support microformats.
Closes #452.
1. Have two or more posts with featured images
2. Update one of the posts with new content
3. Add the articles carousel to a page
4. Publish the page 
5. Visit the page and see that the post in the carousel doesn't show a repeated date
=> Carousel: Remove post modified time

src/blocks/carousel/view.scss
Use `object-fit: cover` to keep the correct ratio.
_Note: This won't work for anyone using IE11._
Closes #460
1. Replicate #460
2. Switch to this branch
3. Refresh your carousel
=> fix: carousel image being distorted

src/blocks/carousel/view.scss, src/blocks/homepage-articles/view.scss
This PR adds styles to make sure Jetpack's Content Options won't hide the category, author byline or date in the Homepage Posts block and Article Carousel block, since each have their own controls to toggle those settings.
I'd originally fixed this for the Homepage Posts block in the Newspack Theme, but it makes more sense to tackle it in the block, since it could happen with other themes.
Should be tested with https://github.com/Automattic/newspack-theme/pull/919 (a PR removing the original fix from the Newspack theme), to make sure the block fix isn't coming from there. 
Closes #465.
1. Add a Homepage Posts block and Article Carousel to a page. For both, enable everything (author, date, category).
2. Navigate to Customizer > Content Options, and uncheck all the options under Post …
=> Homepage Posts, Article Carousel: Make sure content options don't affect blocks

src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php
This PR makes sure the 'image shape' classes are actually being output on the front-end of the block (right now they only work in the editor). It also simplifies the classes a bit, from image-shape[shapename] to just is-[shapename], to shorten them, and make them match other class formats.
These classes can be used to change the image aspect ratio a bit with CSS only -- so if someone wanted their landscape images to be 16:9 rather than 4:3 on the front end, they could use CSS like the example in #472 to adjust them.
Closes #472.
2. Add four homepage posts blocks to the editor; one with the default image shape, one with portrait, once with square and one with no crop.
3. Inspect each and confirm that a class for each shape is output on the main …
=> Homepage Posts: Add image shape classes to the front end

package-lock.json, package.json, src/blocks/carousel/create-swiper.js, src/blocks/carousel/edit.js, src/blocks/carousel/view.js, src/blocks/carousel/view.php, src/blocks/carousel/view.scss, src/blocks/homepage-articles/view.scss, src/shared/sass/_mixins.scss
Improves Articles Carousel accessibility through keyboard focus management and screen reader interactions.
announcements) that prevents the slide content from being announced.
Closes https://github.com/Automattic/newspack-blocks/issues/436
**Editor with VoiceOver on Safari**
**Frontend with VoiceOver on Safari**
1. Add an Articles Carousel to a post
2. Tab through the slider
3. It should not switch slides when tabbing
4. All Arrows and Navigation dots should be able to be used with the keyboard
5. Check that the current slide's title and author can be tabbed to
6. Pause/Play buttons should work and not lose focus when activating the button with a keyboard
7. Test the above on Editor side as well (you can move focus into the Editor Carousel by clicking initially into the carousel, then …
=> Articles Carousel: Improve accessibility

src/blocks/carousel/edit.js
Solves issue described in https://github.com/Automattic/newspack-blocks/pull/469#pullrequestreview-411362555.
Swiper wasn't initializing for additional blocks because `componentDidUpdate` (where we initialize Swiper) is not called for them. The reason that only the first block is calling `componentDidUpdate` is that the `latestPosts` prop is empty on mount and changes once the request is done, triggering the update. That is not the case for additional blocks because the `latestPosts` data is already there. Initializing `Swiper` on `componentDidMount` (if posts are available) fixes the issue.
=> Articles Carousel: Fix Swiper init for additional blocks

src/blocks/carousel/edit.js
It is possible to break the block's UI by clearing the `Number of Items` control, as described in https://github.com/Automattic/newspack-blocks/issues/477. This branch fixes the issue by ensuring the value is 1 or greater.
If this approach is successful, I'll make the same fix for Homepage Posts.
Closes https://github.com/Automattic/newspack-blocks/issues/477
1. On `master`, observe the scenario described in the issue.
2. Switch to this branch and attempt to repeat the scenario.
3. Verify it is impossible to set the field to a value less than 1.
=> fix: disallow 0 as post to show value

src/blocks/homepage-articles/edit.js
When you have a category with an ampersand, it appears encoded in the editor (`&amp;` rather than `&`). This PR wraps the category output in `decodeEntities()` to fix.
1. Add a category with an ampersand, and apply it to a post; publish.
2. Add the Homepage Posts block to a page, and make sure your new post is displaying in it.
3. Note the ampersand in the editor:
4. Apply the PR and run `npm run build`.
5. Confirm that the ampersand is now displaying as expected:
=> Homepage Posts Block: decode entities in categories when shown

src/block-styles/core/group/editor.scss, src/block-styles/core/group/index.js, src/block-styles/core/group/view.scss, src/block-styles/view.js
This PR adds a border style to the group block, a request that's come up a couple times.
It will need to be paired with border-related styles in the theme as well, to make sure some of the child themes (specifically, Nelson, Katharine and Joseph) are using their border styles on this block, too.
Closes #195.
2. In the editor, add a group block, and confirm there is a 'borders' style. Apply it to your block:
3. View in the editor, and confirm a border has been added, as well as padding (it's equal to how much padding is added when you add a background colour to that block):
4. View on the front-end and confirm the border has been added:
=> Group Block style: Add border option to group block

src/blocks/carousel/index.js
Rename "Articles Carousel" block to "Post Carousel". Discussion in `pbAPfg-no-p2#comment-1012`
1. Verify name change in the block picker.
2. Verify name and description change in the Post Carousel block's sidebar.
=> refactor: rename articles carousel block->post carousel

src/blocks/carousel/view.php, src/blocks/homepage-articles/view.php
Currently the carousel and homepage-arcticle blocks will load their
CSS and JS resources on every page view, as soon as the Full Site Editing
plugin is activated.  This change is part of a two part process to have
these two blocks only load these resources on page views where the blocks
are being used.
The second part of this change will to the Full Site Editing plugin in the
newspack_blocks_block_args() function.
Closes # .
1.
2.
3.
=> Enqueue styles and scripts at render time

src/blocks/homepage-articles/view.scss
Some of the spacing styles on the Homepage Posts block are too specific when in grid view, overriding styles set in the Varia theme collection. The issue is only noticeable when using the "Featured Image Behind" image placement, and (I think due to the order the CSS is loaded in), can only be recreated on a WP.com sandbox.
Closes #482.
1. On a localhost site running the Newspack theme, add the homepage posts block; set it to grid view, and set the featured image behind style. If the last post in the block doesn't have a featured image, assign one. 
2. Duplicate that block, and set it to list view (for a later spacing comparison).
3. Check the margin on the last article in the list-view of the block; confirm it's 0.
4. On a WordPress.com sandbox site running one of the Varia themes (like …
=> Homepage Posts: make bottom margins less specific for easier overrides on WP.com

src/blocks/homepage-articles/edit.js
Resolves an unreported bug which causes part of "Display Settings" section to disappear.
1. On master,
2. Insert or edit a Homepage Posts block, set the "Number of items" in "Display Settings" section of sidebar settings manually to 0, or just clear the input next to slider
3. Observe the query controls disappearing, leaving only "Choose Specific Posts" control in the "Display Settings" section
3. Switch to this branch and rebuild
3. Redo step 2, observe that no part of settings UI disappears
=> Always display query controls

class-newspack-blocks.php
Ideally, creation of `$all_specific_posts_ids` array should happen once per page request (currently it happens once per HP block), but I don't know how to do that – all suggestions welcome!
Closes #498
1. On master, reproduce #498
2. Switch to this branch, observe that #498 is not reproducible
=> Fix: exclude specific posts from other blocks from query

class-newspack-blocks.php
Resolve PHP warnings due to deprecated parameters for `implode()`.
Closes https://github.com/Automattic/newspack-blocks/issues/513
Should be no visible changes. Test Homepage Block normlly.
=> fix: correct order of arguments in implodes

src/blocks/homepage-articles/templates/articles-loop.php
Full description and testing instructions: https://github.com/Automattic/newspack-popups/pull/136
To distinguish the `WP_Query` in Homepage Posts from the main loop, this branch holds the `wp_query` global in a temporary variable, then restores it after the block is rendered.
h/t @claudiulodro for the fix!
See https://github.com/Automattic/newspack-popups/pull/136
=> fix: don't use main wp_query when rendering homepage posts

class-newspack-blocks.php, src/blocks/homepage-articles/templates/articles-loop.php
The "Load more posts" button isn't always appearing on the front end of the site, even when the site is public and there are definitely more posts to load.
**Without this PR**
I think this is to do with the code that prevents a post from appearing twice on the same page. From what I can tell the block [keeps a track of which posts have already been rendered on the page](https://github.com/Automattic/newspack-blocks/blob/31181a5536aef03779cf789d2dcd4d9de05b4371/src/blocks/homepage-articles/templates/articles-loop.php#L22) so that it doesn't render them again. I think the idea is to [over-fetch posts](https://github.com/Automattic/newspack-blocks/blob/31181a5536aef03779cf789d2dcd4d9de05b4371/class-newspack-blocks.php#L364)  when rendering the following blocks to make up for the fact that …
=> fix(homepage-posts): exclude posts already on the page from query

src/blocks/homepage-articles/templates/articles-loop.php
This is a better approach to dealing with the issue in which Newspack Campaigns injected campaigns content into excerpts in the Homepage Posts block. The original solution tinkered with the `$wp_query` global which had unexpected negative side effects, and is generally a risky practice. The new approach fires a custom action before and after the block renders. These hooks allow Newspack Campaigns to remove and re-add the `the_content` filter, ensuring that Campaign content isn't injected into the block.
h/t @adamsilverstein for the approach.
Closes https://github.com/Automattic/newspack-blocks/issues/525
1. Switch Newspack Campaigns to `master`.
2. Create a Campaign, Sitewide Default, Placement: Center, Trigger: Timer, Frequency: Test Mode. Fill it with recognizable content (e.g. one of …
=> refactor: replace query global manipulation with hooks

class-newspack-blocks.php, src/blocks/homepage-articles/templates/articles-loop.php
This PR fully adopts the approach of https://github.com/Automattic/newspack-blocks/pull/515, using `post__not_in` queries rather than the original approach of "overshooting" and removing duplicates in PHP. This PR removes the experimental flag and applies the exclusion approach everywhere. 
Using the experimental flag some testing was done on production sites comparing the performance of the old and new approaches. Results were similar but the new approach looks a bit faster, and since it resolves the Load More issue it should be adopted.
cc: @p-jackson 
1. Create a complex homepage. Verify the results seen in the editor match the frontend, with no duplicate posts shown. 
2. Go through testing instructions in https://github.com/Automattic/newspack-blocks/pull/515 and verify the Load More …
=> refactor: remove experimental flag for frontend exclusion queries

src/blocks/donate/edit.js
This just brings donations wizard links in Donate block editing code up to date. 
1. On master branch
1. Insert a Donate block, in the sidebar, click the "Edit donation settings" link
2. Observe the link leading to an error page
1. Switch to this branch and rebuild 
1. Click the link again, observe it leads to the Reader Revenue wizard, Donations section
=> Fix donations wizard link

class-newspack-blocks-api.php, class-newspack-blocks.php
This is a companion PR to https://github.com/Automattic/newspack-theme/pull/974, but that PR isn't required for this one.
This PR fixes an issue I noticed on BDN. On some historic posts, `get_coauthors()` would return an empty array. I haven't figured out the exact cause why, but it's likely old metadata with the same key or something like that.
This PR adds a fall back to display the regular post author if `get_coauthors()` doesn't return anything.
1. Add the following somewhere: `add_filter( 'get_coauthors', '__return_empty_array' );`
2. Look at homepage block with author display enabled on the frontend and in the editor. Observe author is "By {nothing}":
3. Apply this patch. Look again. Observe author is correct:
=> Fallback to author if coauthors fails

src/blocks/donate/edit.js, src/blocks/donate/index.js, src/blocks/donate/view.php
Makes the text of the Donate button editable. 
Closes https://github.com/Automattic/newspack-blocks/issues/361
1. Add Donate block to a post.
2. Edit the button text in place.
3. Publish, verify the text change is visible in frontend.
4. Try with manual settings and Newspack-set defaults, verify all works as expected.
=> feat: editable donate button text

class-newspack-blocks.php, src/blocks/homepage-articles/store.js, src/blocks/homepage-articles/view.js, src/blocks/homepage-articles/view.php
Exclude the current post ID in Homepage Posts block. This change allows placement of the block in content without the obvious mistake of displaying the current post. 
Note: There are some unrelated issues that will occur when the Homepage Posts block is used in a Campaign. These will be addressed in a future PR.
Closes https://github.com/Automattic/newspack-blocks/issues/359
1. On `master`, create a new Post, add Homepage Posts block. Publish the post then refresh the editor page. Observe the current page is displayed in the block.
2. View the published post. Observe the current page is shown in the block in frontend as well.
3. Switch to this branch. Observe the current page is no longer visible in editor or frontend.
4. Verify "Show More Button" works properly  and doesn't show the …
=> feat: exclude current post in homepage posts block

src/blocks/donate/view.php
Resolves a few PHP and PHPCS warnings in the Donate block. There should be no change to the block's functionality. 
1. On `master`, add Donate block to post, toggle to "configure manually." Publish and view the post.
2. In PHP error log, observe many notices like this: `PHP Notice:  Undefined index: items in /srv/www/wordpress-simple/public_html/wp-includes/rest-api.php on line 1251`
3. Switch to this branch and refresh the page. 
4. Observe the notices are gone.
=> fix: php warnings, phpcs warnings in donate block

src/blocks/homepage-articles/view.scss
This PR makes the margin styles for the load more button a bit more specific, making sure they're a direct child of the main block wrapper, so they don't accidentally get picked up by sharing buttons on atomic sites. The LinkedIn button specifically is picking it up, and the share buttons are added inside of each `article`. 
Closes #508.
1. Set up a homepage posts block and turn on the load more button.
2. Apply the PR and run `npm run build`.
3. View on the front-end and confirm that the 1em top margin is still being applied:
=> fix: make load more button styles more specific

src/blocks/carousel/view.php, src/blocks/donate/view.php, src/blocks/homepage-articles/view.php, src/blocks/video-playlist/view.php
When running Gutenberg 8.6.0 server-rendered blocks that don't have a `supports` parameter defined in `register_block_type` will throw PHP Notices:
```
Notice: Undefined property: WP_Block_Type::$supports in /srv/users/userf199047f/apps/userf199047f/public/wp-content/plugins/gutenberg/lib/blocks.php on line 241
```
This branch adds an empty `supports` parameter for all four blocks, temporarily silencing the notices.
1. Install Gutenberg 8.6.0.
2. On `master` branch, add each of the blocks to a post (Homepage Articles, Donate, Video Playlist, Carousel). Publish and view. Observe a PHP Notice for each block.
3. Switch to this branch, observe the Notices are gone.
=> fix: php notices in gutenberg 8.6.0

src/blocks/donate/edit.js, src/blocks/donate/view.php, src/blocks/donate/view.scss
This PR doesn't change anything visually about the Donate Block, but it reduces the CSS by a bit over 2kb for the tiered version when using AMP tree shaking:
Standard - before: 6,632b
Tree shaken - before: 6,025b
Standard - after: 4,678b (-1,954b)
Tree shaken - after: 3,998b (-2,027b -- or about 2.7% of the available total)
This block is often used on the homepage, and the homepage typically has the most CSS, so this seemed like a quick win!
2. Apply custom colours and fonts on the site (just to verify that they are applied).
3. Set up the Donate Block on a page, with tiers.
4. Test in the editor and on the front end at both desktop and mobile sizes; confirm that it looks correct, and selecting different tabs/options still works:
5. Switch the …
=> refactor: simplify donate block styles

class-newspack-blocks-api.php, class-newspack-blocks.php, src/components/query-controls.js
We've received feedback from Bangor Daily News that specific posts lookups in the Homepage Posts block can take 45-60 seconds, making homepage management a painfully slow operation. This seems to be because we're using the `/wp/v2/search` endpoint which does a full-text search. The site in question is very large (over 400k posts), so this operation runs slow. This branch introduces a new endpoint that queries `post_title` only, which should be orders of magnitude faster. Although I suspect most use of the specific posts field does use the title, this change is a feature removal, so for the moment it's behind a new `wp-config` flag (`NEWSPACK_BLOCKS_EXPERIMENTAL`). If this fix works well and we determine the full text search isn't essential, we can remove the flag and apply it universally. …
=> feat: experimental title-only specific posts lookup endpoint

src/blocks/carousel/view.scss
The Post Carousel block's font colours are largely set to `inherit`; in a couple WP.com themes, the carousel is inheriting from the theme's more specific styles, rather than the block, making the colours too dark. This PR switches the block to use `#fff` to fix. It's possible it won't fix all themes, but we can adjust further as individual cases crop up!
Note: this needs a WP.com sandbox to test.
Closes #548
1. On your WP.com sandbox, switch to a theme where this issue happens, like Stratford or Independent Publisher 2. 
2. Add a Post Carousel block to a page and publish.
3. Note the issue on the front-end:
4. Apply the PR and run `npm run build`
5. Sync your local dev site with your WP.com sandbox using the process for the FSE plugin in Calypso (just ping me if you need steps!)
6. …
=> fix: make sure colors aren't overridden in non-NP themes

.circleci/config.yml, .distignore, .gitignore, composer.json, composer.lock, package.json
1. Change release ZIP file structure, so that it matches the structure used by WPORG plugins.
2. `semantic-release` config update which will enable [prereleases](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pre-release-branches). 
1. Run `npm run release:archive`
2. Install the plugin on a fresh site, confirm that it works as before
=> Build: change release zip structure

class-newspack-blocks-api.php
This PR fixes an issue I noticed while beta testing WP 5.5. Starting in WP 5.5, REST endpoints without a permissions callback will throw an error in order to prevent people inadvertently making their endpoints public. There were a couple (safe) endpoints in Newspack Blocks with this issue, so I've added permissions callbacks. In theory, the endpoints would be fine as public endpoints, but there isn't really a reason to expose them outside the post editor.
1. Before applying this patch, install the latest WP 5.5 release candidate and add `define( 'NEWSPACK_BLOCKS_EXPERIMENTAL', true );` somewhere.
2. Observe notices shown at the top of every admin screen:
3. Apply this patch. Observe notice disappears. Try the specific post search with the Homepage Posts block and try inserting a YouTube …
=> Add permission_callback to all REST endpoints for wp 5.5

src/blocks/homepage-articles/view.php
Sometimes it makes sense to include a homepage posts block in a post, for example to show a more targeted related post element. This can cause issues with RSS feeds through as the markup for a homepage posts block can confuse parsers and services that ingest feeds for syndication purposes.
The re-circulation benefits of the block being in a post aren't going to carry through to a feed and the styling will not be present so it's best to remove them from the feed entirely, as this change does.
1. Add a new post with a homepage posts block in the content
2. View the main RSS feed and observe the block markup is added
3. Apply the patch
4. Reload the RSS feed and observe the markup is gone
=> Don't render homepage posts blocks in feeds

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/carousel/edit.js, src/blocks/carousel/view.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php, src/shared/js/utils.js
This PR adds some visuals elements when a post is marked as native sponsored content using the Newspack Sponsors plugin (the underwritten posts only show visual elements on single posts).
It needs to be tested in partnership with https://github.com/Automattic/newspack-theme/pull/1008 to apply the correct styles.
Closes #563
1. Install and activate the Newspack Sponsors plugin (ping myself or Derrick if unsure where to find it).
2. Switch your site to use AMP transitional so you can test both the AMP and non-AMP versions, just to make sure there's no weirdness with the scaled down logos.
3. Add at least four sponsors; make sure to include the following combinations; make sure to use at least one horizontal and one vertically-oriented logo:
* Set scope to native content, attached to a …
=> Homepage Posts, Post Carousel Blocks: Add sponsored labels

class-newspack-blocks.php
Similar to https://github.com/Automattic/newspack-theme/pull/1032, this PR moves the check for sponsors so it doesn't throw an error when the Newspack Sponsors plugin is not installed.
1. Start with a test site with the Newspack Sponsors plugin disabled, and set up some Homepage Posts and Post Carousel Blocks. Make sure `wp_debug` is enabled.
2. View on front-end; note each block throws an error, `Notice: Undefined variable: sponsors in /srv/www/newspack-build/public_html/wp-content/plugins/newspack-blocks/class-newspack-blocks.php on line 530`.
3. Apply the PR and confirm the errors go away.
4. Activate the Newspack Sponsors plugin, and make the sponsor flair (flag, logos and byline) still show up for Homepage Posts and Post Carousel blocks with native sponsors, on the front-end and in …
=> Fix: moving check for sponsors to prevent notices

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/carousel/view.php, src/blocks/homepage-articles/templates/article.php
This PR updates the sponsor code for blocks to use the new function in the sponsors plugin. Like the theme approach, it still creates a new function to avoid linting errors. 
1. Start with a test site sponsored content; ideally both native and underwritten content (even though the latter shouldn't show anything in the block).
2. Set up a Homepage Posts block and a Post Carousel block with setting so they both show sponsored and non-sponsored content.
3. View in the editor and on the front-end; confirm that sponsored content shows the sponsor flag, logos and byline, even when the author and category are set not to display:
=> Update sponsor code to use new function

class-newspack-blocks.php, src/blocks/carousel/view.php, src/blocks/homepage-articles/templates/article.php, src/shared/js/utils.js
This PR helps make sure the block doesn't throw notices when a sponsor is missing a logo or a link.
2. Set up a couple native sponsors; one with everything and one missing a logo/link or both.
3. Set up a homepage posts block and a post carousel block that will display some of each.
4. Confirm the sponsors are linked only when links are available on the front end (links are not clickable in the editor), and that logos only display when available on the front-end and in the editor. 
Correct placement in post carousel:
Correct placement in homepage posts:
=> fix: prevent errors when there is no sponsor logo, link

src/blocks/homepage-articles/view.scss
When you pair sponsored content with the 'Load More' option in the Homepage Posts block, and the sponsored content is not in the first 'page' of posts, AMP will remove the styles because they're not needed on page load. 
This PR, with https://github.com/Automattic/newspack-theme/pull/1046, makes sure AMP doesn't remove these styles. They will need to be tested together.
1. Set up a test site with sponsored content, and with AMP enabled.
2. Add a Homepage posts block to the front page, set up to use the 'Load More' button. Make sure your sponsored content will appear in the block, but not on the first "page" of posts, so it doesn't display until you click "Load More" on the front-page.
3. View on the front end, and click 'Load More' until your sponsored content appears.
4. Note that the …
=> Homepage Posts: Make sure sponsored content styles survive tree shaking

class-newspack-blocks-api.php, src/blocks/homepage-articles/edit.js
Closes #507.
1. Open a private WPCOM site (or simulate it by setting `window.wpcomGutenberg = {blogPublic: '-1'}`)
2. In the editor, Homepage Posts Block settings, Display Settings panel observe a notice in place of the "Show "Load more posts" toggle
3. Open a public site's editor, observe the toggle working as before
4. Create a block with post/s sponsored by a sponsor which does not have an image, observe no warnings are logged during rendering
=> Assorted bugfixes

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php
This PR adds support for post formats to the Homepage Posts block, and some different treatment to the Aside post format (not adding a link to the title, and displaying `the_content` rather than `the_excerpt`.
This PR needs to be tested with https://github.com/Automattic/newspack-theme/pull/1074; additional information and testing steps are in that issue.
Closes # .
1.
2.
3.
=> Feat: add support for the aside post format

src/blocks/homepage-articles/view.scss
Closes #587 
For some reason, on themes that display blog posts in full width such as Radcliffe 2 and Intergalactic the `flex-basis` is not being applied.
Setting a `min-width` fixes the issue and does not affect the `flex-basis` of each column amount.
[![Screenshot](https://d.pr/i/yNi4Sq+)](https://d.pr/i/yNi4Sq)
[![Screenshot](https://d.pr/i/bRm96W+)](https://d.pr/i/bRm96W)
https://premelini.wordpress.com/testing-posts/
1. Activate Radcliffe 2 theme
2. Add Blog Posts block and set to display in at least 2 columns
3. View the blocks functioning properly. You should be able to adjust the columns and see the width change appropriately based on the preset `flex-basis`
4. Optionally, switch to the Intergalactic theme and observe the fix persists.
=> Fix for columns width not adjusting on some themes

src/blocks/carousel/index.js
Adds wide and full alignment options to the Post Carousel block
Closes: #488
1. Check out this PR locally and run built blocks in a local WP install
2. Insert a Post Carousel block and check that there are now Centre, Wide, Full alignment options in the tool bar
3. Check that each of the alignment options displays correctly in editor and front end
=> Add alignment options to post carousel block

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/homepage-articles/utils.js
Suppresses password-protected posts in the Homepage Posts and Posts Carousel blocks.
Closes https://github.com/Automattic/newspack-blocks/issues/608
1. On `master`, create and publish one or more password protected posts.
2. Add Homepage Posts and/or Posts Carousel blocks to a Page or Post, showing the most recent few posts.
3. Observe the password-protected posts are visible in the editor and front end.
4. Switch to this branch. Observe the password-protected posts are no longer visible.
=> fix: suppress password protected posts

src/blocks/carousel/index.js, src/blocks/donate/index.js, src/blocks/homepage-articles/index.js, src/blocks/video-playlist/index.js
Using Material's outlined instead of filled and add Newspack Blue colour to it.
The idea is to have our blue, just like Jetpack and WooCommerce do with respectively their green and purple.
2. Add a Newspack block, check that the icon is now using Newspack Blue
=> Update blocks icons style and colour

class-newspack-blocks-api.php, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/templates/articles-loop.php, src/blocks/homepage-articles/view.php
This is a rework of #605 with the same testing steps.
It replaces the front-end approach to truncating the excerpts with a filter, so they will still be normal excerpts that pick up other filters. 
The one remaining issue is that the_excerpt is no longer filtered in the editor, so theme's 'Continue Reading' and social links will no longer show up there. I think this is an acceptable loss, between the 'Continue Reading' styles not usually being included in the editor styles, and the social links not displaying correctly anyway.
If it comes up as an issue, we can always rework it there, too!
1. See #605.
=> Homepage Posts: Add option to change excerpt length

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/carousel/view.php, src/blocks/homepage-articles/templates/article.php
Like https://github.com/Automattic/newspack-theme/pull/1144, this attempts to minimize the number of queries executed by the sponsors plugin to at most once per post item in the Homepage Posts block.
Closes #614.
Front-end behavior shouldn't be any different. Testing instructions for sponsors are [here](https://github.com/Automattic/newspack-blocks/pull/563).
=> feat: optimize sponsor queries

class-newspack-blocks.php
When specific posts are selected to be shown, `posts_per_page` is not specified for the `WP_Query` which results in using the default value. If specific posts are selected then we should show all the selected posts, rather than cutting off some of them.
1. Change global settings for how many posts to show (Settings -> Reading -> Blog pages show at most) to 1
2. Create a page
3. Add Blog Posts block
4. Specify 2 posts
5. Publish
6. Open your published page and make sure you see 2 posts (on `master` you should only see 1 post)
Partial fix for https://github.com/Automattic/wp-calypso/issues/47086
=> Blog Posts block: Disabling paging in specific mode

src/blocks/donate/edit.js, src/blocks/donate/index.js, src/blocks/donate/view.php
Adds a control to specify the initially selected tab in the Donate block. 
Closes: https://github.com/Automattic/newspack-blocks/issues/303
1. Add Donate block to a page or post. Verify `Monthly` is the selected tab, as it has been all along.
2. In the block sidebar, change `Default Tab`. Verify the tab changes.
3. Publish the post/page, in the frontend verify the correct tab is initially selected.
4. Verify this flow works properly with `Configure manually` selected or unselected.
5. To verify this won't break existing blocks, switch to `master`, create Donate blocks, then switch to this branch and verify there is no disruption.
=> feat: control to select default tab in donate block

class-newspack-blocks.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/templates/articles-loop.php
In `Homepage Posts` block the `Max number of words in excerpt` is not respected for posts shown after page load by clicking the `Load More` button. This PR fixes this. 
Closes https://github.com/Automattic/newspack-blocks/issues/627
1. On `master` add Homepage Posts block to a page, toggle on `Show Excerpt` and set `Max number of words in excerpt` to 10, publish and view.
2. Observe the initial set of posts have 10 word excerpts. Click `Load more` button and observe the new posts have much longer excerpts.
3. Switch to this branch and repeat.
4. Observe the correct excerpt length for posts loaded asynchronously.
=> fix: respect excerpt length attribute in load more display

src/blocks/homepage-articles/store.js, src/blocks/homepage-articles/utils.js
Addresses a condition where `null` is included in post arrays in `include` or `exclude` parameters, leading to `Invalid parameter(s):` errors and block failure in the editor.
Closes https://github.com/Automattic/newspack-blocks/issues/650
1. While still on `master` branch, grab raw markup from the affected page (https://sahanjournal.com/) and paste into a post or page in test environment.
2. Observe multiple `Invalid parameter(s):` errors.
3. Switch to this branch, observe the errors are gone.
=> fix: sanitize post id arrays in includes and excludes

class-newspack-blocks-api.php
Make sure `newspack_post_format` REST API field fallbacks to `standard` value if the post format is `false`. This change is for consistency. Right now we are returning `false` which doesn't comply with the schema we use. We specified `string` as the field type. So returning a boolean doesn't make sense.
It also fixes an issue with updating posts via REST API. If you are reusing the post object returned by the GET WP REST API for a PUT request, then you are going to get an error: `newspack_post_format is not of type string`. Since we received `false` as a value for `newspack_post_format` which isn't a string so it doesn't comply with our schema.
1. `GET /wp/v2/posts/`
2. Make sure body contains `newspack_post_format` and it isn't `false`
=> fix(api): fallback to standard if post_format is false

class-newspack-blocks.php, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/templates/articles-loop.php, src/blocks/homepage-articles/view.scss
This PR adds an option to add a customize-able 'Read More' link for each story on a per-post basis.
Unfortunately, current behaviour in WP.com themes could complicate this. This is a comment from me from the [original enhancement request](https://github.com/Automattic/newspack-blocks/issues/495):
> There are a number of themes that replace the [...] at the end of automatically generated excerpts with something else by filtering excerpt_more ([example](https://github.com/Automattic/themes/blob/b6ae2c8a45c2317cef960b8c0ef94da55427ffa5/textbook/inc/template-tags.php#L181-L201)). The reason the link doesn't happen with Custom Excerpts is that the [...] is not there, since it's assumed that those would end with a full stop and not need an ellipsis.
To work around this, I added a filter that …
=> Homepage Posts block: add optional 'continue reading' link underneath excerpts

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/homepage-articles/store.js, src/components/query-controls.js
Replaces core WordPress `/wp/v2/posts` with a custom endpoint. This is done in preparation for CPT support in Homepage Posts block. Core v2 endpoints are limited to a single post type, so to enable a mixed group of CPTs it is necessary to switch to a custom endpoint. This PR is a pure refactor and should work exactly like `master`. Once this is merged, a follow-up PR will add support for CPT selection. This PR also replaces the specific posts look up with a custom API which was previously considered experimental. The custom API should be much faster and more efficient. 
1. Edit a page or post with many Homepage Posts blocks. 
2. Open Dev Tools->Network->XHR and verify all API requests go to `/wp-json/newspack-blocks/v1/posts`. On `master` the same requests should go to …
=> feat: custom endpoint for homepage posts in editor

src/components/autocomplete-tokenfield.js, src/components/query-controls.js
Closes #669.
1. Observe #669 is not reproducible
2. Create four categories named "Foo", assign different parrent to two of them
3. Insert a Homepage Posts block and use the category filter in the sidebar, insert "Foo"
4. Observe that the four are present in the suggestions: the ones with the parents have `Foo – <parent>` as label, while the duplicated parent-less one has `Foo (<id>)` as label
=> Fix duplicate category names

amp/homepage-articles/view.js, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
Fixes a bug in the Homepage Posts block's "load more" functionality. Previously, if passing the `exclude_ids` args, we still decided whether to hide the "load more" button by comparing the query's `max_num_pages` property to the page number. But `max_num_pages` will no longer reflect the total number of found posts if using `post__not_in`, so the condition was met prematurely and the "load more" button would be hidden too early.
This fix takes into account whether `exclude_ids` is being passed, and if it is, it just checks whether `max_num_pages` is more than `1` (which would indicate that there are more posts to load after this current batch) and shows the "load more" button if it is. If `exclude_ids` is not passed, we use WP's standard `paged` query param, which will result in an …
=> fix: load more button functionality

class-newspack-blocks.php
This PR adds a CSS class with the format `.type-XXXX`, for the current post's post type.
Closes #658.
1. Add a homepage post block to a page; enable both posts and pages for the block, and make sure you have at least one of each in the current query, and publish.
2. Apply the PR.
3. Inspect the articles on the front end and in the editor; confirm that the posts have the CSS class `type-post` on the `<article>` tag, and the pages have the CSS class `type-page` on the `<article>` tag.
=> Homepage Posts: Add article class for post types

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/store.js
WP.com Toolkit (formerly Full Site Editing) performs some kind of server-side transformation of REST API endpoints. This refactor will ensure that the path used for the new `/posts` endpoint comes from the server with the required transformations, rather than being hard-coded in the JS.
This is a pure refactor and shouldn't cause any changes in behavior when the plugin is run on a non-WP.com site.
Related to #404 
1. Create or edit a page and add a Homepage Posts block. 
2. Verify that the block loads posts in the editor as expected, with no change in behavior.
=> refactor: use rest_url to get the /posts route, for Toolkit

class-newspack-blocks-api.php, src/blocks/homepage-articles/utils.js
Fixes a bug reported by a Newspack publisher:
> We had this come in from the editorial team and am curious if anything changed in how the post order is displayed for editors. For context, here is the editor's note " The order of stories displayed in the three-story row when editing the home page no longer reflects the list of post order in the editing window on the rail, or on the actual page. (fortunately, the order in the editing window matches the actual page, but until now changing the order on editing window also changed the preview display on the backend.)"
To summarize: since #661, when editing a block in Specific Posts mode, the posts in the editor preview are always shown in descending order of publish date (same as in query mode), which doesn't match the front-end display. Posts …
=> fix: in specific posts mode, post order should match input order

src/blocks/carousel/view.php
This should cause the Carousel block to render authors exactly like Homepage Posts on the front end.
Closes https://github.com/Automattic/newspack-blocks/issues/456
1. Publish a series of posts with different author configurations, including a) more than one guest author, b) one guest author, c) one WordPress author, d) one guest author, one WordPress author, e) any of the above with avatars. 
2. Create two pages, one with a Posts Carousel block and one with a Homepage Posts block.
3. Compare the two in the editor, verify the author displays are identical (this should be true on `master`).
4. Compare the two on front end. On `master` the Posts Carousel block's author display is broken, on this branch it should be identical to Homepage Posts.
=> fix: carousel block renders authors like homepage articles

.circleci/config.yml, .phpcs.xml.dist, README.md, class-newspack-blocks-api.php, class-newspack-blocks.php, composer.json, newspack-blocks.php, src/blocks/donate/view.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.php, tests/bootstrap.php
This PR resolves all phpcs issues reported by `./vendor/bin/phpcs ./`, along with one extra which was reported when running the lint check on WordPress.com.
Why: we currently sync newspack blocks to WordPress.com via the editing toolkit plugin (ETK). There is a lint check in wpcom as part of the commit process. Up to now, we have that check disabled for the editing toolkit plugin, but I would like to enable it. To do so, all code in the plugin has to pass the test! I handled the ETK changes in https://github.com/Automattic/wp-calypso/pull/49692, and would also like to have newspack blocks pass that lint check.
Turns out that the local phpcs config caught even more lint things than the wpcom lint check did. As a result, I'd expect future code in this repo to be linted by about the same …
=> Resolve PHPCS issues in newspack-blocks

class-newspack-blocks-api.php, class-newspack-blocks.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/edit.js, src/components/query-controls.js
The same fix as #677, but for `specific-posts`.
Refactors the `newspack-blocks/v1/specific-posts` custom endpoint so that it is a.) retrieved from a localized value, so that it gets run through the `rest_url` filter, and b.) moved to the Homepage Posts REST controller, so that the downstream application knows to pick it up.
Also fixes #685.
This is a pure refactor and shouldn't affect behavior in a non-WP.com environment. To test, create a block in Specific Posts mode and ensure that the posts load as expected in both the editor and on the front-end.
1. Create a new Homepage Posts block and enable "specific posts" mode.
2. Confirm that the `Show "Load more posts" Button` is hidden when specific posts mode is on, and shown when it's off.
=> refactor: get specific posts REST endpoint from localized value

class-newspack-blocks.php
WooCommerce Memberships v1.21 introduced an option to change the preview excerpt length of protected posts (the option appears under WP Admin > WooCommerce > Settings > Memberships). This control also affects the Homepage Posts block, overriding the per-block setting, even when left at the default 55 value.
This PR adds a filter to retrieve the post's original excerpt, rather than the truncated excerpt generated by the WC plugin.
1. Make sure your test site is running at least v. 1.21 of the WooCommerce Memberships plugin.
2. Using WooCommerce Memberships, set it up so a category requires you to be a member to view; apply the category to a mix of recent posts.
3. Add a Homepage Posts block that has a mix of regular and member only posts; change the excerpt length to a lower number, like …
=> fix: override WooCommerce Memberships excerpt length in block

class-newspack-blocks-api.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/store.js, src/blocks/homepage-articles/utils.js
The custom excerpt length control introduced in https://github.com/Automattic/newspack-blocks/pull/607 had one drawback, which is that `the_excerpt is no longer filtered in the editor.` This has come up in https://github.com/Automattic/newspack-blocks/issues/700 as a problem for blocks with fallback content. The custom posts endpoint introduced in https://github.com/Automattic/newspack-blocks/pull/661 opens up a cleaner way to deal with this problem. In this PR, the block excerpt length and visibility attributes are passed to the endpoint and the endpoint uses excerpt filtering identical to the block's front-end rendering. This should also mean the truncated excerpt is _slightly_ more WYSIWYG since the editor and front-end are now using the exact same approach.
Closes …
=> refactor: render custom excerpt length server-side

.phpcs.xml.dist, class-newspack-blocks-api.php, class-newspack-blocks.php, composer.json, composer.lock, src/blocks/carousel/view.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
Add a PHPCS rule that ETK tracks to keep the two projects in sync.
=> chore: add phpcs unused variable rule

includes/class-newspack-blocks.php
Avoids a PHP warning thrown when editing a Newspack newsletter CPT. It's another question why the Blocks handler is running at all on a CPT that doesn't register any blocks from Newspack Blocks, but this should fix the warning wherever it might happen.
1. On `master`, create or edit a newsletter in the Newspack Newsletters plugin.
2. Observe a PHP notice in your debug.log like this:
```
[24-Mar-2021 16:05:09 UTC] PHP Notice:  Trying to access array offset on value of type bool in /newspack/app/public/wp-content/plugins/newspack-blocks/includes/class-newspack-blocks.php on line 285
```
3. Check out this branch, refresh the editor page. Confirm that the warning is no longer thrown.
=> fix: a PHP warning when editing newsletters

includes/class-newspack-blocks-api.php, src/blocks/carousel/edit.js, src/blocks/carousel/index.js, src/blocks/carousel/view.php, src/blocks/carousel/view.scss, src/blocks/homepage-articles/templates/article.php
Makes a few changes:
* Allows any post types with `newspack_blocks` support to be selected and added to a Posts Carousel, much like with the Homepage Posts block.
* Enables Specific Posts mode for the carousel, just like with Homepage Posts.
* On the front-end, if a post has an external sponsor URL meta value defined, the slide will link to this, otherwise it will link to the post's permalink. This is to accommodate sponsors, who don't have working permalinks but should have an external sponsor URL set. If it turns out that some sponsors don't have that metavalue set, we can add a block attribute to choose whether to link the slides at all.
* Adds some new block options:
- `imageFit` – Lets you specify whether the image is cropped to fill the slider or downsized to fit within it. The …
=> feat: allow different post types in carousel; plus new block options

src/blocks/carousel/view.php
#746 added a new attribute to the Carousel block, but it was not registered on the backend - this fixes that.
Ideally the block attributes should be defined in a single JSON file, so that's the next step.
1. On `master`, insert a Carousel block
2. Observe a PHP error logged about missing `'imageFit'` index
3. Switch to this branch, observe that all is well now
=> Fix: add missing Carousel block attribute

includes/class-newspack-blocks-api.php, src/blocks/carousel/view.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php
Hides the author names and published/modified dates for listings if the corresponding options in Newspack Listings are enabled.
See testing instructions in https://github.com/Automattic/newspack-listings/pull/57.
=> feat: support Newspack Listings hide entry meta options

src/blocks/author-profile/edit.js, src/blocks/author-profile/editor.scss, src/blocks/author-profile/index.js, src/blocks/author-profile/shared.scss, src/blocks/author-profile/view.php
This PR adds a new style to the block: Center.
It's slightly different from the avatar alignment option because the entire content is being centered and not just the avatar like with the alignment option.
When this new style is active, the avatar alignment option is being removed.
Also, I renamed and reorganised some of the various classnames.
2. Test both styles (Default, Center)
=> Add centered style to author profile block

src/blocks/homepage-articles/view.scss
When using the "show media behind" option in the block, these rules need to be stronger than others that might be applied to images. Using `!important` in CSS is generally considered bad practice, but I believe in this case it is the right tool for the job, since we always want this CSS to apply regardless of the context the block is loaded in. 
This will solve issues like https://github.com/Automattic/themes/issues/3341.
=> Blog Posts Block: Force image to be the right size when used behind the block

src/blocks/homepage-articles/utils.js
In WordPress 5.8, the Homepage Posts block placeholders are used pretty prominently on the Widget screen, and actually apply the different styles used by the block settings.
Currently, the excerpt and content placeholders don't pick up the font scale setting, because they're not wrapped in a paragraph tag like the actual excerpt and content markup is. 
This PR adds a paragraph tag to each.  
Closes #783 
1. Start with a test site running WordPress 5.8; navigate to WP Admin > Appearance > Widgets and add the Homepage Posts block.
2. Try increasing and decreasing the font scale on the right; note the excerpt font size doesn't change in the preview, but everything else (headline, post meta) does.
3. Apply the PR and run `npm run build`
4. Confirm that the excerpt now picks up the font scale …
=> Homepage Posts: add paragraph markup to excerpt, content placeholders

src/blocks/homepage-articles/utils.js
In WordPress 5.8, the Homepage Posts block placeholders are used pretty prominently on the Widget screen, and actually apply the different styles used by the block settings.
When the font scale is adjusted, the avatars in the block scale down for the smaller font sizes, so they fit in with the byline size better. But the placeholder avatar has a fixed 40px x 40px size, so it stays the same size. 
This PR adds a max width and height, so the avatar preview behaves more like the front-end. 
Closes #782
1. Start with a test site running the WordPress 5.8 RC (you can use the [beta testing plugin for this](https://wordpress.org/plugins/wordpress-beta-tester/)); navigate to WP Admin > Appearance > Widgets and add the Homepage Posts block.
2. Try decreasing the font scale on the right; note the …
=> Homepage Posts: add max width to avatar placeholder

src/blocks/homepage-articles/utils.js
In the utils.js file, there are placeholder images listed; the 'large' and 'uncropped' images were both referencing a size (1024x683) that didn't actually exist in the assets directory. 
This image was being used by the Post Carousel block in the preview under Appearance > Widgets and in the Customizer. 
This seems to close #788 for me, but I'm not 100% sure if that's just because that issue was a bit intermittent. Would appreciate another set of eyes on that, to make sure it has actually stopped! 
1. Start on a test site running the latest WordPress 5.8 release candidate.
2. Navigate to WP Admin > Appearance > Widgets and add a Post Carousel widget.
3. Note that the space where the featured image would be is empty; if you open the console, you should also see a bunch of 404s for the …
=> Post Carousel: correct path to placeholder image

src/blocks/carousel/view.scss
This PR makes some image sizing styles in the Post Carousel block more specific, so they're only picked up by the post thumbnail, and not the avatar.
I noticed the styles are fine when the block is out of the box, but when I try to scale down the avatar for the new widget spaces in WordPress 5.8, the avatar placement gets a bit weird (it's not perfectly square; it can overlap the byline). 
1. Add the Post Carousel block to a post or page; make sure you have posts with both one author, and more than one.
2. View the carousel on the front end with AMP enabled; note its appearance.
3. Confirm that the carousel's appearance hasn't changed (outside of the avatar moving minutely to the left -- part of the styles I'm trying to stop being applied are the …
=> Post Carousel: Tweak image width styles to not affect avatars

src/blocks/carousel/view.scss
Closes #793
1. Run Newspack blocks with the latest Jetpack
2. Comment out the temporary Newspack fix from top of `projects/plugins/jetpack/modules/carousel/jetpack-carousel.css`
3. Turn on the Jetpack gallery carousel option
4. Add a Newpack Post Carousel block and a gallery block to a post, on editor and frontend notice additional next and previous buttons
Before:
After:
=> Override the default :after content from swiper

src/blocks/carousel/editor.scss
Fixes a visual bug I've noticed in WP v5.8 affecting Post Carousel blocks in the editor.
1. On a site running WP v5.8, insert a Post Carousel block into a post's content. Observe that it looks strangely tall:
2. Check out this branch, refresh, confirm that it now appears at the expected height:
3. View on the front-end and confirm that the carousel appears as expected there, too.
=> fix: height of post carousel blocks in editor preview

src/blocks/carousel/editor.scss, src/blocks/carousel/view.scss
Adds `right: auto` to `.swiper-button-prev` to ensure the previous arrow button does not overlap the next arrow.
In RTL locales such as Arabic or Hebrew, the previous arrow styles are being dictated by SwiperJS CSS (`right: 10px`). 
**What I expected:**
**What I see:**
1. Insert a Post Carousel block
2. Switch your site and user language to Arabic/Hebrew
3. Ensure that the carousel arrows do not overlap in the editor or the frontend
4. Switch back to a LTR language and make sure these changes don't affect the arrows.
=> Carousel: Ensure that the swiper arrows don't overlap in RTL

src/blocks/carousel/create-swiper.js, src/blocks/carousel/edit.js
On the WP 5.8 Widgets page, widget areas after the first one are collapsed on initial page load, meaning the blocks within them are hidden. This causes issues with initializing SwiperJS instances inside Post Carousel blocks if those blocks are hidden when the component is first mounted.
This PR updates the editor component for the Post Carousel and waits until the component is visible before initializing its Swiper instance.
1. On `master`, go to **Appearance > Widgets**. In a widget area whose panel is collapsed on page load, add a Post Carousel block and save.
2. Refresh the page. Observe that the widget area panel is collapsed on page load. Expand it and observe that the Post Carousel block renders with an inert carousel; if you try to interact with it, you should see a JS console …
=> fix(wp-5.8): do not initialize swiper instances if component is hidden

src/blocks/carousel/edit.js
Allow SwiperJS to reinitialize carousels when block attributes are updated that affect the carousel's visual rendering. Fixes a regression introduced in #804.
1. On `master`, add a Post Carousel block to post or page content. Observe that the carousel functions in the editor preview as expected.
2. Alter some of the visual attributes in the block sidebar under Slideshow Settings and Article Meta Settings. Observe that after updating one of those attributes, the carousel ceases to be interactive unless you update the post and refresh.
3. Check out this branch, rebuild, refresh, confirm that this is no longer the case.
4. Confirm that the block still works as expected in the **Appearance > Widgets** and **Customizer > Widgets** admin pages.
=> fix: allow swiper to reinitialize carousel on attribute changes

includes/class-newspack-blocks.php
Due to incorrect assets path, view and editor scripts were loading fallback dependencies. This
resulted in unnecessary scripts being added to the front end as well as wrong dependencies being
added for editor scripts.
Closes #779.
Test 1:
1. Create a new page/post with Homepage Articles block.
2. Preview or view the page using devTools inspect mode.
3. Observe that there are no extraneous scripts added at bottom of the page.
Test 2: ( Using debug methods )
1. If you are using xdebug add a breakpoint at following line
https://github.com/Automattic/newspack-blocks/blob/d8dd2a98d89bbc3addc43b41a03ad263c3889fd5/includes/class-newspack-blocks.php#L44
2. Check that `$script_data['dependencies']` has the values defined in corresponding `dist/{script-path}.assets.php`
=> fix(class-newspack-blocks.php): assets meta file path for scripts

src/blocks/donate/class-wp-rest-newspack-donate-controller.php
Fixes a PHP dependency bug in the CI release builds. Seems like this dependency isn't needed because the Stripe PHP library was moved to `newspack-plugin` instead, which does load Composer dependencies on release build jobs.
1. Install the built `newspack-blocks.zip` asset from [the latest alpha release](https://github.com/Automattic/newspack-blocks/releases/tag/v1.30.0-alpha.2) on a fresh site. Attempt to activate and observe a PHP dependency error that prevents activation:
```
Warning: require_once(/srv/htdocs/wp-content/plugins/newspack-blocks-v1.30.0-alpha.2/vendor/autoload.php): failed to open stream: No such file or directory in /srv/htdocs/wp-content/plugins/newspack-blocks-v1.30.0-alpha.2/src/blocks/donate/class-wp-rest-newspack-donate-controller.php on line 8
Fatal error: …
```
=> fix: remove autoload dependency from donation class

src/blocks/carousel/edit.js, src/blocks/carousel/view.php
The Homepage Post block currently renders class names for the post type, categories, and tags for each item shown by the block. This PR applies the same classes for Post Carousel items, as well.
Related to but not dependent on https://github.com/Automattic/newspack-listings/pull/103.
1. On `master`, add a Homepage Posts and Post Carousel block to a page. Ensure that each is displaying posts with categories and tags.
2. In the editor and on the front-end, observe that the items shown by Homepage Posts have class names for post type, categories, and tags but that the Post Carousel items do not.
3. Check out this branch, rebuild and refresh. Now confirm that the items in both blocks show post type, category and tag class names.
=> feat: show term classes for Post Carousel blocks

includes/class-newspack-blocks-api.php, includes/class-newspack-blocks.php, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/utils.js, src/components/query-controls.js
Closes #600.
1. Insert Homepage Posts block
2. In the sidebar, "Display Settings" panel, click on "Show Advanced Filters" 
3. Fill in a category to exclude from the query and observe that posts from this category are not included in the block
4. Publish the content, observe that on the frontend too, the posts with the excluded category are not displayed
=> feat(homepage-posts): handle category exclusion

src/blocks/homepage-articles/view.scss
Closes #825.
1. Open a new page.
2. Add Homepage Post Block.
3. Set Styles > Borders.
4. Set to Grid View.
5. Show media behind.
6. Observe the column height is the same for all columns.
=> fix(homepage posts): fix inconsistent column sizing when border enabled

src/components/autocomplete-tokenfield.js
Closes #777.
1. Create a new post and grab the post ID.
2. In MySQL run update wp_posts set post_title = "This post has a space at the end of the title " where ID = 1234; (Use the ID from step 1). Then run wp cache flush to flush the post cache so the changes apply quickly.
3. On a different post/page, create a homepage posts block and use the specific select option.
4. Check the `Choose Specific Posts` display setting and search for "space". Select the newly added post from the suggested posts.
5. Observe the post gets added to the posts list.
6. If you check the `code view`,  we don't have a `null` anymore but the proper post ID:
``
=> fix: select specific posts with white space at the end of the title

src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
Prevents a PHP notice.
1. On `master`, open the editor and insert a Homepage Posts block
2. Observe a PHP notice logged: `Undefined index: categories_exclude…`
3. Switch to this branch, observe notice not displayed
=> chore: categories exclude in rest params

src/blocks/homepage-articles/view.php, src/shared/js/utils.js
This PR adds a `<span>` around the `by` text in the byline of the Post Carousel and Homepage Posts block.
It's to help us control this piece of the text differently with CSS, whether hiding (outstanding request), making it all caps or a different style, etc....
Closes #842.
2. Add a Homepage Posts and Post Carousel block to the editor. 
3. In the editor, inspect the blocks; confirm that the 'by' text in the byline is wrapped in a span, like `<span>by</span>`.
4. Publish the post. 
3. On the front-end, inspect the blocks; confirm that the 'by' text in the byline is wrapped in a span, like `<span>by</span>`.
=> Homepage Posts, Post Carousel: Add span to 'by' in block bylines

src/blocks/donate/class-wp-rest-newspack-donate-controller.php, src/blocks/donate/streamlined.js, src/blocks/donate/streamlined.scss, src/blocks/donate/view.php
Adds a newsletter opt-in checkbox in the donation form of the Donate block.
1. Switch to `feat/donations-mailchimp` branch of `newspack-plugin`
2. Switch to `feat/lists-getters-and-contact-adding` branch from `newspack-newsletters`
3. Configure Reader Revenue to use Stripe as the platform
4. Create a page with a Donate block, visit the front-end
5. Observe that after unravelling the form fields (clicking the "Donate" button) there is _no_ signup checkbox
3. Configure Newspack Newsletters to use Mailchimp as ESP
4. Visit the Reader Revenue wizard, choose a contacts list in the "Newsletters" settings section
5. On the frontend, observe that after unravelling the form there's a "Sign up for our newsletter" checkbox (checked by default)
6. Submit a test donation* using an email you have …
=> feat(donate): handle newsletter opt-in

src/blocks/donate/edit.js, src/blocks/donate/index.js, src/blocks/donate/view.php
This PR makes the "Thank you for your contribution." text editable, similar to how the donate block button text works. 
Closes #545
2. Add a donate block to the editor; try clicking on the 'Thank you' text and editing it; confirm you can make edits. 
3. Publish the page.
4. Confirm that your updated text appears on the front-end.
=> Donate Block: make 'thank you' text editable

src/blocks/donate/view.scss
Closes https://github.com/Automattic/newspack-plugin/issues/235.
1. On `master`, choose "Uzbekistani som" as the currency in Reader Revenue wizard
2. Visit a page with a Donate block, observe the money input (when chosen "Other" as the amount) displays the currency symbol and input in two separate lines
3. Switch to this branch, rebuild, observe issue resolved
=> fix: currency symbol handling

src/components/query-controls.js
Fixes a minor but editorially annoying bug with the Specific Posts selector field for Homepage Posts and Post Carousel blocks, discovered during GDG launch.
1. On `master`, add a Homepage Posts and/or Post Carousel block to a post or page.
2. Under **Post Types**, choose "Posts" and at least one other post type.
3. Under **Display Settings**, turn on Specific Posts and choose some posts (of the actual `post` post type) as well as posts of post types other than `post`. Save/update.
4. Refresh the editor. Select the block and expand **Display Settings**. Observe that in the Specific Posts field, only titles for saved posts with the post type of `post` are shown in the field. This means it's not possible to remove the posts of other post types from this block.
5. Check out this branch, …
=> fix: show all saved post types in specific posts field

src/blocks/carousel/edit.js, src/blocks/carousel/view.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php
Homepage Posts and Post Carousel front-end templates render category terms with a link. This omits the `a` anchor tag in the unlikely event that a term lacks a link. This could happen if the term being rendered is a "pseudo term", or a term that's appended programmatically to a post's term output based on some condition other than a true taxonomy term applied to the post. 
The use case this comes from: a "featured" post meta toggle which programmatically shows a "featured" category label alongside the post's other categories. In this case the "featured" category label is not tied to a true category term, therefore it has no term link.
Bonus: also ensures that if a post with no categories (not even "Uncategorized") gets rendered by Homepage Posts or Post Carousel with categories enabled, …
=> fix: only show category link anchor tags if the category has a link

src/blocks/homepage-articles/view.php, src/shared/js/utils.js
Fixes a minor visual bug in WP.com sites. Shouldn't affect anything on non-WP.com sites.
Ensure that the bylines in Post Carousel and Homepage Posts blocks still look as expected in the editor and on the front-end.
=> fix: specify whitespace between author prefix and byline

src/blocks/homepage-articles/templates/article.php
This PR switches the Article Subtitle to allow the same HTML that's allowed in the Newspack theme. Otherwise, you can add HTML and have it display nicely from the theme, but when it's coming from the block, the HTML is encoded and visible. 
See https://github.com/Automattic/newspack-theme/issues/1500
1. Edit a post and add some basic HTML to the Article Subtitle field. (strong, em, small...)
2. Publish the post and note that it's visible on the front-end. 
3. Add the same post to a Homepage Posts block and enable the Article Subtitle.
4. Note that your HTML tags are visible rather than being applied (eg. text isn't **bold**, but looks like `<strong>bold</strong>`):
5. Apply the PR.
6. Confirm that the HTML code is no longer visible, and the tags are actually applied:
=> feat: allow some html in the homepage posts subtitle

includes/class-newspack-blocks.php
When a publisher is using Newspack and has set up Newspack's donations feature, this addition will disabled Jetpack's donations block to avoid confusion when selecting the right block in the editor.
1. Ensure you see both the Jetpack and Newspack donate blocks in the block chooser
2. Apply the PR and reload the editor
3. Observe that Jetpack's block is no longer available when Newspack donations are configured.
=> Disable Jetpack donations when using Newspack donations

includes/class-newspack-blocks.php
A small feature which shouldn't affect any plugin behavior. Adds a filter for the term class names that are added to each post displayed in Homepage Posts and Post Carousel blocks. This will let other plugins hook into the filter and add arbitrary class names as needed. The specific use case I added this for is [featured listings](https://github.com/Automattic/newspack-listings/pull/124), but it might come in handy for other purposes as well.
1. Check out this branch.
2. Somewhere in your theme's `functions.php`, temporarily add a callback for the new filter:
```
function newspack_test_term_classes_filter( $classes ) {
$classes[] = 'my-arbitrary-class';
return $classes;
}
add_filter( 'newspack_blocks_term_classes', 'newspack_test_term_classes_filter' );
```
3. Add a Homepage Posts and …
=> feat: add a filter on term classes so other plugins can add classes

includes/class-newspack-blocks-api.php, includes/class-newspack-blocks.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/templates/articles-loop.php
Trims excerpts even if it's a custom excerpt for a uniform look.
Deprecated excerpt_length and excerpt_more methods in favor of a comprehensive excerpt callback.
Core only allows to control the length of generated excerpts, assuming that authors want to keep their custom excerpts as they're written. This PR will apply the excerpt length limit to both types of excerpts for a more uniform look.
Closes https://github.com/Automattic/wp-calypso/issues/51415
1. Once you checked out the branch and built the block…
2. Add a custom excerpt to a post, preferably a rather long one.
3. In a different post, insert the Homepage Posts block and manipulate the excerpt length.
4. Preview the post to make sure the front-end works as expected.
=> fix: limit excerpt lengths even for custom excerpts

includes/class-newspack-blocks.php
#874 added functionality to ensure that generated excerpts adhere to the length attribute set in Homepage Posts blocks. However, it seems that it causes every post to show a generated excerpt, even if it has a custom excerpt. This fix checks for a custom excerpt and uses it if it exists, before generating one.
1. Publish a post with a lengthy custom excerpt and some different post content.
2. On `master`, add a Homepage Posts block that will show this post to a page and enable "Show Excerpt."
3. Observe that your post is shown with a generated excerpt, not with your custom one, in both the editor and on the front-end.
4. Switch to this branch, confirm that the editor and front-end now show your custom excerpt, but trimmed according to the Excerpt Length setting in block attributes.
5. …
=> fix: if a post has a custom excerpt, use it

includes/class-newspack-blocks.php
Removes the `the_content` filter applied to excerpts generated for Homepage Posts blocks, since it might result in unwanted behavior if other plugins are using that same filter.
1. On `master`, temporarily add a function to your theme's `functions.php` to append some content on the `the_content` hook:
```
function newspack_test_content_filter( $content ) {
$content .= ' And this is my appended text!';
return $content;
}
add_filter( 'the_content', newspack_test_content_filter, 0 );
```
2. Add a Homepage Posts block to a page and turn on "Show Excerpts". Observe that excerpts are affected by your test filter in the editor and on the front-end.
3. Check out this branch, confirm that your excerpts are unaffected by the content filter.
=> fix: do not apply the_content filter to homepage post excerpts

src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
Adds an alignment control to the block when the featured image is shown and the image position is "top", allowing users to centre-align the block text when using that particular image style.
Closes #847.
1. Apply the PR and add a block, selecting the combination mentioned above for feature image
2. Observe the alignment control (dis-)appearing as you change the options
3. Observe that the correct CSS class is applied and the text is aligned accordingly.
One note: there is no horizontal line between the alignment control and the three dots - I wasn't sure why or how to correct that.
=> Add text alignment option when image featured image is at the top

includes/class-newspack-blocks.php
This is needed when we do use the homepage-posts block in an overlay, we need to show all the filtered posts even if they were rendered in another block previously
Technically this PR just adds a filter so nothing should change with this. If the filter is enabled, in the homepage-posts block, we'll render all filtered posts including the ones previously rendered. We needed this since the overlay prompts from the `newspack-popups` act as another content layer.
1. Create a prompt with placement before header, with a `homepage-posts` block, and filter the posts by a category.
2. Create an overlay prompt with a `homepage-posts` block, and filter the posts by the same category from 1.
3. Load the homepage and observe that the posts loaded in the overlay don't include the ones rendered in the …
=> feat(homepage-posts): enable showing previously rendered posts too

src/blocks/iframe/class-wp-rest-newspack-iframe-controller.php
Without the trailing slash, the iframe URL does a redirection to add the slash and set the request on HTTP which raises a mixed content issue, adding the trailing slash would stop the redirection and minimize the calls to the server. The issue was raised in the Atomic environment but I was able to reproduce it locally too.
1. If you don't have HTTPS use a temporary Atomic site.
2. On a new post, add the iframe block.
3. Upload a zip archive with at least an index.html file that will be the entry point to your iframe (I attached a zip archive for tests).
4. Notice that the iframe doesn't preview, and the console shows a mixed content error due to a redirection to HTTP.
5. Pull this PR.
6. Upload again the same archive and notice this time there is no redirection and the iframe loads as …
=> fix(iframe-block): add a trailing slash to iframe URL

src/blocks/homepage-articles/templates/article.php
This PR adds [`wptexturize`](https://developer.wordpress.org/reference/functions/wptexturize/) to the article subtitle.
See https://github.com/Automattic/newspack-theme/issues/1570
1. Add a subtitle to a post; make sure to include a quote or apostrophe, or `--`.
2. Add a homepage posts block that includes that article, and set the Article Subtitle to be visible in the right sidebar. 
3. View the block on the front-end -- in the subtitle, the quotes/apostrophes will be straight up-and-down, and your `--` will look like `--` (when it's normally transformed to a proper m-dash when added through the post editor).
4. Apply the PR.
5. Refresh the page with the homepage posts block; you should now have smartquotes, and/or a proper m-dash (&mdash;).
=> fix: add wptexturize to the article subtitle

src/blocks/author-profile/class-wp-rest-newspack-authors-controller.php, src/blocks/author-profile/view.php
Fixes two bugs:
* The front-end link rendered for guest authors' post archives depended on query args instead of "pretty" URLs. This works most of the time, unless the permalink slugs for guest authors contain non-URL-friendly characters (especially slashes), in which case the links result in 404s. This latter condition can really only happen if the `cap-user_login` meta field is set manually, for example during a data migration.
* When rendering WP users that are linked to CAP guest authors, the WP user's info and links are shown. This doesn't match CAP's behavior, which essentially replaces WP user info rendered on the front-end with the linked guest author.
Closes #903.
1. While on `master`, create a guest author and link it to a WP user. For ease of testing, the two authors should …
=> fix(author-profile): corrected CAP author links; linked WP users

src/blocks/carousel/create-swiper.js, src/blocks/carousel/edit.js, src/blocks/carousel/view.php, src/blocks/carousel/view.scss
This PR makes some visual updates to the Post Carousel block:
* To scale down the title font size when displaying 3-4 slides at once
* To alter the number of posts shown on tablet and mobile-sized screens, so they don't get too croweded.
* To fix an issue with the aspect ratio getting smooshed on blocks displaying 3-4 slides, on smaller screen sizes. 
Closes #844.
1. Add four Post Carousel block to a page: one displaying one slide at a time, one displaying two, one displaying three and one displaying four. Publish. 
2. View on the front end; note the blocks showing 3-4 slides at a time are crowded: 
3. Scale down the browser window to roughly tablet and mobile sizes; note the appearance of the blocks, specifically how the text can get cut off on the 3-4 slide blocks, and how their aspect …
=> Post Carousel: update sizing for multiple slides, mobile

src/blocks/donate/streamlined.js
As per [docs](https://www.npmjs.com/package/@stripe/stripe-js):
> If you would like to use loadStripe in your application, but defer loading the Stripe.js script until loadStripe is first called, use the alternative @stripe/stripe-js/pure import path
1. On `master`, open a page with the Donate block in streamlined (Stripe) version*
2. Observe that Stripe's JS (`https://js.stripe.com/v3`) loads on page load 
4. Observe the Stripe JS loads after clicking the "Donate" button, which initiates the payment flow
\* Choose and configure Stripe as the platform in Reader Revenue wizard
=> feat(donate-block): defer Stripe scripts loading

includes/class-newspack-blocks.php, src/blocks/carousel/view.php, src/blocks/donate/view.php
Closes #953
Not all view scripts (JS loaded on the frontend) were handled in AMP Plus mode. This PR fixes that, ~so that the blocks' interactions in AMP Plus mode are as they do with AMP disabled.~ 
_Initially, this PR forced all blocks into behaving as with AMP disabled in AMP Plus. There's no need for this, though. The only block that really needs to use AMP Plus features is the streamlined version of the Donate block, because it needs to load additional scripts._
1. Observe that #953 is not reproducible
2. Confirm that Carousel block's frontend JS-reliant interactions work as expected with AMP Plus mode on, and exactly as with AMP enabled
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1200994000430649
=> fix: view scripts in AMP Plus mode

.circleci/config.yml
A [release job](https://app.circleci.com/pipelines/github/Automattic/newspack-blocks/1401/workflows/77f27c63-d8c0-46df-b449-534da29d0520/jobs/3028) has failed with the following error:
```
E: Unable to locate package rsync
```
In other repositories [`apt-get update` is ran](https://app.circleci.com/pipelines/github/Automattic/newspack-popups/1739/workflows/c56ece87-9e22-43e1-bf5d-12a4037516de/jobs/6701) before this command. Let's see if that fixes it.
=> ci: update apt-get before installing rsync

src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php
Implements Lazy Load toggle for the Homepage Posts block in order to improve [Largest Contentful Paint (LCP)](https://web.dev/i18n/en/lcp/) score for blocks above the fold.
It also implements by default the `data-hero-candidate` attribute to take advantage of AMP's prerendering features for LCP improvement.
Closes #969.
With AMP Plus on:
1. Check out this branch and install it on a JN or behind ngrok.
2. Set up a page with a Homepage Posts as the first block. It should use "Show media behind" as the media position to take as much screen space as possible. 
3. Visit the page and notice the `<img />` contains the `loading="lazy"` attribute.
4. Obtain the page metrics at https://web.dev/measure
5. Edit the block on the "Featured Image Settings" toggle on the "Disable Featured Image Lazy …
=> feat: disabling image lazy load for homepage articles

src/blocks/carousel/view.php
The Post Carousel block renders an `amp-base-carousel` on AMP-enabled pages, but several attributes in our markup have missing values or just aren't valid attributes for that AMP element. This means that any pages with a Post Carousel will fail AMP validation.
1. On `master`, add a Post Carousel block to a post.
2. In the sidebar, expand AMP and click "Open AMP Validation" then "Re-validate" to trigger AMP validation for the post content.
3. Observe several errors (particularly the `controls`, `loop` and `type` attributes) relating to the Post Carousel like so:
4. Check out this branch, re-validate for AMP again. Confirm that the errors related to Post Carousel are no longer reported.
=> fix: validation errors for invalid attributes on amp-base-carousel

src/blocks/donate/streamlined.js, src/blocks/donate/streamlined.test.js, src/blocks/donate/view.php
Allows hiding of cover-fees checkbox (#928) if the fees amount to 0.
_Follow steps in https://github.com/Automattic/newspack-plugin/pull/1376_
=> feat(donate-stripe): hide fee checkbox if fees are zero

src/blocks/carousel/edit.js, src/blocks/carousel/editor.scss, src/blocks/carousel/view.php, src/blocks/carousel/view.scss
This PR adds a simplified CSS class to the Post Carousel block (`wpnbpc`, to replace the longer `wp-block-newspack-blocks-carousel` class in the CSS. 
This helps reduce the amount of CSS loaded by AMP, especially since this class is included in every style associated with this block -- something similar was done with the Homepage Posts block early on. In my testing, it reduces the CSS by 1.7% when the controls are visible:
With controls before changes: 7,183b = 9.6% of 75kb
With controls after changes: 5,996b = 7.9% of 75kb
There's probably more that can be done here but it's a start!
1. Set up a Post Carousel block, and check your AMP CSS usage.
2. Apply the PR and run `npm run build.`
3. Clear your browser cache; make sure the post carousel looks right with and without AMP enabled, on …
=> Post Carousel: add simplified CSS class to carousel to reduce style size

block-list.json
Adds the `author-list` block to the manifest of blocks to be built for production (`block-list.json`). Without it, automated build jobs won't include the new block. This wasn't caught previously because the `watch` command will include all block source files regardless of what's in the manifest.
1. On `master`, delete the `dist` folder (`rm -r dist`) and rebuild using `npm run build`.
2. Observe that you can't add an Author List block to any post or page.
3. Check out this branch, repeat step 1, confirm that you can now add the Author List block and view it on the front-end.
=> fix: add Author List block to manifest of blocks to build in production

src/block-styles/core/columns/editor.scss, src/block-styles/core/columns/view.scss
In the Newspack Blocks suite, we have some column block styles that:
1. Update the default column block styles, to not wrap until they hit the mobile breakpoint.
2. Allow you to add borders to the columns.
3. Allow you to reorder the columns on desktop.
Changes coming in WP 5.9 to add the option to not wrap columns on mobile have overridden some of our own styles. This PR hopefully sorts them out and gets them working again, without causing issues in 5.8.
Closes #1018 and #1019
This will be easiest to test if you can work with two test sites and compare them: one running WordPress 5.8.X, and the other running the 5.9 RC.
1. In the test site running 5.9 RC, copy [this test content](https://github.com/Automattic/newspack-blocks/files/7885188/columns-59.txt) to the editor, or add a bunch of …
=> Update Column Block styles for WordPress 5.9.

src/block-styles/core/columns/view.scss
Changes in #1018 incorrectly added the bottom margin between columns that's needed on mobile. This PR reinstates it.
1. On a test site running 5.9, set up some columns, with and without the border style, and with and without 'Stack on mobile' checked. View on mobile sized screens. 
2. Note that when the columns don't have borders, they don't have space between them on mobile:
4. Confirm that the columns now have space when stacked on mobile, and that no extra space is added on desktop, or between columns with borders:
5. Test on a site running 5.8 and confirm that this change did not cause visual regressions.
=> Re-add column vertical spacing

src/blocks/video-playlist/view.php
Closes #577
1. Insert some youtube embeds in some posts
2. Insert the "Video Playlist" block on a page
3. Observe the embeds from other posts are compiled to a playlist on this block
=> fix(video-playlist): youtube embeds fetching

.distignore, includes/class-newspack-blocks.php
1. Handles the case of Newspack plugin unavailable
2. Adds `.cache` directory (npm-related) to `.distignore` file, so it won't be included in the released ZIP 
1. On `master`, deactivate the Newspack Plugin 
2. Try to add a new page in Newspack admin, observe a PHP fatal `Fatal error:  Uncaught Error: Class 'Newspack\Donations' not found` thrown
3. Switch to this branch, observe no fatal thrown
=> fix: handle unavailable Newspack plugin

includes/class-newspack-blocks.php
Fix the NextGen Gallery and Homepage Posts block conflict by disabling NextGEN's `C_NextGen_Shortcode_Manager`. The way it currently parses `the_content` conflicts with the REST API request to save a post containing a Homepage Posts block. This is due to how it uses output buffering through `ob_start()` on REST requests.
https://plugins.trac.wordpress.org/browser/nextgen-gallery/tags/3.23/non_pope/class.nextgen_shortcode_manager.php#L193
Closes #665.
Reproduce the steps mentioned in #665 with this branch and confirm the post saves without errors.
=> fix(NextGen Gallery): disable ngg shortcode manager

src/blocks/iframe/index.js, src/blocks/iframe/view.php
This PR makes two changes to the iframe block: 
1. It makes sure that the alignment classes (alignwide, alignfull...) are added to the front-end of the site -- multiple alignments were available, but the styles weren't actually being applied. 
2. It pares down the alignment options from all (left, right, center, wide and full) to just wide and full. 
I am definitely open to feedback about the second change! My feeling is that the left, right and (to a lesser extent) centre alignments are less useful options for something like an embed. 
On top of that, none of them really work even with the right classes applied to the front-end: if an iframe is aligned left or right, it needs a fixed px width set so it doesn't "collapse" due to how the theme styles left and right-aligned blocks. If the …
=> iFrame Block: Add alignment classes and update options

src/blocks/donate/streamlined/utils.js
Fixes a bug. Should be followed by a hotfix, since the bug is released on `alpha`.
1. Set up streamlined Donate block
2. Deactivate `newspack-popups` 
3. Observe the Donate block does not fully load on the front-end
=> fix: handle inactive newspack-popups

includes/class-newspack-blocks-api.php
https://github.com/Automattic/newspack-listings/pull/233 refactors class names in the Listings plugin. This PR updates an instance where we use a Listings class to match the refactored name.
No changes in functionality. Ensure that if you add a listing whose "Hide author" and "Hide publish date" options are on to a Homepage Posts block that shows author and publish date, that info is still hidden for that listing.
=> fix: update listings class name to match after refactor

package-lock.json, package.json, src/blocks/homepage-articles/store.js, src/blocks/homepage-articles/utils.js
While adding a Homepage Posts or Carousel block to a widget area through the new block-based UI you get placeholder content instead of fetching actual posts.
This PR makes the necessary changes for these blocks to perform the posts fetch on the widget editor.
| Current | This PR |
| --- | --- |
| <img width="732" alt="image" src="https://user-images.githubusercontent.com/820752/157888670-ef9efd8b-04d0-48d7-901b-f2ede7cc7398.png"> | <img width="731" alt="image" src="https://user-images.githubusercontent.com/820752/157889258-bbb8e6dd-1514-4841-9789-e0ba2af1afa8.png"> |
1. If you are running Newspack plugin, check out https://github.com/Automattic/newspack-plugin/pull/1550 to enable the block-based widget editor
2. While on master, visit Appearance -> Widgets and place a Homepage Posts and a …
=> fix(homepage-posts): post fetch for widget blocks

src/blocks/donate/view.scss
This PR changes the Tiers Grid breakpoints for the Alternate and Minimal styles.
See #1077 
1. Add 2 donate blocks on a page, 1 with Alternate style, 1 with Minimal style
2. Resize your screen
4. Refresh page
=> fix: donate block non-default styles grid breakpoint

includes/class-newspack-blocks-api.php, includes/class-newspack-blocks.php, src/blocks/author-profile/class-wp-rest-newspack-authors-controller.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/utils.js, src/blocks/homepage-articles/view.php, src/components/query-controls.js
This PR supersedes #1082. Testing instructions remain the same except for an additional testing step at the end (see bolded header below). 8ddcee8 is the only new commit in this branch vs #1082, if that helps with code review.
Fixes four bugs related to author querying:
1. A SQL syntax error when filtering Homepage Posts blocks by authors and including at least one Co-Authors Plus guest author
2. When filtering Homepage Posts blocks by CAP guest authors, posts by linked user accounts are not included in the results
3. An unhandled `include` query param when fetching saved authors to display in the block sidebar controls
4. When filtering by a WP user, posts that were created by that user but are attributed to an unrelated CAP guest author are also fetched
1. On `master`, add several …
=> fix: authors and guest authors in homepage posts

includes/class-newspack-blocks.php
Fixes a bug in the `tax_query` syntax when filtering Homepage Posts blocks by WP user and no CAP guest authors. The args were missing a level of array nesting, resulting in the `tax_query` being ignored by the query.
1. On `master`, add a Homepage Posts block to a post and filter it by:
- A non-CAP WP user
- A category exclusion
2. Observe that in both the editor and front-end, the block does not properly filter by the WP user. Instead, it shows posts by any user.
3. Check out this branch, confirm that the block now shows only posts by the WP user, without the excluded category.
=> fix: incorrect nesting of tax_query args

CHANGELOG.md, newspack-blocks.php, package-lock.json, package.json, src/blocks/homepage-articles/block.json, src/components/query-controls.js
#1083 re-instated issue fixed by #857. There's some confusion around "post type" attribute's casing in `Newspack_Blocks::build_articles_query` method – if `post_type` is supplied in the `$attributes` argument (instead of `postType`), it will be overridden with the default value (`['post']`). 
This PR ensures that the call to the API always uses the camel-case `postType` (and not snake-cased `post_type`).
This confusion arises from the fact that `postType` is the block attribute, and `post_type` is the API call param.
1. Observe that the issue described in #857 is reproducible on `master`
2. Switch to this branch, observe the issue is not reproducible
=> fix(posts-query): specific posts getting

CHANGELOG.md, includes/class-newspack-blocks-api.php, newspack-blocks.php, package-lock.json, package.json
Restores the `post__in` sort order of Homepage Posts block using specific posts mode, which was accidentally deleted in #1083.
Closes #1092.
Confirm that the bug described in #1092 can't be replicated, and that the posts appear in the exact order as entered in both editor and front-end.
=> fix: restore post__in sort order for specific posts mode

includes/class-newspack-blocks-patterns.php, src/block-patterns/subscribe-7.php, src/block-patterns/subscribe-8.php, src/block-patterns/subscribe-9.php
This PR adds 3 new subscribe patterns. These are slightly different from the previous ones. They use `templateLock: all` on the main `Group` and `lock:{remove:false}` on the heading and copy.
This means that these patterns are kind of locked yet there's still some flexibility with its customisation.
2. Insert the various patterns to a page and/or a prompt
=> Add 3 new subscribe patterns

src/blocks/donate/class-wp-rest-newspack-donate-controller.php, src/blocks/donate/view.php, src/blocks/donate/view.scss
_See and follow instructions in https://github.com/Automattic/newspack-plugin/pull/1599._
=> feat(donate): handle woocommerce-memberships

includes/class-newspack-blocks.php
Closes #2
Observe that (in a non-AMP environment!) a `wp-polyfill` script is loaded on a page with a Newspack Block. It probably also loads for most setups on `master`, since it's a common practice to do that.
=> chore: add wp-polyfill to view scripts

src/blocks/carousel/view.php, src/blocks/homepage-articles/templates/article.php
This PR replaces the author-provided alt text on the linked featured images with the post title. This helps give some context to where the link actually goes, to improve accessibility. Otherwise, descriptive text in this context isn't as helpful because it doesn't tell someone navigating the site via screenreader where the link on the image goes. 
Closes #1115
1. Apply the PR.
2. Add a Homepage Posts and Post Carousel block to a page; make sure each block has at least one post with a featured image. 
3. Publish.
4. Inspect the source and confirm that the alt text on the featured image matches the post title.
=> Homepage Posts & Carousel blocks: Improve alt text on images linked to posts

src/blocks/donate/view.scss
This PR tweaks the Donate block styles so the radio buttons that aren't visible are no longer hidden with `display: none`, but with `position: absolute; left: -99999em` to push them off screen. This way, they can be tabbed to when navigating the site with a keyboard, so it improves the block's accessibility. 
The styles also add some visual changes when a tab/tier is focused on -- I stuck with `outline` so it wouldn't change things too much (since these are also visible when you click on a tab/tier) but we might want to look at something more noticeable down the road, as this is pretty low contrast. 
Closes #123
1. Add a donate block to a post or page and publish.
2. Try to "tab" through the page (you can 'Skip to Content' at the top). When you get to the block, note that the focus skips …
=> Donate block: make possible to navigate via keyboard

package.json, src/blocks/homepage-articles/edit.js, src/blocks/iframe/edit.js, src/setup/newspack-logo.js, src/shared/js/newspack-icon.js, src/shared/js/utils.js
Lint npm script was actually formatting code, not linting. This fixes it and fixes linting issues introduced in the meantime.
Observe the JS linting job passing on CI
=> chore: linting fixes

includes/class-newspack-blocks-patterns.php, src/block-patterns/subscribe-10.php
This is a very simple pattern, 2 columns (70 - 30) with paragraph and mailchimp block. It's intended for "above header" inline prompts.
2. Apply Newspack theme PR: https://github.com/Automattic/newspack-theme/pull/1818
3. Create new above header prompt
4. Insert this pattern
5. Publish
=> Add new subscribe pattern

src/blocks/carousel/view.php, src/blocks/homepage-articles/templates/article.php
In the Sponsors markup, the code is missing an `echo` on the closing link on the byline for both the Homepage Posts and Post Carousel blocks. I think this flew under the radar because it doesn't seem to cause issues when AMP is enabled (AMP seems to be correcting the malformed HTML), but when AMP is disabled, it causes visual issues. 
Closes #1151.
1. Start with a test site with a number of sponsored posts.
2. Set up a Post Carousel and Homepage Posts block that each display at least one of your sponsored posts that has a native sponsor; enable dates on both blocks.
3. View on the front end and disable AMP.
4. If your blocks have dates displaying, they should be incorrectly picking up the sponsor byline's link; failing that, you can also inspect the page and see that the sponsor byline …
=> Sponsors plugin integration: echo closing link tags on sponsor bylines

src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php, src/blocks/author-list/edit.js, src/blocks/author-profile/block.json, src/blocks/author-profile/class-wp-rest-newspack-authors-controller.php, src/blocks/author-profile/edit.js, src/blocks/author-profile/view.php
Accounts for a previously unhandled edge case where a CAP guest author and a WP user might have the same numeric ID in the DB. In this case, `master` will always choose the guest author over the WP user because we can't tell which type of author to fetch with only the ID.
This PR fixes the above issue by storing a new block attribute `isGuestAuthor` as part of the Author Profile block. If this is `true` (the default), the block's behavior will behave as it currently does (search guest authors first, and if none found, fall back to WP users). If it's `false`, it will only search WP users. This ensures that if a WP user is chosen which has the same ID as a CAP guest author, the WP user will be displayed in the editor and the front-end.
Note that this doesn't fix pre-existing instances of …
=> fix: disambiguate WP users vs. guest authors with same ID

src/blocks/donate/view.scss
As of WordPress 6.0, something changed in the editor styles causing the Donate Block tabs to exceed their normal width -- in WP 5.9.3, the tabs were picking up `box-sizing: border-box;` thanks to a style `.edit-post-visual-editor * { box-sizing: inherit; }`; as of 6.0 that style appears to be gone. 
This PR fixes the issue by adding `box-sizing: border-box;` to the tabs directly. 
(You can test the appearance of the Donate Block before and after the WordPress 6.0 update by installing the [Core Rollback](https://wordpress.org/plugins/core-rollback/) plugin and switching your test site back to 5.9.3). 
**WordPress 5.9.3:**
**WordPress 6.0**
1. Add a donate block to the editor and note its appearance: 
2. Apply the PR and run `npm run build`.
3. Confirm that the tabs are no longer 'sticking …
=> Donate Block: correct tab spacing in editor

src/blocks/iframe/class-wp-rest-newspack-iframe-controller.php
Handle errors from server-side fetch of iframe URL for the iframe block:
Closes #1160 
1. On the master branch, create a draft post and paste a random non-existent URL to an iframe block
2. Observe the error as described in #1160
3. Check out this branch, paste the URL again and confirm you see the error message returned from `wp_safe_remote_head()`, as shown above
=> fix(iframe-block): handle errors from server-side fetch

src/setup/editor.js, src/setup/unregister-blocks.js
This PR unregisters the [Jetpack Donations block](https://jetpack.com/support/jetpack-blocks/donations-block/), so it's not so easily confused with the Newspack Donate block.
Closes #1161.
1. Start on a test site running either a Jetpack Security or Jetpack Complete plan active (please ping me if you don't already have this plan and I can help!). 
2. Type `/donate` into the editor and note the blocks that appear:
4. Repeat step 2 and confirm that the 'Donations Form' block no longer appears in the list.
=> Blocks: Unregister Jetpack's Donation Form block

src/setup/unregister-blocks.js
If Jetpack is not installed it currently attempts to unregister a non-existing block and throws an error. This PR adds a check to only unregister a block that is registered.
1. While on the master branch, deactivate Jetpack
2. Edit any post/page and confirm the error on the browser console
3. Check out this branch, build and confirm the error is gone
4. Reactivate Jetpack and confirm the block is not available, as it's still being unregistered successfully
=> fix: make sure block exists before unregistering

src/blocks/homepage-articles/view.scss
Blog post block uses a flexbox to render items in a grid and use `justify-content: space between` to determine how the items are laid out. This however causes the flexbox to force empty space between some items when there is an odd number of items in the grid. This fix changes how items are laid out using  `justify-content: flex-start` so items are properly aligned when rendered and instead of allowing flexbox to determine the space we specify a `gap` between each item.
Closes #1171.
Original issue https://github.com/Automattic/wp-calypso/issues/62318
1. Create a number of posts (about 5)
2. Create another post and add Blog Post Block with the posts created from 1 above. use a 3 * 3 grid 
3. Verify the posts are properly aligned with no empty space between.
Before:
After:
=> Blog Post Block: Fix grid so items are aligned when an odd number of posts are inserted

src/blocks/donate/view.php
1. On `master`, set a default frequency for a Donate block
2. Observe it's not respected on the front end
3. Switch to this branch, observe the default currency is set as expected
=> fix(donate-block): handle default frequency from attributes

src/blocks/donate/class-wp-rest-newspack-donate-controller.php
Adds the current page URL to the client metadata. I'm aware of the inconsistent casing, but the camelcased properties were meant for Stripe and are processed as such, while this new property is meant for Reader Activation and already processed as snakecased.
_Follow instructions in https://github.com/Automattic/newspack-plugin/pull/1841 or just smoke test._
=> feat(donate): add current_page_url to client metadata

includes/class-newspack-blocks.php, src/blocks/donate/class-wp-rest-newspack-donate-controller.php, src/blocks/donate/streamlined/index.js, src/blocks/donate/streamlined/style.scss, src/blocks/donate/streamlined/utils.js, src/blocks/donate/view.php
Implements reCaptcha v3 to secure Stripe donation forms. Relies on reCaptcha v3 credentials entered into the UI implemented in https://github.com/Automattic/newspack-plugin/pull/1879.
If reCaptcha is enabled and credentials are stored, then all form submissions via the Stripe donate block will be tested against the reCaptcha v3 API before we attempt to process the transaction with Stripe. If the reCaptcha test returns a score lower than `0.5` (the default threshold for likely valid/human interactions), then we will fail the test and stop the transaction with an error message.
Note that reCaptcha v3 is an "invisible" form of captcha and doesn't involve any front-end user input, so the change will be totally invisible to most valid users. [More info …
=> feat: use reCaptcha v3 to secure Stripe donate forms

src/blocks/donate/streamlined/utils.ts
Looks like #1201 introduced a small bug due to removing the fallback/default value of `0` for `amount` when calculating the total donation amount plus Stripe fees.
Closes #1226.
Confirm that #1226 is not replicable.
=> fix: ensure amount is always defined for totalAmount calculation

includes/class-newspack-blocks-api.php
This PR re-adds the excerpt length preview that was accidentally removed in https://github.com/Automattic/newspack-blocks/pull/1083.
Closes #1094.
1. Add the Homepage Posts block to the editor, and change the excerpt length.
2. Note that the block reloads (becomes semi-transparent) but the excerpt length doesn't change -- however, if you publish your changes the new excerpt length will work on the front-end.
3. Apply this PR. 
4. Confirm that if you change excerpt length, it now previews correctly in the editor.
=> Homepage Posts Block: Re-add excerpt length preview in editor

includes/class-newspack-blocks.php, src/blocks/donate/class-wp-rest-newspack-donate-controller.php, src/blocks/donate/streamlined/index.ts, src/blocks/donate/view.php, src/types/index.d.ts
Refactor required to handle the migration of reCAPTCHA settings to the Reader Activation wizard in https://github.com/Automattic/newspack-plugin/pull/1910.
This is technically a pure refactor. To test, check out this PR and https://github.com/Automattic/newspack-plugin/pull/1910 and follow the testing steps in https://github.com/Automattic/newspack-plugin/pull/1910 to confirm that reCAPTCHA still works as expected on streamlined donate blocks.
=> refactor: handle reCAPTCHA settings and methods move to RAS

src/blocks/homepage-articles/view.php
The 'More' button in the Homepage Posts block has the `wp-block-button__link` class in the editor, but it doesn't have it on the front end. 
This isn't always a problem -- the button normally picks up the styles for the `button` HTML element -- but with FSE themes, there aren't styles generated for the `button` element by default. However, because the `wp-block-button__link` class is in the editor, the styles do match there.
This PR adds the `wp-block-button__link` to the front-end as well.
Closes #1070.
1. Switch to a FSE theme (like Twenty Twenty Two).
2. Add the Homepage Posts block to the editor, and turn on the 'Load More' posts button. Note the appearance in the editor (it will be picking up the theme's default dark grey background, and square corners):
3. Publish and view on the …
=> Homepage Posts block: make sure More button inherits styles

src/blocks/donate/view.php
Fixes a small issue with the Donate block: deriving name from registration email is overly optimistic and might be confusing. Until the user explicitly provides their full name, this should not be prefilled. 
1. Enable Reader Activation and set Stripe as the RR platform
1. Register as a new reader and visit a page with a Donate block
2. On `master`, observe the name field in the form is pre-filled with a name derived from the registration email
3. Switch to this branch and observe the name is not pre-filled
4. Visit the My Account page (you'll have to verify the account) and update the first & last name
5. Visit a page with a Donate block and observe the name is pre-filled correctly
=> fix(donate): use first & last name as default name

src/blocks/donate/view.php
This PR sets the default value rendered on the block to never be below the configured minimum. It would be unintuitive for the donor not to be able to donate with the proposed value on the form.
Although the settings can be saved with a lower value, the displayed warning should be enough to let the user know that it may not behave as expected.
1. On the master branch, configure Reader Revenue Donations settings with a minimum donation to 5 and tiers below that value
2. Visit the page with the block and confirm these values are rendered and you are unable to donate with the default values
3. Check out this branch and confirm the values are never rendered below 5 even though you are still able to store it that way and prompted with the warning
=> fix(donate): default value not below minimum donation

src/blocks/donate/class-wp-rest-newspack-donate-controller.php, src/blocks/donate/streamlined/index.test.js, src/blocks/donate/streamlined/index.ts
Detects if a donation happened from inside a Newspack Campaigns prompt, and if it did, adds the prompt's unique ID to the payment metadata sent to Stripe for processing payment. This will get picked up by https://github.com/Automattic/newspack-plugin/pull/1928 to append the prompt ID to the label attached to the GA event for the donation.
Follow testing instructions in https://github.com/Automattic/newspack-plugin/pull/1928.
=> feat: if donation via a prompt, add prompt ID to Stripe payment metadata

src/blocks/donate/view.scss
In the latest release of the Newspack Blocks, the thank you message is sitting beside the Donate Block button instead of above it, and some styles from the theme are causing an odd vertical alignment. 
This PR switches the Thank You message from `display: inline` to `display: block`, to stack it above the button again. 
Closes #1257
1. Add the Donate Block to a page and publish. 
2. View on the front end and note that the thank you message is next to the button, and weirdly aligned (in the editor the vertical alignment is a bit better, but the placement is different than in the 1.55 release:
4. Confirm that the thank you message is now above the donate block button:
5. Cycle through the different Donate Block styles and confirm that no display …
=> fix: correct Donate thank you message alignment

src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
This PR tackles a couple changes to how the column spacing works with the Homepage Posts block:
* It fixes an issue with the columns no longer filling the whole space (#1213)
* It fixes an issue with the last item wrapping when pairing the grid and border settings in the editor (#1233)
* The columns used to be spaced out a a bit haphazardly by using `justify-content: space-between`; this PR updates the default gap to be 32px to match the columns block; it also adds an option to reduce the gap if needed (#638).
Closes #1233, #1213 and #638.
1. Switch your site to the default Newspack theme -- this makes it easiest to see if the columns span the full space, because the accent header fills the whole space. 
2. Create a post and add an assortment of Homepage Posts blocks to the editor -- …
=> Homepage Posts: fix column spacing and add control 

README.md
Since the README is aimed at developers, but this repo is the only place the plugin can be found, let's link to our end-user documentation, too.
=> Add: Link to end-user documentation

composer.json, composer.lock, phpunit.xml.dist, tests/bootstrap.php
This PR updates our phpunit tests dependencies to allow us to run them against the latest version of WordPress
=> test: update tests dependencies

src/blocks/donate/streamlined/index.ts, src/blocks/donate/streamlined/utils.ts, src/blocks/donate/view.php
Adds zero fees handling for Simplified Donate block and closes https://github.com/Automattic/newspack-plugin/issues/1911
1. Configure the site to use Stripe as the Reader Revenue platform
2. On `master`, observe that setting just one of the fee-regulating values to 0 in the Reader Revenue wizards results in a fee of 0 being displayed
3. Switch to this branch, observe that the fee is properly calculated even if one of the fee-regulating values is 0
4. Set both values to 0, observe it resulting in no fees checkbox being displayed
=> fix(donate): handle zero fees

src/blocks/carousel/edit.js, src/blocks/homepage-articles/edit.js
The Sponsors flag wasn't previewing in the editor in the Homepage Posts or Post Carousel blocks, unless the category was also set to display with that sponsor. This PR tweaks the logic so it should line up with how things display on the front-end.
Closes #1277
1. Create two sponsors: one with the default settings, and one with "Sponsorship Category Display" set to Sponsors and Categories in the sidebar.
2. Assign each sponsor to a category, and make sure that category is assigned to at least four posts. 
3. Set up six homepage posts blocks, with the following settings:
* Two blocks that display one post each, from the Sponsored category that's set to show the sponsor flag and category. In the block settings, set Show Category on one of these blocks.
* Two blocks that display one post …
=> Sponsors: make sure sponsor flag previews in blocks in the editor

.circleci/config.yml, composer.json, composer.lock
This upgrades the tests so they can run both on php 7.4 and 8.
To test it, load the repo in a php 8 environment and run composer install. the run ./vendor/bin/phpunit
Do the same thing on a php 7.4 environment, but run composer update instead of install. (Discard the changes to composer.lock afterwards)
=> test: Upgrade to php 8

src/blocks/carousel/view.php, src/blocks/homepage-articles/templates/article.php
Updating the newspack-blocks in the editing toolkit causes php lint issues.
You can see the failing editing toolkit job on this PR here: 
https://github.com/Automattic/wp-calypso/pull/67870
This PR applies trivial fixes to unblock the related PR
=> Fix php linter errors caused by $sponsor_classes

src/blocks/donate/edit/index.tsx, src/blocks/donate/types.ts
See https://github.com/Automattic/newspack-plugin/pull/2160
1. Switch the main plugin to `feat/rr-other-option` branch (https://github.com/Automattic/newspack-plugin/pull/2160)
2. Insert a Donate block on a post or page, observe that it displays an error in the editor:
3. Switch the platform to a different one, observe the block is rendered correctly in the editor
=> feat: handle 'other' reader revenue platform in the editor

src/templates/author-profile-card.php
Fixes an overzealous sanitization function in the Author Profile and Author List blocks that prevented avatar images from loading all their attributes, resulting in low-res images being rendered in high-DPI environments (due to the `srcset` and `sizes` attributes being stripped).
Closes `1203451787793554/1203512877120434`.
1. Create a guest author and add a high-res avatar image.
2. Add an Author Profile or Author List block to a post and set it to show the guest author with its avatar.
3. On `master`, view the block front-end on a high-DPI device (such as mobile or a MacBook Pro) and observe that the avatar image looks blurry—this is because the default image is 72dpi, while the missing `srcset` is supposed to ensure that higher-DPI images are rendered when appropriate. You can also …
=> fix: allow all img tag attributes in avatar output

src/setup/unregister-blocks.js
Unregisters the Jetpack Subscriptions block, which could be easily confused with Newspack's similarly-named and similar-looking block.
Closes `1203451787793554/1203589724907791`.
1. Enable the Jetpack Subscriptions feature as [described here](https://jetpack.com/support/subscriptions/).
2. On `master`, observe that you can add a Jetpack Subscribe block to a post or page.
3. Check out this branch, confirm that you can no longer add the block and that any existing instances won't render in the editor or on the front-end.
=> feat: unregister Jetpack Subscriptions block to avoid confusion with Newspack blocks

src/blocks/author-list/edit.js, src/blocks/author-profile/edit.js, src/blocks/donate/block.json, src/blocks/donate/class-wp-rest-newspack-donate-controller.php, src/blocks/donate/edit/FrequencyBasedLayout.tsx, src/blocks/donate/edit/components/AdditionalFields.tsx, src/blocks/donate/edit/components/AmountValueInput.tsx, src/blocks/donate/edit/components/index.tsx, src/blocks/donate/edit/index.tsx, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php, src/blocks/donate/streamlined/index.test.js, src/blocks/donate/streamlined/index.ts, src/blocks/donate/streamlined/style.scss, src/blocks/donate/styles/editor.scss, src/blocks/donate/types.ts, src/blocks/homepage-articles/utils.ts, src/components/editor-panels.js, src/shared/js/utils.js
Adds additional fields feature to the streamlined Donate block:
_(address and phone fields above are added per-block)_
1. Switch `newspack-plugin` to `feat/donation-additional-fields` branch (https://github.com/Automattic/newspack-plugin/pull/2187)
1. Ensure the site is set up to use Stripe as the Reader Revenue platform and webhooks can reach the site
2. Insert a Donate block on a page. Observe new editor sidebar panel – "Additional data fields"
3. Add some fields
4. Visit the front-end and make a donation, supply values to the additional fields
5. Observe that the fields are added to the Stripe customer metadata – as separate fields, but also the whole group, JSON-encoded, under `_additional_fields` meta key
=> feat(donate): additional fields on the form

includes/class-newspack-blocks-api.php, includes/class-newspack-blocks.php
This PR resolves an issue where WP Users were having their avatars overridden if their ID was the same as a Guest Author's.
The underlying issue was coming from an old fix that looks like it's no longer needed. When the Homepage Posts block was originally developed, guest authors would pick up featured images as avatars when they didn't have one assigned -- this is no longer reproduceable without the fix, so it's safe to remove. 
Closes 1200133283606042-as-1203598624455770
To test this, you need to have a site where a Guest Author and WP User share the same ID. If you don't already have this, you can create it by: 
1. Spin up a new Newspack site (opting NOT to install the demo content)
2. Adding a Guest Author. 
3. Checking the Guest Author's ID -- on a new site, it should be pretty low, …
=> fix: make sure correct avatar is loaded when guests and users share IDs

includes/class-newspack-blocks.php, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.php
Improves performance by removing image sizes which are too large to load from the `srcset` attribute of the `img` tags rendered by the Homepage Posts block. 
1. On `master`,
1. Create a page with some Homepage Posts blocks, make sure all articles have featured images
2. Set one of the blocks to multiple columns
3. Load the page, observe all images are downloaded in the same size (inspect the Network devtools tab)
4. Switch to this branch and rebuild the thumbnails (`wp media regenerate`)
5. Load the page, observe more appropriate image sizes are loaded (this is most visible for a block with a few columns)
=> HPB: filter image sizes based on the maximum image width

CHANGELOG.md, newspack-blocks.php, package-lock.json, package.json, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer.php
v1.60.0 included some major changes to the Donate block's front-end JS as well as the Donate block's HTML markup. However, we've received reports from some end users that suggest they're still seeing an older cached version of the JS, which causes errors and breaks the streamlined Donate block since the JS no longer matches the HTML markup.
This change pegs the asset versions for front-end block JS to the plugin release number, which should ensure that the asset cache is busted every time a new release is deployed. We're already doing this for the front-end CSS, so the change is trivial and it seems to have fixed the issue on at least one site reporting the issues.
Publish a post with a streamlined donate block. In source code, verify that the `donateStreamlined.js` file is enqueued with …
=> fix: use release version number instead of filemtime for JS asset versions

src/blocks/author-profile/editor.scss, src/blocks/author-profile/view.scss
Styles added for the Author Profile block are overriding custom font sizing on paragraph blocks in the editor and on the front-end.
When I originally noticed this I just assumed it was a block editor issue - I wish I had investigated sooner! 
@dkoo and @adekbadek - I'm adding you both as reviews specifically because it looks like [you co-authored the original PR](https://github.com/Automattic/newspack-blocks/pull/947) where this was added. I don't think I've broken anything, but the change to the editor styles -- specifically correcting the containing CSS class so they're getting picked up -- makes me a little nervous, I just want to make sure the other styles there are still working as expected!
See 1203536997639429-as-1203571822380539
1. Set up a page with few paragraph block with …
=> fix: make author block font sizing more specific

includes/class-newspack-blocks-api.php, src/blocks/carousel/edit.js, src/blocks/homepage-articles/edit.js
Fixes a minor edge case bug in the publish/modified dates shown in the Homepage Post block, only in the editor.
Closes 1200550061930446/1203550842074278.
1. In **Settings > General**, set your time zone to something other than UTC, and your date format to a custom format that contains a time, e.g. `F j, Y | g:i a`
2. Publish some posts and note the specific publish date and time.
3. Add a Homepage Posts block to a post and set it to display publish date. On `master`, observe that in the editor, the time shown is in UTC instead of the site's local time zone. Observe also that the time shown on the front-end is in the correct time zone.
4. Check out this branch and confirm that the time in the editor now matches the time shown on the front-end, in the correct local time zone.
=> fix: show HPP dates in correct timezone in editor

src/blocks/donate/styles/view.scss, src/blocks/homepage-articles/view.scss
This is a long explanation for a tiny code change:
**Context:** The RichText fields in Gutenberg allow some minor text formatting -- bold, italic, link, highlights (text and background colours). The highlights use the `mark` tag. 
The `mark` tag typically has some standard styling in HTML (bright yellow by default in most browsers; kind of a mellow-er yellow in our theme). 
In most cases, Gutenberg works around that by adding `style="background-color: rgba(0, 0, 0, 0)"` to `mark` tags that don't have a background colour. 
Publishers have very occasionally been using the highlight option to change the section title of the Homepage Posts block, or the button text colour in the Donate block. 
**The issue:** In both blocks, we're sanitizing the strings on the PHP side using `wp_kses_post`, …
=> fix: remove mark background in Newspack blocks

src/blocks/author-list/block.json, src/blocks/author-list/view.php, src/blocks/author-profile/view.php, src/blocks/shared/author.js
Fixes a type issue that causes custom Author Profile and Author List fields to be displayed on the front-end even if those fields are disabled in the editor. The `string` type of the attribute forces the rendered value to always be truthy.
Closes 1203695565716937/1203810977425531.
1. Add an Author Profile and Author List block to a post. Add guest authors who have custom fields filled out (Job Title, Role, Employer, Phone Number)
2. Uncheck some of the fields and observe that they're hidden in the editor, but not on the front-end.
3. Check out this branch and confirm that only the checked fields are shown in both the editor and the front-end.
=> fix: attribute types for custom author fields

includes/class-newspack-blocks.php
This PR updates the custom excerpt behaviour in the homepage posts block to allow a limited amount of HTML. 
This kind of replicates its original behaviour, which also allowed HTML, but balances that with a limit number of tags, and also making sure the excerpt still respects the excerpt length control. 
The custom excerpts should now allow these tags:
`<em>, <i>, <strong>, <b>, <u>, <ul>, <ol>, <li>, <h1>, <h2>, <h3>, <h4>, <h5>, <h6>, <img>, <a>, <p>`
Closes #888.
1. Apply the PR.
2. Set up a few different posts, so you have a mix of:
* Auto-generated excerpts (no custom excerpts); for these posts add a bit of HTML to the start of the post (like `strong`, `em`, `a`). 
* Custom excerpts of varying lengths; the custom excerpts should have a bit of HTML (`strong`, `em`, `a`), and make sure …
=> Homepage Post Block: allow HTML in custom excerpts

src/blocks/donate/styles/view.scss
Because of z-index order, a Donate block inside a Campaign will be rendered behind it:
This PR fixes that. Note that the **alpha release should be updated with this change**, since it already went out.
1. On `master`, with Newspack set as the RR platform, place a Donate block in an overlay prompt
2. Click "Donate", observe the modal checkout renders behind the prompt
3. Switch to this branch, repeat, observe the checkout modal is rendered in front of the prompt
=> fix(modal-checkout): z-index when used w/ Campaigns

src/blocks/donate/frontend/class-newspack-blocks-donate-renderer.php
Small tweak. 
1. On `master`, with Newspack set as the RR platform and RAS activated (in order to get the modal checkout experience), load a page with a Donate block
2. Inspect network requests, observe that there's a failed request for a `donateCheckoutBlock.css` file (there's no such file)
3. Switch to this branch, reload, observe no such failed request
=> fix: prevent enqueuing non-existent stylesheet

src/blocks/donate/checkout-modal/block.js, src/blocks/donate/styles/view.scss
Adds a body class when the modal checkout is open. This allows for other overlays to hide and allow the checkout to be prioritized in the UI.
1. Checkout this branch and https://github.com/Automattic/newspack-popups/pull/1077
2. Make sure you have reader revenue platform set to Newspack
3. Create an overlay campaign prompt with a donate block
4. Visit a page that renders the prompt, click to donate and confirm the prompt is not visible when the checkout opens
5. Close the checkout and confirm the prompt is now visible again
=> feat(donate): add body class for modal checkout

.hooks/pre-push, composer.json, composer.lock, package.json
- Removes `xwp/wp-dev-lib` dependency
- Adds PHP & JS linting of staged files
- Adds a pre push hook to avoid pushes to master
1. Reinstall git hooks by running `composer install`
1. Make linting-breaking changes to an SCSS, a JS, and a PHP file
2. Try to commit, observe it failing on the three linting errors
3. Fix the errors, commit again, observe it succeeding
=> fix: local git hooks

src/blocks/carousel/edit.js, src/blocks/carousel/view.js
Fixes an editor bug and a front-end bug.
Closes `1204166503564710/1204293714861357`.
Editor bug:
1. Add a Post Carousel to a post in the editor. Change the aspect ratio and/or slides per view options from the defaults.
2. Update the query params for the carousel block—e.g. add a category or tag. On `master`, observe that the block preview updates with the new posts, but the carousel itself becomes non-functional and doesn't show your aspect ratio or slides per view settings until you change another attribute. This is because the Swiper library operates outside of React and doesn't trigger a component re-render by itself.
3. Check out this branch, repeat, confirm that the carousel remains interactive after updating the post query. The fix ties the initialization of a Swiper instance to …
=> fix: bugs for Post Carousel

includes/class-newspack-blocks.php, src/blocks/carousel/edit.js, src/blocks/carousel/index.js, src/blocks/carousel/view.php, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/utils.ts, src/components/query-controls.js, src/types/index.d.ts
[Edited to add all of this after @leogermani's review! Basically copied over some comments about this PR from Slack 🙂 ]
This PR adds the 'Brands' taxonomy as an option for querying to the Homepage Posts and Post Carousel blocks. 
See 1204179187018802-as-1204179187293071
This is a pretty literal set up, just adding the grabbing the Brands taxonomy. We do have an existing issue for allowing more [general custom taxonomy support](https://github.com/Automattic/newspack-blocks/issues/858); this could be a good opportunity to add that by abstracting these changes.  
2. Confirm there are no issues/errors on the front-end or in the editor when you add a homepage posts block.
3. Install and activate the [Multi-Branded …
=> Add brand query support to the blocks

src/blocks/donate/frontend/class-newspack-blocks-donate-renderer.php
Remove the modal checkout feature for the Donate Block from behind the RAS flag. Allows every publisher to use the feature if their RR platform is Newspack (WooCommerce).
1. Check out this branch and confirm your instance doesn't have the RAS flag
2. Make sure your RR platform is Newspack
3. Render a Donate Block and confirm the modal checkout flow works as expected
=> fix: modal checkout outside of ras

.distignore
The following files/folders are currently included in the release archive, which is not ideal:
* `__mocks__/`
* .eslintrc.js
* .npmignore
* .npmrc
* .nvmrc
* .prettierrc
* babel.config.js
* commitlint.config.js
* package.json
* tsconfig.json
* webpack.config.js
This change adds them to `.distignore` so that they don't make it into the release archive.
1. Run `npm run release:archive`
2. Open the resulting newspack-blocks.zip archive
3. Confirm the files/folders listed above are not present
=> Exclude non-dist files from the release archive

src/blocks/homepage-articles/view.scss
The smaller homepage post blocks sizes (1 and 2) get really small on mobile; this PR bumps them up a bit, makes the sizing a wee more standard on desktop (by also tweaking them a bit).
The specific size changes are bolded below:
| DESKTOP     | Before | After | MOBILE     | Before | After |
| ----------- | ------  | ----- | ----------- | ------  | ----- |
|  **Category**   | 12px | 12px  | **Category**   | 10.8px | 10.8px  |
| **Title** | 24px |  24px  | **Title** | 18px |  18px  |
| **Subtitle** | 16px | 16px | **Subtitle** | 14.4px | 14.4px |
| **Paragraph** | 16px | 16px | **Paragraph** | 14.4px | 14.4px |
| **More Link** | 16px | 16px | **More Link** | 14.4px | 14.4px |
| **Post Meta** | 14px | 14px | **Post Meta** | 12.6px | **14.4px** 
| DESKTOP     | Before | After | MOBILE     | …
=> fix: bump up font size on smallest blocks

src/templates/author-profile-card.php
This PR adds a link to the author avatar in the Author Profile and Author List blocks, to line up with the links that are added to the theme in https://github.com/Automattic/newspack-theme/pull/2114. 
In the blocks, these links should be disable-able by turning off the "Link to author archive", just like the link in the author name and at the end of the bio.
See 1200550061930446-as-1204508674733864
1. Apply this PR.
2. Add a couple Author Bio blocks (one with a regular author and one with a guest author), and an Author List block (that's showing at least one regular and one guest author).
3. View the blocks on the front-end, and confirm that the avatars are linked to each author's archive. 
4. Turn off the "Link to author archive" toggle for all blocks, and confirm there are no adverse …
=> feat: adding link to the author bio avatar

includes/class-modal-checkout.php, src/blocks/checkout-button/block.json, src/blocks/checkout-button/edit.js, src/blocks/checkout-button/save.js
Implements support to select a product variation in the Checkout Button.
1. Create a WC subscription product with 2 variations, with one variation having "Name Your Price", and a product without variations (if you don't have any)
2. Draft a page and add the Checkout Button block
3. Select the product with variations
4. Confirm you see the variation selection
5. Change the variation to the one with NYP, configure the price, and save
6. Visit the frontend, click on the button, and confirm the cart contains the product with the correct price
7. Edit the page and change the variation to the one without NYP
8. Save and repeat step 6
9. Edit the page, change the product to the one without variations
10. Save and repeat step 6
=> feat(checkout-button): support product variations

src/modal-checkout/modal.js, src/modal-checkout/modal.scss
Fixes the behavior of the pre-checkout modal for variation selection so it can work with other overlays.
1. While on master, create a content gate with the "Overlay" style and add a Checkout Button block with a variable product for user selection
2. Visit a gated content and confirm that clicking the button renders the modal behind the gate overlay
3. Checkout this branch, refresh the page and confirm the pre-checkout modal replaces the gate modal
4. Close the modal and confirm the gate renders
5. Click again, select a variation, and confirm the checkout modal also renders as expected
=> fix(checkout-button): overlay class for modal stacking

includes/class-newspack-blocks.php, src/blocks/carousel/edit.js, src/blocks/carousel/index.js, src/blocks/carousel/view.php, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/utils.ts, src/blocks/homepage-articles/view.php, src/components/query-controls.js, src/types/index.d.ts
Replaces the hard-coded support to the `brands` taxonomy with a generic support to any registered custom taxonomy.
1. On a site without multi-branded plugin, confirm the homepage block and the carousel block still work as expected
2. Activate the multi-branded plugin
3. Confirm you now see the option to filter by brands in both blocks
4. Confirm the filtering works as expected
5. Confirm that the post shows the correct posts in the front end
6. Confirm the articles have a corresponding `$taxonomy-$term-slug` class in the HTML element
7. Confirm the content of the block is updated on the fly when you make changes
8. Register another custom taxonomy and make sure it works as expected:
7; Also confirm that if the custom taxonomy is not public or if `show_in_rest` is set to `false` it won't …
=> Add custom taxonomies support 

includes/class-modal-checkout.php
Implements the selection of donation billing fields as default for the modal checkout.
This temporary solution should soon be replaced with a logic that also allows customization at the Checkout Button Block level.
1. In your dashboard, visit Newspack -> Reader Revenue, in the "Donations" tab, select only "First Name", "Last Name" and "Email" and save
2. Add a Checkout Button block attached to a custom subscription product
3. Visit the page and confirm the checkout form is only rendering the selected billing fields
4. Visit the regular checkout page (`/checkout`) and confirm all fields are rendered
=> feat(modal-checkout): always use donation billing fields

src/modal-checkout/checkout.scss, src/modal-checkout/templates/checkout-form.php
This PR adds the tax/order details table on the second screen of the modal checkout, if you have taxes enabled. 
It also removes some cruft that came over from the theme's version of this template; the theme had options to hide this information outright, display it with a toggle, or show it all the time. We could also go that route; I was just leery of duplicating the setting, or tying it to something in the current theme if we can avoid it 😬 
I also didn't do much with the styling; I tried to keep with the simplified appearance for this information, but it just felt more cluttered. The table's a straight copy of how this information displays in the theme. 
See 1200550061930446-as-1204773493453836
First enable and set up taxes. 
1. Enable taxes in WooCommerce by following [these …
=> feat: display purchase details in checkout modal when taxes are enabled

src/blocks/donate/edit/FrequencyBasedLayout.tsx, src/blocks/donate/edit/TierBasedLayout.tsx, src/blocks/donate/frequency-based/style.scss, src/blocks/donate/streamlined/style.scss, src/blocks/donate/styles/editor.scss, src/blocks/donate/tiers-based/style.scss
Fixes a minor but annoying bug in which the `RichText` component for the submit button in the editor for Donate blocks doesn't allow spaces if it's nested inside a `button` element. This fix changes the `button` element to a `div` with the same styles, in the editor only. See also https://github.com/Automattic/newspack-newsletters/pull/1202
Closes `1204751246381643/1204483195828260`.
1. On `master`, add a Donate block to a post or page.
2. In both Frequency and Tiers layout options, observe that you can edit the submit button labels but can't add spaces in either case.
3. Check out this branch, repeat step 2 and confirm that you can now add spaces, and that both editor and front-end styles and behavior are otherwise unchanged.
=> fix(donate-block): allow spaces in button label

includes/class-newspack-blocks.php, src/blocks/carousel/edit.js, src/blocks/carousel/index.js, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/utils.ts, src/components/query-controls.js
Change the default behavior of the Homepage Posts and Carousel blocks to include posts in subcategories of the selected categories. Added a toggle under the category picker to switch this behavior off. 
Generally speaking, this is more in line with how Wordpress treats parent/child categories, where a query for the parent category is inclusive of posts in the child categories, and seems more intuitive. 
Closes #207
1. Create a category with one or more child categories (i.e. Food > Tacos)
2. Categorize some posts into the parent category (i.e. Food)
3. Categorize some posts into the child category, but do not explicitly categorize them into the parent category (i.e. Tacos, but not Food)
4. Create a new page and add a Homepage Posts block
5. Under Display Settings, filter by the parent …
=> Change default behavior of Homepage Posts and Carousel blocks to include posts in subcategories 

includes/class-modal-checkout.php, src/modal-checkout/checkout.scss, src/modal-checkout/index.js, src/modal-checkout/templates/checkout-form.php
Implements a dynamic check on whether to render the order details for a modal checkout cart.
The following should render the order details table:
- Cart has an applied coupon
- Taxes are enabled and set to display prices excluding taxes (#1480)
- Cart has more than one item
1. Repeat steps from #1480
2. Disable tax rates and calculations on WC settings (or switch the "display prices" in the "tax" tab to "including taxes")
3. Enable coupons and create a coupon
4. Click on the checkout button and confirm the order details do not render
5. Apply the coupon and confirm the order details rendered with coupon details as the coupon is applied
6. Go through the entire checkout process and confirm the order is placed
=> feat(modal-checkout): render order details under different conditions

src/blocks/donate/edit/index.tsx
The "Additional Fields" panel applies only to the Simplified Donate block, but it's always shown in the block's sidebar in the editor. This fix only shows it if the Reader Revenue platform is Stripe. This condition will have to be changed once we allow the SDB to be used with WooCommerce as well.
1. On `master` or `release`, set your Reader Revenue platform to "Newspack" or anything other than "Stripe".
2. Add a Donate block to a post or page and observe that the Additional Fields panel is available, but that it won't do anything to the front-end render of the block.
3. Check out this branch and confirm the Additional Fields panel is now hidden.
4. Set your Reader Revenue platform to "Stripe", reload the editor, and confirm the Additional Fields panel is available again and lets you add …
=> fix: only show Additional Fields panel when using Stripe platform

src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-frequency-based.php, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
All changes required for the Campaigns Rearchitecture initiative. Also requires https://github.com/Automattic/newspack-plugin/pull/2558 and https://github.com/Automattic/newspack-popups/pull/1192.
There should be no functional changes as a result of this changeset, but it does remove the hidden AMP client ID field which was previously a requirement for the Campaigns Lightweight API, since client ID is no longer needed for Campaigns segmentation APIs.
=> feat: changes required for Campaigns rearchitecture

includes/class-modal-checkout.php, src/modal-checkout/checkout.scss, src/modal-checkout/modal.js, src/modal-checkout/modal.scss, src/modal-checkout/templates/billing-form.php, src/modal-checkout/templates/checkout-form.php
Fixes the modal checkout flow when WooCommerce settings are set to allow account creation and password setting during checkout.
Also adds a few accessibility and style improvements to the modal checkout flow:
- Allows submitting part 1 (billing details) of the form with and "enter" keypress
- Shows the spinner when submitting part 1 of the form, to provide visual feedback that the form is loading another part
- Fully hides the order review table if we're not supposed to see it (if there are no coupons or taxes to calculate), so that we don't see it flash on screen before Woo hides it via JS
Some caveats/discussion points:
- Enabling this account creation flow during checkout allows readers to bypass the RAS account verification flow, as the reader account will be generated with a password …
=> fix: support account creation on modal checkout

src/blocks/carousel/view.scss
This PR reduces the font size of the post title and meta when your slideshow is showing 5-6 slides at once.
It was [previously done for 3-4 slides](https://github.com/Automattic/newspack-blocks/pull/946), and honestly, I have no idea why I didn't do it for these slide counts as well at this time 😐 
See 1200550061930446-1204989622181280
1. Add three post carousels, one with 4 slides at once, one with 5 slides and one with 6.
2. View in the editor and on the front-end - note you can barely see the titles on the 5 and 6 slide blocks:
3. Apply this PR and run `npm run build`.
4. Confirm that the titles are now logically sized for the 5 and 6 slide blocks, and that they truncate to two lines.
5. Scale down your browser window and confirm that the 5 and 6 slide blocks drop to 2 and then 1 slide …
=> fix: reduce post carousel font size for 5-6 slides

src/blocks/carousel/editor.scss, src/blocks/carousel/view.scss
This PR fixes an issue where the Post Carousel slider would be collapsed on the front-end if none of the posts had featured images.
See 1200550061930446-as-1204845439898529
1. Add a post carousel to the editor and change the setting so none of the posts have featured images (this could be adjusting the query, or quickly spinning up 3+ posts without featured images.
2. View on the front-end; note you have the little pagination at the bottom, and nothing more:
4. Confirm your carousel now shows on the front-end.
5. Test a couple different aspect ratio options and confirm the placeholders fill the space on the front-end.
=> fix: make sure carousels without images aren't collapsed

includes/class-newspack-blocks-api.php, src/blocks/carousel/edit.js, src/blocks/carousel/view.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.php
This PR adds the filter `newspack_block_categories` to the post category output used by the Homepage Posts and Carousel blocks, similar to the `[newspack_theme_categories](https://github.com/Automattic/newspack-theme/blob/84319066842b0aea136b1ccab4d5c1f6c3b93592/newspack-theme/inc/template-tags.php#L257)` filter used in the themes.
This addresses a publisher specific request related to how one of our smaller plugins works on single posts but not Homepage Posts, but it could have some other uses!
See 1205368557216686-as-1205459019020490.
2. Add a Homepage Posts and Carousel block to the editor; set the categories to display. Confirm there are no issues. 
3. Set up something to filter `newspack_blocks_categories`, or test this plugin with: …
=> feat: add category filter for the categories in the blocks

includes/class-newspack-blocks.php, src/blocks/carousel/view.php, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.php, src/blocks/video-playlist/view.php, src/templates/author-profile-card.php
Hardens the use of block attribute values across blocks. There should be no unescaped values, and we shouldn't assume that values will be of the expected type.
1. On `release`, add a Posts Carousel, Homepage Posts, and YouTube Video Playlist block to a post or page. Note that for the YouTube Video Playlist block, you'll need to add some YouTube embed blocks to _other_ posts with valid YouTube URLs.
2. On the Posts Carousel block, ensure that you change the aspect ratio, number of slides to show, and the image fit options. In the Homepage Posts block, ensure that the author + avatars are shown.
3. Save the posts with your modified blocks. 
4. Check out this branch.
5. View the blocks in both the editor and the front-end, and ensure that all function as expected in both contexts with no …
=> fix: harden usage and output of attribute values

includes/class-newspack-blocks.php
Fixes a well-hidden PHP error due to an undefined variable. It looks like PHP in some cases is silently casting this undefined `$children` variable to an array, suppressing the warning unless you invoke the variable before the first `$children[] =` definition.
1. On `release`, create two categories that are children of another category and assign to some posts. Add `error_log( print_r( $children, true ) );` to right before [this line](https://github.com/Automattic/newspack-blocks/blob/master/includes/class-newspack-blocks.php#L674).
2. On another post, add a Homepage Posts block with the "include subcategories" option on and assign it to the parent category. Observe a PHP warning: `PHP Warning:  Undefined variable $children in /newspack-repos/newspack-blocks/includes/class-newspack-blocks. …
=> fix: undefined variable error

src/blocks/checkout-button/edit.js, src/modal-checkout/modal.scss
Increase the pagination limit while fetching product variations in the Checkout Button block and the overflow for the variation modal when users are allowed to select a variation before checkout.
1. While on the `release` branch, create a product with 20 variations
2. Draft a new page and add a "Checkout Button" block
3. Select the new product, uncheck the "Allow the reader to select the variation before checkout." option, and confirm the dropdown below only renders 10 variations
4. Check the option again, save, visit the page, click the button, and confirm the variation list exceeds the container bounds
5. Check out this branch, refresh the page, click the button, and confirm the variation modal renders a scrollbar
6. Edit the page, uncheck the "Allow the reader to select the variation …
=> fix(checkout-button): handle 10+ product variations

includes/class-newspack-blocks.php
Co-Authors Plus author terms for WP users match the WP user's `user_login` at the time of the WP user's creation. The `user_login` can't be updated in WP once the user is created, so it assumes that these values will always match. But in production environments, we've seen cases where this is not the case: specifically, the `user_login` and `user_email` differ, but the CAP term name matches the `user_email` instead of the `user_login. This seems to be possible only through direct DB manipulation, so I suspect this is happening from data migration. I haven't been able to recreate this scenario in a test site using WP admin, so the risk of it happening seems low for sites that haven't run into it, but it can be a serious issue with no workaround for sites that are affected.
1. On `release`, …
=> fix: query for CAP terms

src/blocks/donate/edit/index.tsx, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
Adds support of "once" frequency to tiers-based layout.
Closes 1200550061930446-as-1205559648883658/f
1. On `master`, insert a Donate block and set it to Layout of "Tiers"
2. In Reader Revenue wizard, Donations tab, Suggested Donations section, disable monthly and annual donation tiers, while having "Tiered" donations option selected
3. Visit the page with the Donate block, observe it not rendering
4. Switch to this branch, observe the block is rendering (with only the "once" tier)
=> fix(donate): allow "once" in tiers-based layout

includes/class-newspack-blocks.php
1200550061930446-as-1204938638613364
Implements a recursive check on existing "specificPosts" to apply deduplication logic. The existing approach only loops through top-level blocks, not considering blocks inside columns or groups.
1. While on the master branch, add a 3-column block
2. For each column, add a Homepage Posts block rendering 1 post
3. For the second block, set it to a specific post and select the post that is being rendered on the first column
4. Save and visit the post
5. Confirm you get the first post duplicated
6. Check out this branch, refresh, and confirm the deduplication rule is correctly applied
=> fix(homepage-posts): check existing "specific posts" recursively for deduplication

includes/class-modal-checkout.php, src/blocks/checkout-button/block.json, src/blocks/checkout-button/edit.js, src/blocks/checkout-button/save.js, src/modal-checkout/modal.js, src/modal-checkout/templates/checkout-form.php
Implements an optional link to click after the transaction is complete on the modal checkout.
The button supports linking to the page referrer (which falls back to the current page URL if the referrer is empty) or a custom URL.
1. Checkout this branch and https://github.com/Automattic/newspack-theme/pull/2180
2. Add a checkout button to a page
3. Select the option to go to the Referrer after purchase and add a button label
4. Add a link to this page in the site menu
5. Visit an article
6. Go to the page via the menu link
7. Click the button and buy the product
8. Confirm the button shows up in the thank you message and link back to the article you were seeing
9. In a new tab, copy and paste the page URL directly into the browser so you get no referrer
10. Make the purchase again and …
=> feat: add option for a button after checkout

src/modal-checkout/templates/checkout-form.php
#1516 introduced a regression by hiding the order details wrapper in the template. Since #1485 this has been [handled dynamically](https://github.com/Automattic/newspack-blocks/blob/d1dfb2ae700dd8ceea001d2c0c71690b405b99f3/includes/class-modal-checkout.php#L516-L535), due to the dynamic nature of WC cart template fragments. Adding or removing coupons changes whether the order details should be rendered or not.
This PR removes the "hidden" class from the template so the fragment hook can determine whether to render details.
1. While on the release branch, checkout a product with the checkout button block and apply a coupon
2. Confirm the coupon doesn't seem applied
3. Check out this branch, try again, and confirm the UI updates and the coupon is applied
=> fix: allow order details wrapper to render

includes/class-newspack-blocks.php, src/blocks/homepage-articles/block.json, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/store.js, src/blocks/homepage-articles/templates/articles-loop.php, src/blocks/homepage-articles/utils.ts
1205451924709229-as-1205631504130139
Implements a toggle to allow a Homepage Posts block to be excluded to deduplication logic.
**Without deduplication, the block will not account for previously queried posts and will also not have their queried posts as part of the exclusion for the following blocks.**
---
| Default deduplication | With "Block 2" opted-out |
| --- | --- |
| <img width="851" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/29508c67-7361-4b2a-8f15-6e4423fa4cc2"> | <img width="846" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/4b58a3d9-88b2-412d-974a-e2fbf01d38b3"> |
Closes #258.
1. Check out this branch and draft a new page with 3 Homepage Posts block, similar to the image above
2. Toggle the "Use deduplication …
=> feat(homepage-posts): support deduplication toggling

src/blocks/donate/frequency-based/index.ts
Suppose a reader inputs an invalid value to the "Other" tier option and selects any other tier. In that case, the form will fail to submit due to the browser's native validation for the number input.
This PR implements a reset to the input whenever the tier selection changes, preventing the value from failing form validation.
1. While in the release branch confirm the issue by visiting a page with a frequency-based donate block
2. Input a value lower than the allowed minimum (default is $5)
3. Switch to a suggested value tier and confirm you're not able to continue donating
4. Switch back to "Other", place a valid number, switch back to the suggested option and confirm you're able to continue
5. Switch to this branch, repeat steps 2 and 3, and confirm you are able to continue
6. Close the …
=> fix(donate): reset "other" value when switching tiers

includes/class-modal-checkout.php, src/modal-checkout/checkout.scss, src/modal-checkout/templates/form-login.php
Adjusts some logic in the WooCommerce checkout flow when using the modal checkout. In the scenario where a donation is made while logged out but using an email address that's already associated with a custom account, we don't want to show the login prompt on the thank you step—instead, we want to show the order summary like we do for new email addresses or when already logged in.
1. On `release`, while not logged in, make a donation using an email address that's already associated with an existing reader account.
2. On the thank you step after the successful transaction, observe that instead of an order summary, there's a message to "Please log in to your account to view this order" and a login form.
3. Check out this branch, repeat with a new donation and the same email address. This …
=> fix: match thankyou template when using existing customer email

languages/newspack-blocks-de_DE.po, languages/newspack-blocks-es_ES.po, languages/newspack-blocks-fr_BE.po, languages/newspack-blocks-pt_PT.po, languages/newspack-blocks.pot, newspack-blocks.php
Updates some lingering legacy URLs throughout the code. All instances of newspack.pub or newspack.blog should be newspack.com
No functional changes.
=> chore: newspack.pub > newspack.com

src/modal-checkout/templates/form-login.php
#1550 introduced a custom template to force the "order summary" to appear in the thank-you template when completing a transaction using an email address that's already registered on the site. However, this custom template inherited some logic which only exposed the order's email address if it matches the currently logged-in user. Since this template is only shown in scenarios where a non-logged-in user is completing a transaction using an existing account's email, that condition will never be satisfied, so this PR removes the logic and always shows the email address in the order summary. This should be safe because we're checking the order key before showing order summary details to ensure that the order details are only shown during the course of a checkout flow involving that exact …
=> fix: always show email address for order summaries

includes/class-modal-checkout.php
Updates WC's variation-related methods.
1. Create a product with variations
2. Add a Checkout Button block to a page and select the product
3. Load the page with the button, observe warnings about deprecated methods used being logged
4. Switch to this branch, observe no warnings
=> fix: update WC's variation methods

includes/class-modal-checkout.php, src/modal-checkout/checkout.scss, src/modal-checkout/modal.js, src/modal-checkout/modal.scss, src/modal-checkout/templates/form-login.php, src/modal-checkout/templates/thankyou.php
Adds post-checkout newsletter signup options:
1. Switch `newspack-plugin` to branch from https://github.com/Automattic/newspack-plugin/pull/2707
1. Switch `newspack-theme` to branch from https://github.com/Automattic/newspack-theme/pull/2188 
1. Ensure that the Newsletters provider is configured and some lists are active in Engagement wizard -> Newsletters
1. With "Newspack" set as the Reader Revenue platform, make a donation using the checkout modal
3. Observe that after the checkout is successful, the chosen newsletter lists are presented
4. Select some of them and click "Continue", observe a success message
5. Verify that the email used has been added to the list(s)
6. Set a `NEWSPACK_DISABLE_POST_CHECKOUT_NEWSLETTER_SIGNUP` environment variable to `true` and observe that now the …
=> Modal checkout – post-checkout newsletter signup

includes/class-modal-checkout.php, src/blocks/checkout-button/block.json, src/blocks/checkout-button/edit.js, src/blocks/donate/block.json, src/blocks/donate/edit/index.tsx, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-frequency-based.php, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php, src/blocks/donate/types.ts, src/components/redirect-after-success.tsx, src/modal-checkout/checkout.scss, src/modal-checkout/modal.js, src/modal-checkout/templates/thankyou.php
1. Implements the post-checkout button (https://github.com/Automattic/newspack-blocks/pull/1521) for the Donate block. 
2. Changes how the post-checkout button works:
1. It will be displayed at all times, instead of optionally
2. By default, the post-checkout button will say "Continue browsing" and close the checkout modal on clicking
3. Two other options are, as before, to go to previous page (the `referrer`) or go to custom URL
1. Switch `newspack-plugin` to `feat/donate-post-checkout-button` (https://github.com/Automattic/newspack-plugin/pull/2719)
4. Add a Donate block to a page, configure it to display a button in the "After Purchase" sidebar settings panel
5. Complete a transaction, observe the button is displayed (as in https://github.com/Automattic/newspack-blocks/pull/1521/)
6. …
=> Changes to button-after-success feature 

src/modal-checkout/templates/checkout-form.php
There's an address validation plugin out there, which relies on checkout `inputs` having `id` attributes and on the `state` input being a `select`, as on the native WC checkout page. This PR updates the code so the hidden inputs are more in line with the native checkout.  
1. In Newspack -> Reader Revenue wizard -> Donations tab, check all the address fields in "Billing Fields" settings
2. Use the modal checkout and input a full address on checkout
3. Use the checkout again, this time the "Billing details" section should present the address, instead of the edit form
4. Inspect the source, observe a series of hidden inputs below the address, verify the values match the address
=> fix(modal-checkout): add id attributes to hidden inputs; add select

includes/class-modal-checkout.php
Adds modal checkout handling for Apple Pay (and other non-redirect-based payment flows).
1. On `master`, configure the WC Stripe Gateway to use Apple Pay (`/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`) and enable reCAPTCHA v3 in Connections wizard
3. Visit the site using an Apple device* and make a donation** via Apple Pay using the modal checkout
4. Observe the donation cannot be completed
5. Disable reCAPTCHA v3 in Connections wizard
6. Observe that after the successful transaction, the modal view presents a full "order received" page (with header and footer), not the slimmed-down version of a WC page
7. Enable reCAPTCHA v3 again 
8. Switch to this branch
9. Observe the Apple Pay success flow ends up the same as the CC success flow  
\* Either via an …
=> feat(modal-checkout): handle non-redirect-based flow (e.g. Apple Pay)

includes/class-modal-checkout.php
Expose `\Newspack_Blocks\Modal_Checkout::is_modal_checkout` method, so it can be used by other code, https://github.com/Automattic/newspack-plugin/pull/2695#discussion_r1379086313.
=> feat: expose is_modal_checkout method

src/blocks/homepage-articles/edit.js
Changes the copy and reverse the toggle for the deduplication logic toggle on the Homepage Posts block (first introduced in https://github.com/Automattic/newspack-blocks/pull/1543):
| Before | After |
| --- | --- |
| <img width="278" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/a4bd8d62-2d03-4617-992b-a50bb9d01d57"> | <img width="279" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/8375c88c-a291-4cbd-bba6-d00ed4f8dc62"> |
1. Draft a new page and add 3 Homepage Posts block
2. On the 2nd block, toggle "Allow duplicate posts" on and confirm it renders the contents from the first block and the 3rd block renders the content that was previously being rendered in the 2nd block
3. Save, visit the page and confirm the same posts also …
=> fix(homepage-posts): change copy for deduplication block option

src/templates/author-profile-card.php
This PR adds some checks to the Author Profile and Author List block output, so it doesn't display warnings when the Newspack Plugin is deactivated. 
See: 1200550061930446-as-1205176822910070
1. Add an Author Profile and Author List block to a page; publish.
2. Navigate to WP Admin > Plugins, and deactivate the Newspack Plugin.
3. View your page on the frontend, and note the warnings (example: `Warning: Undefined array key “shownewspack_role” in /srv/users/user8bdc4063/apps/user8bdc4063/public/wp-content/plugins/newspack-blocks/src/templates/author-profile-card.php on line 31`).
4. Apply the PR.
5. Confirm the warnings are gone.
6. Reactivate the Newspack Plugin.
7. Edit one of the authors the block displays and populate one of the Newspack fields (Employeer, Job Title...).
8. View the …
=> fix: add checks for Newspack plugin

includes/class-newspack-blocks-api.php, src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php, src/blocks/homepage-articles/edit.js, src/blocks/homepage-articles/editor.js, src/blocks/homepage-articles/editor.scss, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/view.php, src/blocks/homepage-articles/view.scss
Inlines the critical parts of CSS needed by the Homepage Posts Block, in order to get rid of [layout shift](https://web.dev/cls/) happening when the file-based CSS stylesheet is loaded. 
To demonstrate, here's a recording of a (throttled) page load on `master`:
And here's how it looks like on this branch:
If this strategy proves effective in production environment, it can be enhanced by moving more of the static styles from `view.css` to the dynamically created inline stylesheet. 
1. Create a page with some instances of the Homepage Posts Block, with different type scale settings and images shown
2. Load the front-end, observe the styles are applied just like on `master`, only faster*
\* use DevTools' Network speed throttling to observe it better
=> Inline HPB styles in a style tag

src/modal-checkout/checkout.scss
Fixes a regression introduced by #1572
⚠️ The regression is part of the latest alpha release, so this change should also be merged into alpha. 
1. On `master`, trigger the modal checkout for a one-time donation
2. Observe the "Place order" button at the second step is not 100% wide
3. Switch to this branch, observe it is
=> fix(modal-checkout): place order button width

includes/class-modal-checkout.php
Updates the "Place order" text in modal checkout to "Donate now".
⚠️  This is an alpha-hotfix, merging to `alpha`.
1. Test with a one-time and recurring donation via modal checkout – the CTA on the second step should always say "Donate now"
2. Use the regular checkout, confirm the corresponding button says "Place order" for regular items and "Sign up now" for subscription items
=> feat(modal-checkout): update "place order" text to "donate now"

src/blocks/checkout-button/block.json, src/blocks/checkout-button/edit.js, src/blocks/checkout-button/save.js, src/blocks/checkout-button/view.scss
This PR adds a 'width' control to the Checkout Button block, so you can set it to 25, 50, 75, or 100% of the available space. 
See 1200550061930446-as-1205525005864243
2. Add a Checkout button to the editor. Click it and confirm that there's a 'Width settings' panel under the 'Settings' tab (which, oddly, is the same location as the Button block - it's not under the Styles tab). 
3. Try changing the width to one of the different settings; confirm that it's applied in the editor and on the front end. Repeat with all of the options.
4. When done, click again on the selected option to clear the width and confirm the button returns to the default width (the width of its text label). Publish to confirm that this is the case on the front-end, too.
=> feat: add width control to the Checkout block

.phpcs.xml.dist, composer.json, composer.lock, includes/class-newspack-blocks-api.php, includes/class-newspack-blocks.php, src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php, src/blocks/homepage-articles/templates/article.php, src/blocks/homepage-articles/templates/articles-list.php, src/blocks/homepage-articles/view.php, tests/bootstrap.php
Updates the lint-related Composer packages to handle PHP 8. 
After upgrading to PHP 8, running the linting commands (`./vendor/bin/phpcs`, `./vendor/bin/phpcbf`) was erroring out. This was resolved by updating these packages. Along with the updates, some code had to be refactored – some of it automatically with `phpcbf`, some manually.
1. Smoke test code changes, everything should behave as before
2. Ensure the lint-php job is passing on CI
3. For a good measure, run the linting commands locally to see if there are no issues with local development
=> Chore: update phpcs to handle PHP 8

src/modal-checkout/templates/thankyou.php
Adds "Item: <item-name>" line to modal checkout success state, so the donor can double-check what they've paid for.
1. Complete a donation using modal checkout
2. Observe the item name is displayed (e.g. "Donate: Monthly")
=> feat(modal-checkout): display item name on success

src/blocks/homepage-articles/view.php
This PR updates existence checks to prevent `Attempt to read property "name"|"term_id" on bool` warnings.
Closes p1700077484817269/1700025334.541069-slack-CKZHG0QCR
Follow the testing instructions on this [PR](https://github.com/Automattic/newspack-blocks/pull/1528) to check for regressions.
=> Update existence checks in newspack_blocks_format_categories

src/blocks/homepage-articles/view.php
The inline styles for the Homepage Posts block are not rendered right after `.entry-content` as documented in the code. They are rendered alongside the first rendered HPP block. This can cause containers that leverage pseudo classes like `:first-child` or `:last-child` to not behave as expected, since the style tag can get picked up.
| Before | After |
| --- | --- |
| <img width="1255" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/17e6b0e2-db14-4f65-a801-a2b8669b2def"> | <img width="1257" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/01e112a5-6bd6-40f2-a138-29218e379bd1"> |
This PR changes the placement for the inline CSS so it's printed inside the block container. The improved CLS implemented in the original PR (#1548) should …
=> fix(homepage-posts): placement for inline styles

includes/class-modal-checkout.php
The current modal checkout template is not rendering valid markup. It's currently missing the doctype, html, head, and body tags. This PR ensures the template outputs valid markup and also changes the output so it always renders WC's `[woocommerce_checkout]` shortcode instead of the contents of the checkout page.
This change is to make sure that a checkout template using the new [WooCommerce blocks](https://woo.com/checkout-blocks/) never renders in the modal checkout, since we're not expecting to support it at the moment.
1. Checkout this branch and go through the modal checkout flow using the donate block
2. Confirm you're able to complete the flow without issues
3. Edit the checkout page to use the new WooCommerce checkout blocks
4. Go through the flow again and confirm the modal …
=> fix: modal checkout template markup and shortcode

includes/class-modal-checkout.php
Process the checkout request in an earlier hook for improved performance. Also added a guard clause to bail on `is_admin()` since `wp_loaded` is a higher scope hook executed on every load. 
1. Checkout this branch and go through the modal checkout flow from a Checkout Button block
2. Confirm you are able to purchase without issues
=> perf(modal-checkout): process checkout request earlier

includes/class-modal-checkout.php, src/modal-checkout/checkout.scss, src/modal-checkout/templates/empty-order-details.php
Improves the performance of the modal checkout by skipping unnecessary markup. 
It also fixes a PHP Notice caused by changes in #1601. 
1. On `master`, start a new session (or clear the cookies)
2. Trigger the modal checkout, copy the URL of the modal's iframe and visit it directly*
3. Observe the issues (deactivate Perfmatters if active, because it will make it more difficult to inspect):
1. [Complianz](https://wordpress.org/plugins/complianz-gdpr/) cookie banner is displayed in the iframe
2. reCaptcha badge, too
3. Newspack Ads' JS is loaded (if configured) 
4. Newspack print styles are loaded
5. GA is loaded 
6. If Jetpack "WooCommerce Analytics" module is active**, a whole bunch of React and Redux JS is loaded
7. WP mediaelement scripts and styles are loaded
8. PHP Notice is logged, …
=> feat: improve performance of modal checkout

includes/class-modal-checkout.php, src/modal-checkout/templates/checkout-form.php
With Newspack sites moving from PHP 7.4 and 8.0 to 8.1, we should update all instances of the constant `FILTER_SANITIZE_STRING`, which is now deprecated. This PR updates `class-modal-checkout.php` and `checkout-form.php` by replacing `FILTER_SANITIZE_STRING` with `FILTER_UNSAFE_RAW`.
1.
2.
3.
=> Replace FILTER_SANITIZE_STRING

src/blocks/donate/tiers-based/view.ts
Queuing this up for release early next week! 
This PR updates the logic used to toggle the tab status (active or inactive) in the tiers view of the Donate block.
Originally the tabs, when one was selected, would all toggle the active CSS class -- meaning either one or two would appear active, and they wouldn't necessarily line up with the actual active tab. This was only on the front-end -- it worked as expected in the editor. This PR updates it to check for current status and update; if there's a more elegant way to do this, I'm all ears! 
See 1200550061930446-as-1206029652902709
1. Add a Donate block to your test set, and change the Layout to Tiers; make sure the block is showing all three tabs (One time, Monthly, Annually). Publish you page.
2. View on front end, and click between the …
=> Donate Block: Update selected tier behaviour

src/blocks/homepage-articles/view.php
If the HP block is empty, and it happens to be the first one on the page, the inline styles won't be printed. 
1. Set up a page with at least two HP blocks – the first one should be empty*
2. For the second block, choose a large type scale
3. On `release`, observe that the inline styles are not applied – the type scale is not reflected on the frontend 
4. Switch to this branch, observe the styles are applied
\* e.g. set it to display posts from a category with no posts
=> fix(homepage-posts): handle empty block when printing inline styles

src/modal-checkout/checkout.scss
Tweaks the alignment of the "Save payment information to my account for future purchases." checkbox.
| Before | After |
| --- | --- |
| <img width="543" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/8a705f2f-3fee-4854-aa02-30aebd03d349"> | <img width="541" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/806bdb7d-782c-415b-96e6-0bd118500b1d"> | 
Checkout this branch, go through the modal checkout flow, and confirm the checkbox is not misaligned.
=> fix(modal-checkout): align Stripe's "save payment" checkbox

includes/class-modal-checkout.php
Moves a logic that is [currently placed behind RAS](https://github.com/Automattic/newspack-plugin/blob/fcad059abbe0314ba8a6f3eaaf92d5c96350e248/includes/reader-activation/class-reader-activation.php#L89-L90) but is designed for the modal checkout.
If an anonymous purchase is made for a registered email, it should be attached to that account regardless of them being authenticated.
1. Checkout this branch and https://github.com/Automattic/newspack-plugin/pull/2781
2. Make sure RAS is toggled off (`$ wp option delete newspack_reader_activation_enabled`)
3. Disable the "Allow customers to create an account during checkout" option from the "Accounts & Privacy" section of WC:
4. Go through the regular checkout flow anonymously and use an existing email
5. Confirm the order goes through and in …
=> feat(modal-checkout): allow anonymous purchase for registered email

src/blocks/author-profile/class-wp-rest-newspack-authors-controller.php
Fixes an issue with CAPs linked authors in the Hompepage posts block
1. Create a user and a guest author that share the same name
2. Create one post authored by each of these users
3. Edit the guest author and link them to the user with the same name
4. On `master` add a new Homepage block to a page and search for the author by it name in the "authors" filter box
5. Confirm you get two results
6. Checkout this branch
7. Confirm you now get only one result
8. Confirm the posts are queried correctly and you get both posts rendered in the block
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204817890713184
=> fix: avoid duplicity with linked guest authors

includes/class-modal-checkout.php
Show order details table on the modal checkout if the cart contains fees.
Instructions at https://github.com/Automattic/newspack-plugin/pull/2820
=> fix(modal-checkout): show order details table with fees

includes/class-newspack-blocks.php
Allow to customize the arguments for WP_Query created by build_articles_query using the new filter 'newspack_blocks_build_articles_query'.
Our websites make heavy use of the Homepage Articles block on the Homepage and related type of pages. This results in a significant amount of slow WP_Query calls by the Homepage Articles blocks in case of a cache invalidation caused by new post publications or content changes to these pages. The underlying reason for the slow queries is the default usage of SQL_CALC_FOUND_ROWS by Wordpress. As this seems not to be necessary for a Homepage Articles block, it would be usefull to set the argument 'no_found_rows' for WP_Query in such situations. 
But as such a change might break other existing code in the plugin or third party usage, the best way seems to …
=> Add filter when building WP_Query arguments

CHANGELOG.md, includes/class-modal-checkout.php, newspack-blocks.php, package-lock.json, package.json, src/blocks/author-profile/class-wp-rest-newspack-authors-controller.php, src/blocks/donate/edit/FrequencyBasedLayout.tsx, src/blocks/donate/edit/index.tsx, src/blocks/donate/frequency-based/index.ts, src/blocks/donate/frequency-based/style.scss, src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-frequency-based.php, src/blocks/donate/styles/editor.scss, src/blocks/donate/styles/style-variations.scss, src/blocks/donate/styles/view.scss
=> Release Jan 08

includes/class-modal-checkout.php
Fixes some issues with checkout when using express checkout methods (also called "payment requests" in Stripe terminology) in modal checkout. Our `is_modal_checkout` method isn't recognizing express checkout requests as being triggered by modal checkout, so there can be mismatches in the data we're providing via modal checkout and what WooCommerce would expect, thinking the checkout requests is happening via a standard checkout flow. This could affect any behavior we customize for the modal checkout, including:
- Required billing fields (e.g. if you partially set up Google Pay but don't add an address, and your site is set to not collect address fields during modal checkout, Woo might still throw errors about missing required address fields).
- Behavior we enforce to allow guest checkout …
=> fix(modal-checkout): treat express checkouts as modal checkouts

src/modal-checkout/templates/checkout-form.php
Fixes an issue in the checkout modal when the "Country/Region" field is disabled, but the State field is enabled.
In those cases, in the first step of the modal, users will see the States selectbox and select a state, but in the second step, the hidden select field will not have the correct states loaded.
The end result is that the donation submission will either fail or assign the user to a wrong state (AF, which is the Afghanistan code, the first option in the select).
1. On `trunk` go to Newspack > Reader Revenue. Enable the state and Address field, but disable "Country"
2. As an anonymous reader, try to make a donation. Confirm you can select the state.
3. On the second step of the donation modal, inspect the modal and confirm you see the hidden states SELECT listing countries instead …
=> fix: properly handle states when Country field is disabled
