- src/blocks/donate/edit.js
- src/blocks/donate/view.php
Related https://github.com/Automattic/newspack-plugin/issues/242
[See the companion PR for more info and testing instructions.
](https://github.com/Automattic/newspack-plugin/pull/243)
> Update 'once' donation price logic

- .gitignore
- newspack-blocks.php
- package-lock.json
- package.json
Adds a release script to the repo. 
1. Execute `npm run release:archive`
2. Observe a zip archive has been created in `assets/release/`. 
3. Verify the archive installs properly.
> Release Script

- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/index.js
- src/blocks/homepage-articles/query-controls/index.js
- src/blocks/homepage-articles/view.php
The refactoring work already has [tag filtering built in ](https://github.com/Automattic/newspack-blocks/blob/14f22b05dc726b759ea0a12f01914a8830fe47d8/src/components/query-panel/index.js#L70-L76) however we've gotten immediate requests for this so it makes sense to add the feature to the current Newspack Homepage Articles Block.  
Adds a tag filter dropdown to the block.
Closes https://github.com/Automattic/newspack-blocks/issues/89.
1. Checkout the branch, run `npm run build:webpack`
2. Add Newspack Homepage Articles block to a post  or page.  
3. In the sidebar, observe tags dropdown. This should show all available tags, up to a maximum of 50.
4. Select a tag, observe that the contents of the block is filtered to posts bearing that tag.
5. Publish the post and verify that the same …
> Tag Filtering

- src/blocks/homepage-articles/view.scss
* Move the caption to the bottom right
* Make sure it's only on 1 line (otherwise don't overflow, use ellipsis instead)
* Have the font italic with some opacity to distinguish it from the excerpt/title/meta
Closes #152 .
__Before:__
__After:__
1. Apply this PR and run `npm run build:webpack`
2. Have a bunch of articles set to background image (make sure they have a featured image!)
3. Display the caption (So make sure their featured images have captions!)
> Articles Block: Fix position of the caption when using image as background

- src/blocks/homepage-articles/view.scss
This PR makes sure the category link that you can display with the article block will inherit the block's custom text colour. Otherwise, you can't make sure it's visible against a darker background. For example, here's the block inside of a group block with a dark grey background; the text on the article block is set to white, but the category is still dark grey:
**Before:**
**After the PR:**
1. In the editor, set up a group block and give it a dark background.
2. Insert an Article Block inside of that group block; change the text colour to white, and set the block to 'Show Categories'.
3. Note the appearance of the categories in the editor.
4. Publish the changes and note the appearance of the categories on the front-end -- they should have little to no contrast against the group block. …
> Article Block: Make sure categories inherit the article block's custom text colour

- src/blocks/donate/view.scss
Make the tabs more subtle and have the block more inline with the theme.
__Before:__
__After:__
1. Check a post/page with the donation block. How does it look?
2. Switch to this branch and run `npm run build:webpack`
3. Check the same page and notice the difference. Does it look better?
> Update the donate block view style

- src/blocks/donate/view.php
This PR adds a filter for modifying the HTML output of the Donate block. It's necessary for https://github.com/Automattic/newspack-nrh-checkout/issues/2
1. Verify this PR doesn't break the Donate block output or cause fatal PHP errors. Everything should work as normal.
> Add filter for changing Donate Block HTML

- src/blocks/homepage-articles/index.js
This PR adds full and wide alignment support to the article block (thanks for the suggestion, @thomasguillot!)
There is a theme PR coming shortly that fixes the issue where the 'full' align block gets cut off on the edges.
Edited to add: the related theme PR is https://github.com/Automattic/newspack-theme/pull/477.
2. Add two article blocks to the editor; switch one to align 'wide' and one to align 'full'
3. Confirm the block is displaying as 'wide' and 'full' on the front-end.
> Article Block: Add full and wide alignment support 🌟

- class-newspack-blocks-api.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/templates/articles-list.php
- src/blocks/homepage-articles/templates/articles-loop.php
Fixes phpcs errors when trying to merge NHA to wp.com
See D36505-code
> Fixes for TC's phpcs

- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
> Articles Endpoint: Exclusion Query

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/components/query-controls.js
Adds a `Tag Exclusion` filter that allows excluding posts by tag. This  is useful for complex curation scenarios where it may be desirable to limit specific posts from appearing in instances of the block. Tag Exclusion feels like an advanced feature, so the field is not initially visible. A small `Show Advanced Filters` button can be clicked to reveal it.
cc: @thomasguillot for assessment  of the "Advanced Filters" toggle UI.
1. Add the block to a Page, note which Posts are shown.
2. Edit one or more of the Posts, add the tag "exclude", and republish.
3. Back in the Page with the block, click "Show Advanced Filters", then type "exclude" in the Excluded Tags field. 
4. Observe that the Post(s) with that tag are no longer visible in the block.
5. Publish the Page. Verify the tagged Posts …
> Tag Exclusion

- src/blocks/homepage-articles/view.scss
This PR cleans up some odd spacing when you've floated your images left or right, but also have them stacked on mobile.
1. Add a handful of article blocks to a page with these settings:
a. Images floated left, stacked on mobile
b. Images floated right, stacked on mobile
c. Images align top (default)
d. Images floated left, not stacked on mobile.
2. Save and publish; confirm that at least one article per section has an image.
3. Shrink down the browser window to 'mobile' width, and note the spacing when the images stack -- images floating right have a right margin that pushes them right, and the vertical spacing between images on bot left and right floated images is a bit tight:
4. Apply the PR and run` npm run build`
5. Confirm that the above issues are fixed:
6. View all the blocks you …
> Homepage Posts: Correct spacing when floated images are stacked on mobile

- newspack-blocks.php
Bumps the version number to 1.0.0-alpha.21, updates a few other plugin text fields.
> Version Bump

- .stylelintrc
- package-lock.json
- package.json
- src/block-styles/core/columns/editor.scss
- src/block-styles/core/columns/view.scss
- src/block-styles/core/group/editor.scss
- src/blocks/carousel/editor.scss
- src/blocks/carousel/view.scss
- src/blocks/donate/editor.scss
- src/blocks/donate/view.scss
- src/blocks/homepage-articles/editor.scss
- src/blocks/homepage-articles/view.scss
- src/shared/sass/_mixins.scss
- src/shared/sass/_variables.scss
After #291 set up linting configuration, now it's time to fix the  existing SCSS files. 
These changes are in most part autofixes (spacing in parentheses, etc.)
1. Look at the code
2. Look some more
3. If it's all innocuous refactoring, then we're cool
> Fix SCSS after linting was set up

- src/block-styles/core/columns/editor.scss
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/view.js
- src/components/query-controls.js
Small fixes - variable names, jsdoc, key attribute in one case
1. check if all changes are refactoring only
2. run `npm run lint:js` - or just look at the [CI output](https://app.circleci.com/github/Automattic/newspack-blocks/pipelines/6ce724c5-f003-4fbe-9f00-840247855fad/workflows/f60ea9da-5010-42a1-9918-df12240b9f96) 👇 ;)
> Fix linting errors

- .circleci/config.yml
- commitlint.config.js
- composer.json
- package-lock.json
- package.json
This configures commit linting and semantic-release:
**Commit linting** simply enforces a [structure of a commit message](https://semantic-release.gitbook.io/semantic-release/#commit-message-format), in this case to adhere to [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format)
**semantic-release** is configured to run when anything lands on `release` branch. In such event, the following should happen (if there are any commits that should trigger a release!):
1. a new version number will be determined
1. a zipped release archive  will be created (`npm run release:archive`)
1. `CHANGELOG.md` file will be updated (or generated)
1. version in `package.json`, `package-lock.json`, and `newspack-blocks.php` will be updated …
> CI: configure semantic release for automated releases

- src/blocks/carousel/edit.js
- src/blocks/carousel/editor.scss
- src/blocks/donate/edit.js
- src/blocks/donate/editor.scss
- src/blocks/donate/index.js
- src/blocks/donate/view.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/editor.scss
- src/blocks/homepage-articles/view.scss
- src/shared/sass/_placeholder.scss
> Weekly Release

- composer.json
- composer.lock
So that prettier is handled when linting JS
> Use newer version of xwp-dev-lib

- src/blocks/homepage-articles/view.php
When a guest author from Co-Authors Plus plugin is assigned to an article, the link on their author name points to `url.com/author` rather than `url.com/author/author-name` -- clicking on it will bring you to the single post or a 404 error rather than the author archive.
This PR fixes that. 
1. Set up a couple articles -- on some assign regular WordPress authors, and for others, create at least one Co-Authors Plus guest author, and assign them.
2. Create a Homepage Posts block that displays enough posts to show a mix of authors from both groups.
3. Try hovering over one of the Guest Author's names; note that the URL is incorrect (note that the bottom of the screenshot) -- you can also click the link to confirm it gives you a 404 error:
4. Try some of the other author links for regular …
> Correct link on Co-Authors Plus guest authors in the Homepage Posts block

- newspack-blocks.php
> Bump Version To 1.0.0-alpha.26

- newspack-blocks.php
- src/blocks/homepage-articles/editor.scss
Merging this branch will trigger a release.
> 1.0.1 Release

- src/blocks/donate/editor.scss
- src/blocks/donate/view.scss
- src/shared/sass/_colors.scss
I have reworked the CSS of the block to make sure that on small screens the labels are being displayed correctly.
1. Add a donation block to a page
2. Try resizing your screen
4. Test again
> Update donate block style on small screens

- newspack-blocks-patterns.php
- package.json
- src/blocks/donate/editor.scss
- src/blocks/donate/view.scss
- src/blocks/homepage-articles/editor.js
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/view.scss
- src/patterns/index.js
- src/patterns/style.scss
- src/shared/js/newspack-icon.js
- src/shared/sass/_colors.scss
> Release 3/24/2020

- src/blocks/homepage-articles/view.php
- src/patterns/index.js
- src/patterns/style.scss
> Release 3/31/2020

- src/blocks/carousel/edit.js
A minor change (alphabetization) in order to correctly trigger a release build.
Verify the block works as it did before.
> refactor: alphabetization

- class-newspack-blocks-api.php
- package-lock.json
- package.json
- src/block-styles/core/columns/editor.scss
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/edit.js
- src/patterns/index.js
- src/patterns/style.scss
- src/shared/js/utils.js
> Release: May 5, 2020

- class-newspack-blocks-api.php
- package-lock.json
- package.json
- src/block-styles/core/columns/editor.scss
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/edit.js
- src/patterns/index.js
- src/patterns/style.scss
- src/shared/js/utils.js
> Release 5/05/2020

- src/blocks/carousel/create-swiper.js
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.js
> Articles Carousel: Unify Swiper config

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/block-styles/core/group/editor.scss
- src/block-styles/core/group/index.js
- src/block-styles/core/group/view.scss
- src/block-styles/view.js
- src/blocks/carousel/create-swiper.js
- src/blocks/carousel/edit.js
- src/blocks/carousel/index.js
- src/blocks/carousel/view.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/view.php
- src/blocks/homepage-articles/view.scss
- src/shared/sass/_mixins.scss
> Release — May 19, 2020

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
This PR adds classes based on each post's assigned category and tag to the `<article>` tag, using the same format that is output by the `[post_class()](https://developer.wordpress.org/reference/functions/post_class/)` function. (I opted not to use that function as it's more likely to output classes -- like `type-post` or `has-post-thumbnail` -- that themes could already be using. The tag and category classes are most likely to be used on a site-by-site basis to customize specific taxonomies). 
This change will make it possible to add custom CSS to posts with specific categories or tags within a block, rather than assigning custom CSS to all posts in a block based on a class added to that block.
Closes #363.
2. Add a Homepage Posts block to a page …
> Homepage Posts: add category, tag classes to each article

- class-newspack-blocks.php
- src/blocks/homepage-articles/templates/articles-loop.php
> Release - 6/12/20

- class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/donate/edit.js
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/editor.js
- src/blocks/homepage-articles/editor.scss
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/templates/articles-loop.php
- src/blocks/homepage-articles/utils.js
- src/shared/sass/_colors.scss
> Release 18/06/2020

- src/blocks/donate/edit.js
> Release 23/06/2020

- class-newspack-blocks.php
- src/blocks/donate/edit.js
- src/blocks/donate/index.js
- src/blocks/donate/view.php
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/view.js
- src/blocks/homepage-articles/view.php
- src/blocks/homepage-articles/view.scss
New release. 
* Editable "Donate Now!" button text
* PHP warnings/error fixes for Donate block
* Fix for Homepage Posts block showing the current post
> Release 30/06/2020

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/donate/edit.js
- src/blocks/donate/view.php
- src/blocks/donate/view.scss
- src/components/query-controls.js
> Release Jul 28

- src/blocks/carousel/view.scss
> Release Aug 04

- .circleci/config.yml
- .distignore
- .gitignore
- class-newspack-blocks-api.php
- class-newspack-blocks.php
- composer.json
- composer.lock
- package.json
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/view.php
- src/shared/js/utils.js
> Alpha release Aug 18

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
- src/shared/js/utils.js
> Release Aug 18

- class-newspack-blocks.php
A new release with a hotfix to fix PHP warnings.
> Release (2) 8/18/2020

- .circleci/config.yml
- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/templates/article.php
> Alpha release Aug 25

- .circleci/config.yml
- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/templates/article.php
> Release Aug 25

- src/blocks/homepage-articles/view.scss
> Alpha release Sep 08

- src/blocks/homepage-articles/view.scss
> Release Sep 08

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Alpha release Sep 15

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/view.scss
> Release Sep 15

- src/blocks/carousel/index.js
> Alpha release Sep 29

- src/blocks/carousel/index.js
> Release Sep 29

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/utils.js
> Alpha release Oct 27

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/utils.js
> Release Oct 27

- class-newspack-blocks-api.php
- src/blocks/carousel/index.js
- src/blocks/donate/index.js
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/index.js
- src/blocks/homepage-articles/templates/articles-loop.php
- src/blocks/homepage-articles/view.php
- src/blocks/video-playlist/index.js
> Alpha release Nov 11

- class-newspack-blocks-api.php
- src/blocks/carousel/index.js
- src/blocks/donate/index.js
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/index.js
- src/blocks/homepage-articles/templates/articles-loop.php
- src/blocks/homepage-articles/view.php
- src/blocks/video-playlist/index.js
> Release Nov 11

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/templates/article.php
An alpha release to test sponsor query behavior.
> Alpha Release – Nov. 20

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/templates/article.php
> Release – Nov. 24

- class-newspack-blocks.php
- src/blocks/donate/edit.js
- src/blocks/donate/index.js
- src/blocks/donate/view.php
> Alpha release – Dec. 8

- class-newspack-blocks.php
- src/blocks/donate/edit.js
- src/blocks/donate/index.js
- src/blocks/donate/view.php
> Release – Dec. 8

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/templates/articles-loop.php
- src/blocks/homepage-articles/utils.js
> Alpha release Dec 15

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/templates/articles-loop.php
- src/blocks/homepage-articles/utils.js
> Release – Dec. 15

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/templates/articles-loop.php
- src/blocks/homepage-articles/view.scss
- src/components/query-controls.js
> Alpha release Jan 12

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/templates/articles-loop.php
- src/blocks/homepage-articles/view.scss
- src/components/query-controls.js
> Release Jan 12

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/utils.js
- src/components/autocomplete-tokenfield.js
- src/components/query-controls.js
> Alpha release Jan 19

- amp/homepage-articles/view.js
- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/utils.js
- src/components/autocomplete-tokenfield.js
- src/components/query-controls.js
> Release Jan 19

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/utils.js
> Alpha release Jan 28

- class-newspack-blocks-api.php
- class-newspack-blocks.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/utils.js
> Release Jan 28

- src/blocks/donate/view.php
Passes `$attributes` through to the Donate block render feature. Needed for https://github.com/Automattic/newspack-plugin/pull/810
Full testing instructions in https://github.com/Automattic/newspack-plugin/pull/810.
> feat: pass attributes to donate block render hook

- class-newspack-blocks.php
> Alpha release Feb 08

- class-newspack-blocks.php
> Release Feb 09

- .phpcs.xml.dist
- class-newspack-blocks-api.php
- class-newspack-blocks.php
- composer.json
- composer.lock
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
> Alpha release Feb 16

- includes/class-newspack-blocks.php
> Release Mar 30

- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
> Alpha release Apr 06

- includes/class-newspack-blocks-api.php
- src/blocks/carousel/edit.js
- src/blocks/carousel/index.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/templates/article.php
> Alpha release May 04

- includes/class-newspack-blocks-api.php
- src/blocks/carousel/edit.js
- src/blocks/carousel/index.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/templates/article.php
> Release May 04

- src/blocks/carousel/view.php
A new release - hotfix to release #754
> Release May 05

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/carousel/create-swiper.js
- src/blocks/carousel/edit.js
- src/blocks/carousel/editor.scss
- src/blocks/carousel/index.js
- src/blocks/carousel/view.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Alpha release May 13

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/carousel/create-swiper.js
- src/blocks/carousel/edit.js
- src/blocks/carousel/editor.scss
- src/blocks/carousel/index.js
- src/blocks/carousel/view.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Release May 13

- includes/class-newspack-blocks-api.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Alpha release Jun 01

- includes/class-newspack-blocks-api.php
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Release Jun 01

- block-list.json
> fix: include author profile block in release packages

- package-lock.json
- package.json
- src/blocks/author-profile/block.json
- src/blocks/author-profile/edit.js
- src/blocks/author-profile/shared.scss
- src/blocks/author-profile/view.php
* Adds ability to display the avatar on the left (default) or right, similar to the Media & Text block
* Remove author archive link around the avatar
2. Add multiple Author Profile blocks
3. Play with the alignment option
4. Check without an avatar, you shouldn't see the option
> Add avatar alignment option to author profile block

- package-lock.json
- package.json
- src/blocks/author-profile/block.json
- src/blocks/author-profile/edit.js
- src/blocks/author-profile/editor.scss
- src/blocks/author-profile/index.js
- src/blocks/author-profile/shared.scss
- src/blocks/author-profile/view.php
- src/blocks/homepage-articles/view.scss
> Alpha release Jun 15

- package-lock.json
- package.json
- src/blocks/author-profile/block.json
- src/blocks/author-profile/edit.js
- src/blocks/author-profile/editor.scss
- src/blocks/author-profile/index.js
- src/blocks/author-profile/shared.scss
- src/blocks/author-profile/view.php
- src/blocks/homepage-articles/view.scss
> Release Jun 15

- src/blocks/homepage-articles/utils.js
> Alpha release Jul 06

- src/blocks/homepage-articles/utils.js
> Release Jul 06

- package-lock.json
- package.json
- src/blocks/donate/edit.js
- src/blocks/donate/streamlined.js
- src/blocks/donate/view.php
> Alpha release Jul 19

- .gitignore
- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/utils.js
- src/blocks/homepage-articles/view.scss
- src/components/autocomplete-tokenfield.js
- src/components/query-controls.js
> Alpha release Aug 10

- .gitignore
- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/utils.js
- src/blocks/homepage-articles/view.scss
- src/components/autocomplete-tokenfield.js
- src/components/query-controls.js
> Release Aug 10

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/components/query-controls.js
take into consideration co-authors when filtering the homepage posts block by authors in editor and frontend.
fix #831
1. Install the [CAP plugin](https://wordpress.org/plugins/co-authors-plus/) if not already done and enable it.
2. Add a new co-author.
3. Add a new post, and set your co-author as one of its authors.
4. If #830 is not merged, please apply it to your site, it will fix #601 and shows the co-authors in the authors' filter list.
5. Create a new page, and add the homepage posts block.
4. In the authors' filter, filter by the name of the co-author created in step 2.
5. Observe that the co-author's post is not displayed on the homepage posts block.
6.  Apply this PR, remove the co-author from the filter, and add it again (you might need to reload the page before).
7. Observe the …
> fix(co-authors plus): filter homepage posts block posts by co-authors

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/streamlined.js
- src/components/query-controls.js
> Alpha release Aug 17

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/streamlined.js
- src/components/query-controls.js
> Release Aug 17

- includes/class-newspack-blocks.php
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/edit.js
- src/blocks/donate/index.js
- src/blocks/donate/view.php
See https://github.com/Automattic/newspack-plugin/pull/1095
Changes how "streamlined" option is handled. Instead of a block attribute, it's now a function of the donation platform. 
_Follow steps in https://github.com/Automattic/newspack-plugin/pull/1095_
> feat: streamlined version handling

- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/author-profile/edit.js
- src/blocks/author-profile/editor.scss
- src/blocks/author-profile/index.js
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/edit.js
- src/blocks/donate/editor.scss
- src/blocks/donate/streamlined.js
- src/blocks/donate/streamlined.scss
- src/blocks/donate/view.php
> Alpha release Aug 31

- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/author-profile/edit.js
- src/blocks/author-profile/editor.scss
- src/blocks/author-profile/index.js
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/edit.js
- src/blocks/donate/editor.scss
- src/blocks/donate/streamlined.js
- src/blocks/donate/streamlined.scss
- src/blocks/donate/view.php
> Release Aug 31

- src/blocks/homepage-articles/view.php
- src/shared/js/utils.js
> Release Sep 09

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/templates/articles-loop.php
> Alpha release Sep 28

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/templates/articles-loop.php
> Release Sep 28

- includes/class-newspack-blocks.php
> Hotfix release Sep 28

- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/view.php
- src/blocks/homepage-articles/view.scss
> Alpha release Oct 05

- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/view.php
- src/blocks/homepage-articles/view.scss
> Release Oct 05

- includes/class-newspack-blocks.php
> Alpha release Nov 09

- includes/class-newspack-blocks.php
> Release Nov 09

- src/blocks/iframe/class-wp-rest-newspack-iframe-controller.php
> Alpha release Nov 16

- CHANGELOG.md
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/iframe/class-wp-rest-newspack-iframe-controller.php
> Release Nov 18

- package-lock.json
- package.json
Fixes a build error due to a missing dependency in Newspack Components.
Test `npm ci && npm run build`. Also, all CI jobs below should be passing. 👇 No functional changes.
> fix: update newspack-components dep version

- package-lock.json
- package.json
> Alpha release Nov 18

- .circleci/config.yml
We are currently requiring node v16 and this PR updates the node version for the CI images.
CI tasks should pass.
> ci: update node version

- .circleci/config.yml
- .gitignore
- __mocks__/@stripe/stripe-js/pure/index.js
- babel.config.js
- composer.json
- composer.lock
- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/create-swiper.js
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/streamlined.js
- src/blocks/donate/streamlined.scss
- src/blocks/donate/streamlined.test.js
- src/blocks/donate/view.php
- src/setupTests.js
> Alpha release Dec 09

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- __mocks__/@stripe/stripe-js/pure/index.js
- babel.config.js
- composer.json
- composer.lock
- includes/class-newspack-blocks.php
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/create-swiper.js
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/streamlined.js
- src/blocks/donate/streamlined.scss
- src/blocks/donate/streamlined.test.js
- src/blocks/donate/view.php
- src/setupTests.js
> Release Dec 14

- CHANGELOG.md
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Release Dec 15

- package-lock.json
- package.json
- src/blocks/carousel/view.php
> Alpha release Dec 16

- .circleci/config.yml
- .github/workflows/auto-merge.yml
- composer.lock
- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/edit.js
- src/blocks/carousel/editor.scss
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/donate/streamlined.js
- src/blocks/donate/streamlined.test.js
- src/blocks/donate/view.php
- src/blocks/iframe/block.json
- src/blocks/iframe/class-wp-rest-newspack-iframe-controller.php
- src/blocks/iframe/edit.js
- src/blocks/iframe/iframe-placeholder.js
- src/blocks/iframe/view.php
A new alpha release. Awaiting https://github.com/Automattic/newspack-blocks/pull/949
> Alpha release Jan 06

- src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
- src/blocks/author-list/edit.js
- src/blocks/author-list/view.php
- src/blocks/author-profile/edit.js
Fixes several errors stemming from updated PHPCS and eslint rulesets.
No changes. All checks should be passing. 👇
> fix: lint errors

- block-list.json
> Alpha release Jan 11

- src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
Fixes a bug with fetching WP users if the Co-Authors Plus plugin isn't active.
1. Deactivate the CAP plugin.
2. On `master`, add an Author List block. Observe that the block displays nothing in both the editor and on the front-end.
3. Check out this branch, refresh both, and confirm that the block now shows WP users as expected.
4. Activate the CAP plugin, refresh both, confirm that the block now shows both WP users and CAP guest authors.
> fix(author-list): user query when CAP is not installed

- src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
> Alpha release Jan 14

- src/block-styles/core/columns/view.scss
> Alpha release Jan 18

- src/block-styles/core/columns/view.scss
- src/blocks/video-playlist/view.php
> Alpha release Jan 24

- src/blocks/carousel/view.scss
Closes #504.
cc @laurelfulford – this fix does not seem to cause any issues when using Newspack theme, but I'd appreciate you taking a look at it anyway :)  
Observe #504 not reproducible anymoe.
> fix(carousel): width issues

- .circleci/config.yml
- .distignore
- CHANGELOG.md
- includes/class-newspack-blocks.php
- newspack-blocks.php
- package-lock.json
- package.json
> Release Feb 08

- CHANGELOG.md
- composer.lock
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/view.scss
> Release Feb 22

- src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
Fixes a bug in the alphabetization of users or guest authors that have spaces in their last names.
1. Create a WP user and a guest author, each with first and last name filled out and with a space in the last name, e.g. "Firstname Lastname II". Also ensure that the last name appears in the display name of the user (the block will alphabetize by last name only if it appears visually in the display name, to avoid reader confusion).
2. Add an Author List block to a post and ensure that it renders both test authors created in step 1.
3. On `master`, observe that the authors with spaces in their names get alphabetized based on their display names, not their last names.
4. Check out this branch and confirm that the authors get alphabetized by their last names, as expected.
---
- To see the …
> fix(author-list): handle alphabetizing last names containing spaces

- src/blocks/donate/edit.js
- src/blocks/donate/editor.scss
- src/blocks/donate/index.js
- src/blocks/donate/streamlined/style.scss
- src/blocks/donate/view.php
- src/blocks/donate/view.scss
This PR adds 2 new styles to the Donate Block: "Alternate" and "Minimal"
__Default style__
__Alternate style (using Newspack as the Reader Revenue platform)__
__Alternate style (using Stripe as the Reader Revenue platform)__
__Minimal style (using Newspack as the Reader Revenue platform)__
__Minimal style (using Stripe as the Reader Revenue platform)__
2. On a page, insert 3 donate blocks -- 1 using the default style, 1 using the alternate style and 1 using the minimal style
3. Test if the blocks work
4. Test the different Reader Revenue platforms
> Add alternate and minimal styles to donate block

- composer.lock
- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
- src/blocks/author-profile/class-wp-rest-newspack-authors-controller.php
- src/blocks/donate/edit.js
- src/blocks/donate/editor.scss
- src/blocks/donate/index.js
- src/blocks/donate/streamlined/style.scss
- src/blocks/donate/view.php
- src/blocks/donate/view.scss
- src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/utils.js
- src/components/query-controls.js
> Alpha release Mar 31

- includes/class-newspack-blocks.php
> Alpha release Apr 05

- composer.lock
- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/view.php
- src/blocks/donate/view.scss
> Alpha release May 02

- package-lock.json
- package.json
- src/blocks/carousel/view.php
- src/blocks/donate/view.scss
- src/blocks/homepage-articles/templates/article.php
> Alpha release May 05

- CHANGELOG.md
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/view.php
- src/blocks/donate/view.scss
- src/blocks/homepage-articles/templates/article.php
> Release May 17

- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/edit.js
- src/blocks/carousel/index.js
- src/blocks/carousel/view.php
- src/blocks/carousel/view.scss
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/store.js
- src/blocks/homepage-articles/templates/article.php
- src/blocks/homepage-articles/utils.js
- src/blocks/homepage-articles/view.scss
- src/components/editor-panels.js
- src/shared/js/utils.js
- src/shared/sass/_preview.scss
> Alpha release May 19

- src/blocks/donate/view.php
Related to https://github.com/Automattic/newspack-plugin/issues/1650, but for other platforms
1. On `master` set a suggested monthly donation amount to 1000 
2. Observe that on the the frontend, the Donate block renders empty amount in "Annually" tab
3. Switch to this branch, observe a value rendered
> fix(donate): amount formatting

- package-lock.json
- package.json
- src/blocks/author-profile/edit.js
- src/blocks/author-profile/editor.scss
Fixes a bug that prevents selection of guest authors via autocomplete suggestion in the Author Profile block.
Also bumps `newspack-components` to v2.1.0, which includes [this fix](https://github.com/Automattic/newspack-plugin/pull/1679).
Closes #1184.
Confirm that #1184 is not reproducible and that you can search for and select both guest authors and WP users via the autocomplete field.
> fix: guest author selection in Author Profile block

- CHANGELOG.md
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/author-profile/edit.js
- src/blocks/author-profile/editor.scss
The post-release job after the latest hotfix release is experiencing failures due to a merge conflict. This should fix the conflict.
Verify that `npm ci --legacy-peer-deps && npm run build` run successfully, and that all CI jobs succeed below. 👇
> fix: resolve merge conflict with release

- package-lock.json
- package.json
- src/blocks/donate/edit.tsx
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/streamlined/style.scss
- src/blocks/donate/streamlined/utils.ts
- src/blocks/donate/types.d.ts
- src/blocks/donate/utils.ts
- src/blocks/donate/view.php
- src/blocks/donate/view.scss
- tsconfig.json
Some UX and mobile-styling tweaks to the Donate block, and a conversion to TypeScript. 
Closes #1077
1. Insert a Donate block, observe the donation frequency tabs are in one line on all screen sizes (not stacked, as they used to be) 
2. Observe that the "Other" donation tier has a minimum of 1 (e.g. when using arrow keys, it will stop at 1)
3. With Stripe set as Reader Revenue platform:
1. Observe that if card payment is the only available option, the card UI will be visible right away
2. If payment request (Apple/Google/Web pay) is available, the card UI will be displayed only after clicking "Donate with card" button
> Donate block – mobile style; UX tweaks

- src/blocks/donate/streamlined/index.ts
- src/types/index.d.ts
Refresh reader authentication state on donation.
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1882
2. On a new session with reader activation, donate using an already registered email
3. Observe the "Sign In" is changed to "My Account"
4. Click on "My Account" and confirm you're prompted to finish signing in
5. Start a new session and donate using a new email
6. Observe the "Sign In" is changed to "My Account"
7. Click and confirm you are redirected to the "My Account" page
> feat(donate): refresh reader authentication

- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/streamlined/utils.ts
- src/types/index.d.ts
> Alpha release Aug 12

- src/blocks/donate/block.json
- src/blocks/donate/edit.tsx
- src/blocks/donate/editor.scss
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/streamlined/utils.ts
- src/blocks/donate/types.d.ts
- src/blocks/donate/view.php
Handles the new "minimum donation" setting from https://github.com/Automattic/newspack-plugin/pull/1895 in the Donate block front-end and editor.
Closes #1211 and https://github.com/Automattic/newspack-plugin/issues/1886.
See testing instructions in https://github.com/Automattic/newspack-plugin/pull/1895.
> feat: handle minimum donation option in Donate block

- composer.lock
- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
- src/blocks/author-list/edit.js
- src/blocks/author-list/view.php
- src/blocks/donate/block.json
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/edit.tsx
- src/blocks/donate/editor.scss
- src/blocks/donate/streamlined/index.test.js
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/streamlined/utils.ts
- src/blocks/donate/types.d.ts
- src/blocks/donate/view.php
- src/blocks/homepage-articles/view.php
> Alpha release Aug 26

- src/blocks/donate/view.scss
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/view.php
- src/blocks/homepage-articles/view.scss
> Alpha release Sep 06

- CHANGELOG.md
- composer.lock
- includes/class-newspack-blocks-api.php
- includes/class-newspack-blocks.php
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
- src/blocks/author-list/edit.js
- src/blocks/author-list/view.php
- src/blocks/donate/block.json
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/edit.tsx
- src/blocks/donate/editor.scss
- src/blocks/donate/streamlined/index.test.js
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/streamlined/utils.ts
- src/blocks/donate/types.d.ts
- src/blocks/donate/view.php
- src/blocks/donate/view.scss
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/view.php
- src/blocks/homepage-articles/view.scss
> Release Sep 14

- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
Adds metadata passing to the handler that creates a WC Memberships membership.
_Follow instructions in https://github.com/Automattic/newspack-plugin/pull/2002_
> feat(donations): pass client metadata when creating a WC membership

- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
Fixes a regression introduced in #1267.
1. On `master`, set up a site with Stripe as Reader Revenue platform
2. Make a recurring donation, observe the WC order resulting from it is attributed to a guest user 
3. Switch to this branch, make a recurring donation, observe the WC order is attributed to the created user
> fix(donate): user id handling

- CHANGELOG.md
- README.md
- composer.json
- composer.lock
- newspack-blocks.php
- package-lock.json
- package.json
- phpunit.xml.dist
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/streamlined/utils.ts
- src/blocks/donate/view.php
- tests/bootstrap.php
> Release Sep 27

- .circleci/config.yml
- CHANGELOG.md
- composer.json
- composer.lock
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/edit.js
- src/blocks/carousel/view.php
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Release Oct 19

- .circleci/config.yml
- composer.lock
- package-lock.json
- package.json
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> Alpha release Dec 01

- src/blocks/author-list/edit.js
- src/blocks/author-profile/edit.js
- src/blocks/donate/block.json
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/edit/FrequencyBasedLayout.tsx
- src/blocks/donate/edit/components/AdditionalFields.tsx
- src/blocks/donate/edit/components/AmountValueInput.tsx
- src/blocks/donate/edit/components/index.tsx
- src/blocks/donate/edit/index.tsx
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
- src/blocks/donate/streamlined/index.test.js
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/streamlined/style.scss
- src/blocks/donate/styles/editor.scss
- src/blocks/donate/types.ts
- src/blocks/homepage-articles/utils.ts
- src/components/editor-panels.js
- src/setup/unregister-blocks.js
- src/shared/js/utils.js
> Alpha release Dec 22

- composer.lock
- includes/class-newspack-blocks-api.php
- package-lock.json
- package.json
- src/blocks/carousel/edit.js
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Alpha release Jan 26

- CHANGELOG.md
- composer.lock
- includes/class-newspack-blocks-api.php
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/edit.js
- src/blocks/homepage-articles/block.json
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/templates/article.php
> Release Feb 15

- __mocks__/@stripe/stripe-js/pure/index.js
- composer.lock
- package-lock.json
- package.json
- src/blocks/author-list/block.json
- src/blocks/author-list/view.php
- src/blocks/author-profile/view.php
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
- src/blocks/donate/streamlined/index.test.js
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/styles/view.scss
- src/blocks/homepage-articles/view.scss
- src/blocks/shared/author.js
> Alpha release Feb 17

- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/types.ts
Adds metadata to the donations via donation block. See https://github.com/Automattic/newspack-plugin/pull/2300
See https://github.com/Automattic/newspack-plugin/pull/2300
> feat: add popup info to donation block

- CHANGELOG.md
- __mocks__/@stripe/stripe-js/pure/index.js
- composer.lock
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/author-list/block.json
- src/blocks/author-list/view.php
- src/blocks/author-profile/view.php
- src/blocks/donate/class-wp-rest-newspack-donate-controller.php
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
- src/blocks/donate/streamlined/index.test.js
- src/blocks/donate/streamlined/index.ts
- src/blocks/donate/styles/view.scss
- src/blocks/homepage-articles/view.scss
- src/blocks/shared/author.js
> Release Feb 28

- README.md
- src/blocks/donate/index.js
- src/blocks/iframe/index.js
- src/setup/placeholder-blocks.js
Updates all newspack.pub documentation references in code to help.newspack.com.
> help.newspack.com doc links

- src/blocks/donate/styles/view.scss
https://github.com/Automattic/newspack-blocks/pull/1391 as an alpha-hotfix.
> fix(modal-checkout): z-index when used w/ Campaigns [alpha hotfix]

- includes/class-newspack-blocks.php
- src/blocks/donate/edit/index.tsx
- src/types/index.d.ts
Same as https://github.com/Automattic/newspack-plugin/pull/2397 but for the Donate Block.
> feat(donate): add recaptcha panel in the editor

- .hooks/pre-push
- composer.json
- composer.lock
- includes/class-newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/donate/edit/index.tsx
- src/types/index.d.ts
> Alpha release Apr 13

- .hooks/pre-push
- CHANGELOG.md
- composer.json
- composer.lock
- includes/class-newspack-blocks.php
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/donate/edit/index.tsx
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer.php
- src/types/index.d.ts
> Release Apr 24

- .distignore
- package-lock.json
- package.json
- src/blocks/homepage-articles/view.scss
> Alpha release May 11

- .distignore
- CHANGELOG.md
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/homepage-articles/view.scss
> Release May 23

- composer.lock
- includes/class-modal-checkout.php
- package-lock.json
- package.json
- src/block-styles/core/columns/view.scss
- src/blocks/checkout-button/block.json
- src/blocks/checkout-button/edit.js
- src/blocks/checkout-button/save.js
- src/blocks/donate/styles/style-variations.scss
- src/blocks/homepage-articles/view.scss
- src/blocks/video-playlist/editor.scss
- src/templates/author-profile-card.php
> Alpha release May 25

- includes/class-modal-checkout.php
- src/blocks/checkout-button/block.json
- src/blocks/checkout-button/edit.js
- src/blocks/checkout-button/save.js
- src/blocks/checkout-button/view.php
- src/modal-checkout/modal.js
- src/modal-checkout/modal.scss
Allow the product variation selection to be made by the reader as a pre-checkout modal.
1. Create a production with variations
2. Make sure to include a description text to at least one of the variations
3. Add a Checkout Button block to a page and select the product
4. Confirm the default state is as above: "Allow the reader to select the variation before checkout." checked and empty variation selection (`--`)
5. Save, visit the page, and confirm clicking the button renders the pre-checkout modal
6. Click on any option and confirm checkout loads with the selected variation
7. Close the modal, click on the button again, select a different variation, and confirm it loads the checkout with the selected variation
8. Edit the page, toggle off the "Allow the reader to select the variation …
> feat(checkout-button): front-end product variation selection

- composer.lock
- package-lock.json
- package.json
- src/blocks/donate/edit/FrequencyBasedLayout.tsx
- src/blocks/donate/edit/TierBasedLayout.tsx
- src/blocks/donate/frequency-based/style.scss
- src/blocks/donate/streamlined/style.scss
- src/blocks/donate/styles/editor.scss
- src/blocks/donate/tiers-based/style.scss
- src/modal-checkout/checkout.scss
- src/modal-checkout/templates/checkout-form.php
> Alpha release Jun 22

- includes/class-newspack-blocks.php
- src/blocks/carousel/index.js
I missed some linting while reviewing #1482, this fixes it.
> chore: fix remaining lint from #1482

- includes/class-modal-checkout.php
- src/modal-checkout/checkout.scss
- src/modal-checkout/index.js
- src/modal-checkout/templates/checkout-form.php
> feat(modal-checkout): render order details under a set of conditions

- composer.lock
- includes/class-modal-checkout.php
- package-lock.json
- package.json
- src/blocks/carousel/editor.scss
- src/blocks/carousel/view.scss
- src/modal-checkout/checkout.scss
- src/modal-checkout/modal.js
- src/modal-checkout/modal.scss
- src/modal-checkout/templates/billing-form.php
- src/modal-checkout/templates/checkout-form.php
> Alpha release Aug 24

- CHANGELOG.md
- composer.lock
- includes/class-modal-checkout.php
- newspack-blocks.php
- package-lock.json
- package.json
- src/blocks/carousel/editor.scss
- src/blocks/carousel/view.scss
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-frequency-based.php
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
- src/modal-checkout/checkout.scss
- src/modal-checkout/modal.js
- src/modal-checkout/modal.scss
- src/modal-checkout/templates/billing-form.php
- src/modal-checkout/templates/checkout-form.php
> Release Aug 24

- src/blocks/author-list/edit.js
- src/blocks/author-profile/edit.js
- src/blocks/homepage-articles/edit.js
- src/blocks/homepage-articles/utils.ts
https://github.com/Automattic/newspack-blocks/pull/1551 as a hotfix
> Hotfix: WP 6.4 HPB rendering issue

- src/modal-checkout/modal.js
Implements the RAS overlay management to the modal checkout.
Further details and instructions at https://github.com/Automattic/newspack-plugin/pull/2708
> feat(modal-checkout): implement ras overlay

- CHANGELOG.md
- includes/class-modal-checkout.php
- newspack-blocks.php
- package-lock.json
- package.json
- src/modal-checkout/checkout.scss
- src/modal-checkout/modal.js
- src/modal-checkout/modal.scss
- src/modal-checkout/templates/form-login.php
- src/modal-checkout/templates/thankyou.php
> Alpha release Oct 20

- includes/class-modal-checkout.php
- src/blocks/checkout-button/block.json
- src/blocks/checkout-button/edit.js
- src/blocks/donate/block.json
- src/blocks/donate/edit/index.tsx
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-frequency-based.php
- src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
- src/blocks/donate/types.ts
- src/components/redirect-after-success.tsx
- src/modal-checkout/checkout.scss
- src/modal-checkout/modal.js
- src/modal-checkout/templates/thankyou.php
> Alpha release Oct 31

- includes/class-modal-checkout.php
Taking over that responsibility from the Theme.
_Follow instructions in https://github.com/Automattic/newspack-theme/pull/2191_
> feat(modal-checkout): dequeue WC styles

- includes/class-modal-checkout.php
- package-lock.json
- package.json
- src/blocks/homepage-articles/edit.js
- src/modal-checkout/templates/checkout-form.php
> Alpha release Nov 03

- src/modal-checkout/checkout.scss
> fix(modal-checkout): place order button width

- includes/class-modal-checkout.php
Implements a filter for adding custom cart item data for the modal checkout to be used by https://github.com/Automattic/newspack-plugin/pull/2740.
> feat(modal-checkout): add filter to cart item data

- includes/class-newspack-blocks.php
Fixes some linting issues from https://github.com/Automattic/newspack-blocks/pull/1412
> chore: fix linting issues

- CHANGELOG.md
- includes/class-newspack-blocks.php
- newspack-blocks.php
- package-lock.json
- package.json
> Release Jan 25

- includes/test-file.php
This is a test.
Closes # .
1.
2.
3.
> feat: test feature for epic release flow raz
